#+title: Exercise
#+property: header-args:racket :lang sicp
#+STARTUP: latexpreview
#+OPTIONS: tex:t

#+NAME: pre
#+begin_src racket
(define (reduce f xs acc)
  (if (null? xs) acc
      (reduce f (cdr xs) (f (car xs) acc))))
(define (sum-numbers xs)
  (reduce + xs 0))

(sum-numbers (list 1 2 3))
#+end_src

#+RESULTS:
: 6


* 2.1 rational

#+begin_src racket
(define (sig x)
  (cond [(> x 0) 1]
        [(< x 0) -1]
        [else 0]))
(define (gcd a b)
  (if (= b 0) a
      (gcd b (modulo a b))))

(define (make-rat n d)
  (let ([sign (* (sig n) (sig d))]
        [num (abs n)]
        [den (abs d)])
    (let ([p (gcd num den)])
      (cons (* sign (quotient num p)) (quotient den p)))))
(define (numer x) (car x))
(define (denom x) (cdr x))
(define (print-rat x)
  (newline)
  (display (numer x))
  (display "/")
  (display (denom x)))

(print-rat (make-rat 6 -8))
#+end_src

#+RESULTS:
:
: -3/4#<void>

* 2.2 point and segment

#+NAME: point-segment
#+begin_src racket
; regard point as vector
(define make-point cons)
(define x-point car)
(define y-point cdr)
(define (add-point p q) (make-point (+ (x-point p) (x-point q)) (+ (y-point p) (y-point q))))
(define (half-vector p) (make-point (/ (x-point p) 2) (/ (y-point p) 2)))
(define (midpoint p q) (half-vector (add-point p q)))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define make-segment cons)
(define start-segment car)
(define end-segment cdr)
(define (midpoint-segment l) (midpoint (start-segment l) (end-segment l)))

#+end_src

#+begin_src racket :noweb yes
;<<point-segment>>
(print-point (midpoint-segment
              (make-segment (make-point 0 2) (make-point 2 0))))
#+end_src

#+RESULTS:
:
: (1,1)#<void>

* 2.3

I know it's bad...

#+NAME: use-rect
#+begin_src racket :noweb yes :results none
;<<point-segment>>
;<<pre>>
(define (square x) (* x x))
(define (distance-point p q)
  (sqrt (+ (square (- (x-point p) (x-point q)))
           (square (- (y-point p) (y-point q))))))
(define (length-segment l)
  (distance-point (start-segment l) (end-segment l)))

(define (perimiter-rectangle r)
  (let ([lengths (side-lengths-rectangle r)])
    (* 2 (+ (car lengths) (cdr lengths)))))

(define (area-rectangle r)
  (let ([lengths (side-lengths-rectangle r)])
    (* (car lengths) (cdr lengths))))
#+end_src

#+begin_src racket :noweb yes
;<<use-rect>>
(define (make-rectangle p q r) (cons r (cons p q))) ; defined by three point, r not on diagonal (make-segment p q)
(define (side-lengths-rectangle rect)
  (cons (distance-point (car rect) (cadr rect))
        (distance-point (car rect) (cddr rect))))

(let ([rect (make-rectangle (make-point 3 0) (make-point 0 4) (make-point 3 4))])
  (list (perimiter-rectangle rect) (area-rectangle rect)))
#+end_src

#+RESULTS:
: (14 12)

#+begin_src racket :noweb yes
;<<use-rect>>
(define make-rectangle- cons) ; defined by two segment(not parallel)
(define (side-lengths-rectangle r)
  (cons (length-segment (car r))
        (length-segment (cdr r))))

(let ([rect (make-rectangle- (make-segment (make-point 3 4) (make-point 3 0)) (make-segment (make-point 3 4) (make-point 0 4)))])
  (list (perimiter-rectangle rect) (area-rectangle rect)))
#+end_src

#+RESULTS:
: (14 12)

* 2.4 use lambda to implement cons, car, cdr

#+begin_src racket
(define (cons x y)
  (lambda (m) (m x y)))

(define (cdr z)
  (z (lambda (x y) y)))

(cdr (cons 1 2))
#+end_src

#+RESULTS:
: 2

src_lisp[:exports code]{(cdr (cons 1 2)) => (cdr (lambda (m) (m 1 2))) => ((lambda (m) (m 1 2)) (lambda (x y) y)) => ((lambda (x y) y) 1 2) => 2}

* 2.5

#+begin_src racket
(define (pown base n)
  (define (iter i acc)
    (if (= i n) acc (iter (inc i) (* base acc))))
  (iter 0 1))

(define (cons n1 n2)
  (* (pown 2 n1) (pown 3 n2)))

(define (car z)
  (if (not (= (modulo z 3) 0)) (/ (log z) (log 2)) (car (quotient z 3))))

(define (cdr z)
  (if (not (= (modulo z 2) 0)) (/ (log z) (log 3)) (cdr (quotient z 2))))

(list (car (cons 3 4)) (cdr (cons 3 4)))
#+end_src

#+RESULTS:
: (3.0 4.0)

* 2.6

#+begin_src racket :results none
(define zero (lambda (f) (lambda (x) x)))

(define (inc n) (lambda (f) (lambda (x) (f ((n f) x)))))

(define (id x) (lambda (x) x))
(define zero_ (lambda (f) id))
(define one (lambda (f) (lambda (x) (f x))))
(define two (lambda (f) (lambda (x) (f (f x)))))

(define (add m n) (lambda f) (lambda (x) ((m f) ((n f) x))))
#+end_src

The expr in add <src_racket[:exports code]{(m f) => (lambda (y) (f (f ... (f y))))} (has the number of m of the "f"),
and the expr <src_racket[:exports code]{((m f) ((n f) x)) => (f (f ... (f (f_ (f_ ... (f_ x))))))}.

* 2.7, 2.8

#+NAME: interval-calc
#+begin_src racket :results none
(define (add-interval x y)
  (make-interval (+ (lower-bound x) (lower-bound y))
                 (+ (upper-bound x) (upper-bound y))))

(define (mul-interval x y)
  (let ([p1 (* (lower-bound x) (lower-bound y))]
        [p2 (* (lower-bound x) (upper-bound y))]
        [p3 (* (upper-bound x) (lower-bound y))]
        [p4 (* (upper-bound x) (upper-bound y))])
    (make-interval (min p1 p2 p3 p4)
                   (max p1 p2 p3 p4))))

(define (make-interval a b) (cons a b))

(define lower-bound car)
(define upper-bound cdr)
(define (sub-interval x y)
  (make-interval (- (lower-bound x) (upper-bound y))
                 (- (upper-bound x) (lower-bound y))))
#+end_src

#+begin_src racket :noweb yes
;<<interval-calc>>
(let ([a (make-interval 1 2)]
      [b (make-interval 3 4)])
  (list
    (add-interval a b)
    (sub-interval a b)))
#+end_src

#+RESULTS:
: ((4 . 6) (-3 . -1))

* 2.9

For interval $(a, b)$, the center is $c = \frac {a + b} 2$, the width is $w = b - c = \frac {b - a} 2$.

For two interval $x = (a_1, b_1)$, $y = (a_2, b_2)$. So $x + y = (a_1 + a_2, b_1 + b_2)$, $x - y = (a_1 - b_2, b_1 - a_2)$.

So $w_{x+y} = \frac {b_1 + b_2 - (a_1 + a_2)} 2 = w_x + w_y$, $w_{x-y} = \frac {b_1 + b_2 - (a_1 + a_2)} 2 = w_x + w_y$. This fits the intuision that the precision goes down as calculation number increases.

For $x > 1$ and $y > 1$, $x \mul y = (a_1\mul a_2, b_1\mul b_2)$. $w_{x\mul y} = \frac {b_1\mul b_2 - a_1\mul a_2} 2$.

$w_xw_y = \frac {b_1b_2 + a_1a_2 - b_1a_2 - b_2a_1} 4$, $c_x c_y = \frac {b_1b_2 + a_1a_2 + b_1a_2 + b_2a_1} 4$. $w_xc_y = \frac {b_1b_2 - a_1a_2 + b_1a_2 - b_2a_1} 4$, $c_xw_y = \frac {b_1b_2 - a_1a_2 - b_1a_2 + b2_a_1} 4$.

So $w_{x\mul y} = w_xc_y + w_yc_x \quad (x > 1, y > 1)$, not only defined by $w_x$ and $w_y$.

* 2.10

#+NAME: div-interval
#+begin_src racket :results none
; example
(define (div-interval x y)
  (mul-interval x
                (make-interval (/ 1.0 (upper-bound y))
                               (/ 1.0 (lower-bound y)))))
#+end_src

#+begin_src racket :noweb yes
;<<interval-calc>>
(define (div-interval x y)
  (if (and (< (lower-bound y) 0) (> (upper-bound y) 0))
      error
      (mul-interval x
                   (make-interval (/ 1.0 (upper-bound y))
                                  (/ 1.0 (lower-bound y))))))

(list
 (div-interval (make-interval 2 4) (make-interval 1 2))
 (div-interval (make-interval 2 4) (make-interval 0.0 1))
 (div-interval (make-interval 2 4) (make-interval -1 1))
 (div-interval (make-interval 2 4) (make-interval -2 -4))
)
#+end_src

#+RESULTS:
: ((1.0 . 4.0) (2.0 . +inf.0) #<procedure:error> (-2.0 . -0.5))

* 2.11

According to my example of interval calc $x \cdot y$, there are 3 special points for multiply computation: 1, 0 and -1.

|---------+------+----------+-----------+-------|
| b\a     | <-1  | (-1,0)   | (0, 1)    | >1    |
|---------+------+----------+-----------+-------|
| <-1     | >1 ↑ | >0 ↑     | <0 -      | <-1 ↓ |
|---------+------+----------+-----------+-------|
| (-1, 0) | .    | (0, 1) ↑ | (-1, 0) - | <0 ↓  |
|---------+------+----------+-----------+-------|
| (0, 1)  | .    | .        | (0, 1) ↓  | >0 -  |
|---------+------+----------+-----------+-------|
| >1      | .    | .        | .         | >1 ↑  |
|---------+------+----------+-----------+-------|

"↑" means the result bigger than the operands, "↓" means smaller, "-" means the result is between the two operands.

|--------------------+------------+----------------+--------------------+------------------+--------------+----------|
| y\x                | (<-1, <-1) | (<-1, (-1, 0)) | ((-1, 0), (-1, 0)) | ((0, 1), (0, 1)) | ((0, 1), >1) | (>1, >1) |
|--------------------+------------+----------------+--------------------+------------------+--------------+----------|
| (<-1, <-1)         | (hh, ll)   | (hh, ll)       | (hh, ll)           | (hl, lh)         | (hl, lh)     | (hl, lh) |
|--------------------+------------+----------------+--------------------+------------------+--------------+----------|
| (<-1, (-1, 0))     | .          | (hh, ll)       | (hh, ll)           | (hl, lh)         | (hl, lh)     | (hl, lh) |
|--------------------+------------+----------------+--------------------+------------------+--------------+----------|
| ((-1, 0), (-1, 0)) | .          | .              | (hh, ll)           | (hl, lh)         | (hl, lh)     | (hl, lh) |
|--------------------+------------+----------------+--------------------+------------------+--------------+----------|
| ((0, 1), (0, 1))   | .          | .              | .                  | (ll, hh)         | (ll, hh)     | (ll, hh) |
|--------------------+------------+----------------+--------------------+------------------+--------------+----------|
| ((0, 1), >1)       | .          | .              | .                  | .                | (ll, hh)     | (ll, hh) |
|--------------------+------------+----------------+--------------------+------------------+--------------+----------|
| (>1, >1)           | .          | .              | .                  | .                | .            | (ll, hh) |
|--------------------+------------+----------------+--------------------+------------------+--------------+----------|

Ex. (hl, lh) means <src_racket[:exports code]{(make-interval (* (upper-bound x) (lower-bound y)) (* (lower-bound x) (upper-bound y)))}.

It seems that 1 and -1 make no difference...

|--------+----------+----------------------------+----------|
| y\x    | (-, -)   | (-, +)                     | (+, +)   |
|--------+----------+----------------------------+----------|
| (-, -) | (hh, ll) | (hl, lh)                   | (hh, ll) |
|--------+----------+----------------------------+----------|
| (-, +) | .        | (min(hl, lh), max(hh, ll)) | (hl, hh) |
|--------+----------+----------------------------+----------|
| (+, +) | .        | .                          | (ll, hh) |
|--------+----------+----------------------------+----------|

Consider the min and max computation(this contains 4 conditions!), there are exact 9 conditions.

|-----------------------+----------------|
| lx < ly < 0 < hx < hy | (lx hy, hx hy) |
|-----------------------+----------------|
| ly < lx < 0 < hx < hy | (lx hy, .)     |
|-----------------------+----------------|
| lx < ly < 0 < hy < hx | (ly hx, .)     |
|-----------------------+----------------|
| ly < lx < 0 < hy < hx | (ly hx, .)     |
|-----------------------+----------------|

#+begin_src racket :noweb yes
;<<interval-calc>>
(define (interval-positive? x) (> (lower-bound x) 0))
(define (interval-negative? x) (< (upper-bound x) 0))
(define (interval-span-zero? x) (and (< (lower-bound x) 0) (> (upper-bound x) 0)))
(define (mul-interval- x y)
  (let ([h upper-bound]
        [l lower-bound])
    (cond
      [(and (interval-negative? x) (interval-negative? y))
       (make-interval (* (h x) (h y)) (* (l x) (l y)))]
      [(and (interval-positive? x) (interval-positive? y))
       (make-interval (* (l x) (l y)) (* (h x) (h y)))]
      [(and (interval-positive? x) (interval-negative? y))
       (make-interval (* (h x) (h y)) (* (l x) (l y)))]
      [(and (interval-positive? x) (interval-span-zero? y))
       (make-interval (* (h x) (l y)) (* (h x) (h y)))]
      [(and (interval-negative? x) (interval-span-zero? y))
       (make-interval (* (l x) (h y)) (* (h x) (l y)))]
      ; below they both span zero.
      [else (if (and (interval-span-zero? x) (interval-span-zero? y))
                (cond
                  [(and (< (l x) (l y)) (< (h x) (h y)))
                   (make-interval (* (l x) (h y)) (* (h x) (h y)))]
                  [(and (< (l y) (l x)) (< (h x) (h y)))
                   (make-interval (* (l x) (h y)) (* (h x) (h y)))]
                  [(and (< (l x) (l y)) (< (h y) (h x)))
                   (make-interval (* (l y) (h x)) (* (h x) (h y)))]
                  [(and (< (l y) (l x)) (< (h y) (h x)))
                   (make-interval (* (l y) (h x)) (* (h x) (h y)))])
                ; if the above conditions are not exaustive,
                ; this function may run into infinite recursion.
                (mul-interval- y x))]
      )))


(list
 (list
  (interval-span-zero? (make-interval 4 8))
  (interval-positive? (make-interval 4 8))
  (interval-negative? (make-interval 4 8)))
 (list
  (mul-interval- (make-interval -2 1) (make-interval -1 2))
  (mul-interval- (make-interval -1 2) (make-interval -2 1))
  (mul-interval- (make-interval -2 2) (make-interval -1 1))
  (mul-interval- (make-interval -1 1) (make-interval -2 2))
  (mul-interval- (make-interval -1 1) (make-interval 4 8)))
 (list
  (mul-interval (make-interval -2 1) (make-interval -1 2))
  (mul-interval (make-interval -1 2) (make-interval -2 1))
  (mul-interval (make-interval -2 2) (make-interval -1 1))
  (mul-interval (make-interval -1 1) (make-interval -2 2))
  (mul-interval (make-interval -1 1) (make-interval 4 8)))
 )
#+end_src

#+RESULTS:
: ((#f #t #f) ((-4 . 2) (-4 . 2) (-2 . 2) (-2 . 2) (-8 . 8)) ((-4 . 2) (-4 . 2) (-2 . 2) (-2 . 2) (-8 . 8)))

* 2.12

#+NAME: interval-calc-cw
#+begin_src racket :noweb yes :results none
;<<interval-calc>>
(define (make-center-width c w)
  (make-interval (- c w) (+ c w)))

(define (center i)
  (/ (+ (lower-bound i) (upper-bound i)) 2))

(define (width i)
  (/ (- (upper-bound i) (lower-bound i)) 2))

(define (make-center-percent c p)
  (let ([w (* c p)])
    (make-interval (- c w) (+ c w))))
(define (percent x)
  (/ (width x) (center x)))
#+end_src

* 2.13

According to my analyses in Exercise 2.9 and Exercise 2.11, for x > 0 and y > 0,
$c = \frac {a + b} 2, w = \frac {b - a} 2$, the error $p = w / c = \frac {b-a} {b+a}$.

$w_{xy} = \frac {b_1 b_2 - a_1 a_2} 2$, $c_{xy} = \frac {b_1 b_2 + a_1 a_2} 2$. $p_{xy} = \frac {b_1 b_2 - a_1 a_2} {b_1 b_2 + a_1 a_2}$.

Observe that
$p_{xy} = \frac {w_{xy}} {w_x w_y + c_x c_y} = \frac {w_x c_y + w_y c_x} {w_x w_y + c_x c_y} = \frac {p_x + p_y} {p_x p_y + 1}$.

(Does it look not so "simple" as the textbook told?)

* 2.14

#+begin_src racket :noweb yes
;<<interval-calc-cw>>
;<<div-interval>>
(define (part1 r1 r2)
  (div-interval (mul-interval r1 r2)
                (add-interval r1 r2)))
(define (part2 r1 r2)
  (let ([one (make-interval 1 1)])
    (div-interval one
                  (add-interval (div-interval one r1)
                                (div-interval one r2)))))

(let ([r1 (make-center-percent 100 0.01)]
      [r2 (make-center-percent 1000 0.001)]
      [r3 (make-interval 1 3)]
      [r4 (make-interval 2 4)]
      [r5 (make-interval 9 11)]
      )
  (display (list
            (div-interval r3 (make-interval 1 1))
            (div-interval r3 r3)
            (div-interval r3 r5)
            (div-interval r4 r4)
            (div-interval r4 r5)))
  (newline)

  (list
   (part1 r1 r1)
   (part2 r1 r1)

   (part1 r1 r2)
   (part2 r1 r2)

   (part1 r3 r3)
   (part2 r3 r3)))
#+end_src

#+RESULTS:
: ((1.0 . 3.0) (0.3333333333333333 . 3.0) (0.09090909090909091 . 0.3333333333333333) (0.5 . 2.0) (0.18181818181818182 . 0.4444444444444444))
: ((48.51980198019802 . 51.52020202020203) (49.49999999999999 . 50.5) (89.74682395644282 . 92.07741347905282) (90.07377049180327 . 91.7431941923775) (0.16666666666666666 . 4.5) (0.5 . 1.5))

* 2.15

For $x > 0, y > 0$, $w_{x\pm y} = w_x + w_y$, $p_{xy^{\pm 1}} = \frac {p_x + p_y} {p_xp_y + 1} < 1$.

Let me see when $p_{xy^{\pm 1}} > p_x$.

$\frac {p_x + p_y} {p_xp_y + 1} > p_x = \frac {p_x^2p_y + p_x} {p_xp_y + 1}$, this needs $1 > p_x^2$ $(p_x < 1)$. And this is always true!

The add and the mul makes error larger.

The less calculation is better, so <src_racket[:exports code]{part2} is better.

* 2.16

Well, the formula itself doesn't change when deformation. So the issue happens on implementation.

<src_racket[:exports code]{(part1 (make-interval 1 3) (make-interval 1 3)) => (div-interval (1 . 9) (2 . 6)) => (1/6 . 4.5)}.

<src_racket[:exports code]{(part2 (make-interval 1 3) (make-interval 1 3)) => (div-interval (1 . 1) (add-interval (1/3 . 1) (1/3 . 1))) => (1/2 . 3/2)}.

It is proved that add-interval and mul-interval generates error differently, so the order of the evaluation matters.

For a certain evaluable expression which can be computed in a limited time, we can find a most precise strategy to calculate. This garantees that the same formula of different form has the same calculation sequence when computing, so as the precision after computing.

* 2.17

#+begin_src racket
(define (last-pair xs)
  (cond [(null? xs) error]
        [(null? (cdr xs)) xs]
        [else (last-pair (cdr xs))]))

(list (last-pair '(1 2 3 4)) (last-pair '()))
#+end_src

#+RESULTS:
: ((4) #<procedure:error>)

* 2.18

#+NAME: rev
#+begin_src racket
(define (reverse lst)
  (define (iter xs acc)
    (if (null? xs)
        acc
        (iter (cdr xs) (cons (car xs) acc))))
  (iter lst nil))

(reverse '(1 2 3 4))
#+end_src

#+RESULTS:
: (4 3 2 1)

* 2.19

The sequence of the argument `coin-values` do not make difference to the result of function `cc`. Because the `cc` will enumerates all situations of arrangement of the coins.

#+begin_src racket :noweb yes
;<<rev>>
(define (cc amount coin-values)
  (define no-more? null?)
  (define first-denomination car)
  (define except-first-denomination cdr)
  (cond [(= amount 0) 1]
        [(or (< amount 0) (no-more? coin-values)) 0]
        [else (+ (cc amount
                     (except-first-denomination coin-values))
                 (cc (- amount (first-denomination coin-values))
                     coin-values))]))

(define us-coins (list 50 25 10 5 1))
(define uk-coins (list 100 50 20 10 5 2 1 0.5))

(define (count-change amount)
  (cc amount us-coins))

(list (count-change 100) (cc 100 (reverse us-coins)))
#+end_src

#+RESULTS:
: (292 292)

* 2.20

#+begin_src racket :noweb yes
;<<rev>>
(define (same-parity . args)
  (define (same? a b) (equal? (odd? a) (odd? b)))
  (define (iter xs acc)
    (if (null? xs)
        acc
        (if (same? (car xs) (car acc))
            (iter (cdr xs) (cons (car xs) acc))
            (iter (cdr xs) acc))))
  (if (null? args)
      error
      (reverse (iter (cdr args) (list (car args))))))

(list (same-parity 1 2 3 4) (same-parity 2 3 4) (same-parity 1) (same-parity))
#+end_src

#+RESULTS:
: ((1 3) (2 4) (1) #<procedure:error>)

* 2.21

#+begin_src racket
(define (square x) (* x x))
(define (square-list items)
  (if (null? items)
      nil
      (cons (square (car items)) (square-list (cdr items)))))

(define (square-list- items)
  (map square items))

(let ([items (list 1 2 3)])
  (list (square-list items) (square-list- items)))
#+end_src

#+RESULTS:
: ((1 4 9) (1 4 9))

* 2.22

#+begin_src racket
(define (square x) (* x x))
(define (square-list items)
  (define (iter things answer)
    (if (null? things)
        answer
        (iter (cdr things) (cons answer
                                 (square (car things))))))
  (iter items nil))

(square-list (list 1 2 3))
#+end_src

#+RESULTS:
: (((() . 1) . 4) . 9)

Well, this makes correct order, in a wrong expression of answer.

See my implementation in 2.20, which use the `reverse` function after the iteration.

* 2.23

#+begin_src racket
(define (for-each f xs)
  (map f xs)
  true)

(for-each display (list 1 2 3))
#+end_src

#+RESULTS:
: 123#t

* 2.24

<src_racket[:exports code]{(list 1 (list 2 (list 3 4))) => (1 (2 (3 4)))}. Root: 1, child: 2; root: 2, child 3, 4.

#+begin_src racket
(list 1 (list 2 (list 3 4)))
#+end_src

#+RESULTS:
: (1 (2 (3 4)))

* 2.25

#+begin_src racket
(define (repeat n f1)
  (define (id x) x)
  (define (iter i f1 acc)
    (if (<= i 0)
        acc
        (iter (dec i) f1 (lambda (x) (f1 (acc x))))))
  (iter n f1 id))

(let ([t1 '(1 3 (5 7) 9)]
      [t2 '((7))]
      [t3 '(1 (2 (3 (4 (5 (6 7))))))])
  (list
   [car (cdr (car (cdr (cdr t1))))]
   [car (car t2)]
   [(repeat 6 (lambda (x) (car (cdr x)))) t3]
))
#+end_src

#+RESULTS:
: (7 7 7)

* 2.26

#+begin_src racket
(define x (list 1 2 3))
(define y (list 4 5 6))

(list
 (append x y) ; => (1 2 3 4 5 6)
 (cons x y) ; => ((1 2 3) 4 5 6)
 (list x y) ; => ((1 2 3) (4 5 6))
)
#+end_src

#+RESULTS:
: ((1 2 3 4 5 6) ((1 2 3) 4 5 6) ((1 2 3) (4 5 6)))

* 2.27

#+begin_src racket
(define (deep-reverse t)
  (cond [(not (list? t)) t]
        [(null? t) nil]
        [else (append (deep-reverse (cdr t)) (list (deep-reverse (car t))))]))

(define (deep-reverse- t)
  (define (iter sub acc)
    (cond [(not (list? sub)) sub]
          [(null? sub) acc]
          [else (iter (cdr sub) (cons (deep-reverse- (car sub)) acc))]))
  (iter t nil))

(list (deep-reverse '((1 2) (3 4))) (deep-reverse '(1 2 (3 4))) (deep-reverse (list 1 2 3)) (deep-reverse- '(1 2 (3 4))))
#+end_src

#+RESULTS:
: (((4 3) (2 1)) ((4 3) 2 1) (3 2 1) ((4 3) 2 1))

* 2.28

#+begin_src racket
(define (fringle tree)
  (define (iter subtree acc)
    (cond [(not (list? subtree)) (list subtree)]
          [(null? subtree) acc]
          [else (iter (cdr subtree) (append (iter (car subtree) nil) acc))]))
  (iter tree nil))

(define x (list (list 1 2) (list 3 4)))

(list (fringle x) (fringle (list x x)) (fringle (list nil nil)))
#+end_src

#+RESULTS:
: ((4 3 2 1) (4 3 2 1 4 3 2 1) ())

* 2.29

#+begin_src racket
(define (make-mobile left right)
  (list left right))
(define (make-branch length structure)
  (list length structure))

; (a)
(define left-branch car)
(define right-branch cadr)
(define branch-length car)
(define branch-structure cadr)

; (b) ; this let me think about mutual recursion
(define mobile? list?)
(define (total-weight mobile)
  (+ (total-branch-weight (left-branch mobile))
     (total-branch-weight (right-branch mobile))))
(define (total-branch-weight b)
  (let ([s (branch-structure b)])
    (if (mobile? s)
        (total-weight s)
        s)))

; (c)
(define (branch-balanced? b)
  (let ([s (branch-structure b)])
    (if (mobile? s)
        (mobile-balanced? s)
        #t)))
(define (mobile-balanced? mobile)
  (define torque *)
  (let ([left (left-branch mobile)]
        [right (right-branch mobile)])
    (and
     (branch-balanced? left)
     (branch-balanced? right)
     (= (torque (branch-length left) (total-branch-weight left))
        (torque (branch-length right) (total-branch-weight right)))
    )))

(let* ([m1 (make-mobile (make-branch 2 5) (make-branch 2 5))]
       [m2 (make-mobile (make-branch 4 5) (make-branch 2 m1))]
       [m3 (make-mobile (make-branch 1 2) (make-branch 2 3))])
  (map mobile-balanced? (list m1 m2 m3)))
#+end_src

#+RESULTS:
: (#t #t #f)

#+begin_src racket
(define (make-mobile left right)
  (cons left right))
(define (make-branch length structure)
  (cons length structure))

; change code in (a) to:
(define left-branch car)
(define right-branch cdr)
(define branch-length car)
(define branch-structure cdr)

(let ([x (make-mobile 1 2)])
  (list x (car x) (cdr x)))
#+end_src

#+RESULTS:
: ((1 . 2) 1 2)

* 2.30

#+begin_src racket
(define (square x) (* x x))
(define (square-tree tree)
  (cond [(null? tree) nil]
        [(not (pair? tree)) (square tree)]
        [else (cons (square-tree (car tree))
                    (square-tree (cdr tree)))]))
(define (square-tree- tree)
  (map (lambda (sub)
         (if (pair? sub)
             (square-tree- sub)
             (square sub)))
       tree))

(let ([x '(1 (2 (3 4) 5) (6 7))]) (list (square-tree x) (square-tree- x)))
#+end_src

#+RESULTS:
: ((1 (4 (9 16) 25) (36 49)) (1 (4 (9 16) 25) (36 49)))

* 2.31

#+NAME: tree-map
#+begin_src racket
(define (tree-map f tree)
  (map (lambda (sub)
         (if (pair? sub)
             (tree-map f sub)
             (f sub)))
       tree))

(tree-map (lambda (x) (* x x)) '(1 (2 (3 4) 5) (6 7)))
#+end_src

#+RESULTS:
: (1 (4 (9 16) 25) (36 49))

* 2.32

It just like `count-change` in 2.19.

#+begin_src racket
(define (subsets s)
  (if (null? s)
      (list nil)
      (let ([rest (subsets (cdr s))])
        (append rest (map (lambda (sub) (cons (car s) sub)) rest)))))

(subsets (list 1 2 3))
#+end_src

#+RESULTS:
: (() (3) (2) (2 3) (1) (1 3) (1 2) (1 2 3))

* 2.33

#+NAME: accumulate
#+begin_src racket
(define (accumulate op init seq) ; or called fold_right
    (if (null? seq) init
        (op (car seq) (accumulate op init (cdr seq)))))
#+end_src


#+begin_src racket :noweb yes
;<<accumulate>>
(define (map p sequence)
  (accumulate (lambda (x acc) (cons (p x) acc)) nil sequence))
(define (append seq1 seq2)
  (accumulate cons seq2 seq1))
(define (length sequence)
  (accumulate + 0 sequence))

(let ([x (list 1 2 3 4)])
  (list (map inc x) (append x x) (length x)))
#+end_src

#+RESULTS:
: ((2 3 4 5) (1 2 3 4 1 2 3 4) 10)

* 2.34

#+begin_src racket :noweb yes
;<<accumulate>>
(define (horner-eval x coefficient-sequence)
  (accumulate (lambda (this-coeff higher-terms)
                (+ this-coeff (* x higher-terms)))
              0
              coefficient-sequence))

(horner-eval 2 (list 1 3 0 5 0 1))
#+end_src

#+RESULTS:
: 79

$1 + 3x + 5x^3 + x^5 |_{x=2} = 7 + 40 + 32 = 79$

* 2.35

#+begin_src racket :noweb yes
;<<accumulate>>
(define (count-leaves t)
  (accumulate +
              0
              (map (lambda (sub)
                     (if (pair? sub)
                         (count-leaves sub)
                         1))
                   t)))

(define (flat-tree t)
  (accumulate (lambda (sub acc)
                (if (pair? sub)
                    (append (flat-tree sub) acc)
                    (cons sub acc)))
              nil t))
(define (count-leaves- t)
  (accumulate + 0 (map (lambda (_leaf) 1) (flat-tree t))))

(list
 (count-leaves '(1 2 (3 4) 5 (6 7)))
 (count-leaves- '(1 2 (3 4) 5 (6 7)))
)
#+end_src

#+RESULTS:
: (7 7)

* 2.36

#+begin_src racket :noweb yes
;<<accumulate>>
(define (accumulate-n op init seqs)
  (if (null? (car seqs)) nil
      (cons (accumulate op init (map car seqs))
            (accumulate-n op init (map cdr seqs)))))

(let ([x (list 1 2 3 4)])
  (accumulate-n * 1 (list x x x)))
#+end_src

#+RESULTS:
: (1 8 27 64)


* OTHER
#+begin_src racket
(define (displayln x) (display x) (newline))
(map displayln (list
 (list 1 (list 2 (list 3 4)))
))
#+end_src

#+begin_src racket
(list
 (list? (list 1 2 3))
 (pair? (list 1 2 3))
 (pair? (cons 2 3))
 (list? (cons 2 3))
)
#+end_src

#+RESULTS:
: (#t #t #t #f)


* COMMENT Local Variables
# Local Variables:
# org-babel-noweb-wrap-start: ";<<"
# org-babel-noweb-wrap-end: ">>"
# End:
