#+title: Exercise
#+property: header-args:racket :lang sicp
#+OPTIONS: tex:t
#+STARTUP: latexpreview

* 3.1 Assignment and Local State

** 3.1

#+begin_src racket
(define (make-accumulator sum)
  (lambda (addend)
    (set! sum (+ sum addend))
    sum))

nil
(define A (make-accumulator 5))

(list
 (A 10)
 (A 10))
#+end_src

#+RESULTS:
: (15 25)

** 3.2

#+begin_src racket
(define (list-single-of? el lst)
  (and (eq? (car lst) el) (null? (cdr lst))))

(define (make-monitored f)
  (define called 0)
  (define (dispatch . args)
    (cond [(list-single-of? 'how-many-calls args) called]
          [(list-single-of? 'reset-count args) (begin (set! called 0) 0)]
          [else (begin (set! called (+ called 1))
                       (apply f args))]))
  dispatch)

nil
(define s (make-monitored sqrt))

(list
 (s 100)
 (s 'how-many-calls)
 (s 100)
 (s 'how-many-calls)
 (s 'reset-count))
#+end_src

#+RESULTS:
: (10 1 10 2 0)

** 3.3

#+NAME: account-password
#+begin_src racket
(define (make-account balance password)
  (define (withdraw amount)
    (if (<= amount balance)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch op)
    (cond [(eq? op 'withdraw) withdraw]
          [(eq? op 'deposit) deposit]
          [else (error "Unknown request -- MAKE-ACCOUNT" op)]))
  (lambda (input op)
    (if (eq? input password)
        (dispatch op)
        "Incorrect password")))
#+end_src

#+begin_src racket :noweb yes
;<<account-password>>
nil
(define acc (make-account 100 'secret-password))

(list
 ((acc 'secret-password 'withdraw) 40)
 (acc 'some-other-password 'deposit))
#+end_src

#+RESULTS:
: (60 "Incorrect password")

** 3.4

#+begin_src racket :noweb yes
(define (always res) (lambda _args res))

(define (call-the-cops)
  "Cops arrived")

(define (make-account balance password)
  (define rest-chance 7)
  (define (withdraw amount)
    (if (<= amount balance)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch op)
    (cond [(eq? op 'withdraw) withdraw]
          [(eq? op 'deposit) deposit]
          [else (error "Unknown request -- MAKE-ACCOUNT" op)]))
  (lambda (input op)
    (if (eq? input password)
        (begin (set! rest-chance 7)
               (dispatch op))
        (begin (set! rest-chance (- rest-chance 1))
               (if (zero? rest-chance)
                   (always (call-the-cops))
                   (always "Incorrect password"))))))

nil
(define acc (make-account 100 'secret-password))

;<<higher-order>>
(list
 ((acc 'secret-password 'withdraw) 40)
 ((repeat 7 (lambda () ((acc 'some-other-password 'deposit) 50))))
 )
#+end_src

#+RESULTS:
: (60 ("Incorrect password" "Incorrect password" "Incorrect password" "Incorrect password" "Incorrect password" "Incorrect password" "Cops arrived"))

** 3.5

#+NAME: monte-carlo
#+begin_src racket
(define (monte-carlo trials experiment)
  (define (iter trials-remaining trials-passed)
    (cond [(zero? trials-remaining) (/ trials-passed trials)]
          [(experiment) (iter (- trials-remaining 1) (+ trials-passed 1))]
          [else (iter (- trials-remaining 1) trials-passed)]))
  (iter trials 0))
#+end_src


#+begin_src racket :noweb yes
;<<square>>
;<<monte-carlo>>
(define (random-f int . precisions)
  (define default-precision 1000000)
  (define (random-by-precision precision)
    (* int (/ (random precision) precision)))
  (if (null? precisions)
      (random-by-precision default-precision)
      (map random-by-precision precisions)))

(define (random-in-range low high)
  (let ([range (- high low)])
    (+ low (random-f range))))

(define (estimate-integral p x1 x2 y1 y2 trials)
  (define (random-point x1 x2 y1 y2)
    (cond [(> x1 x2) (random-point x2 x1 y1 y2)]
          [(> y1 y2) (random-point x1 x2 y2 y1)]
          [else (list (random-in-range x1 x2)
                      (random-in-range y1 y2))]))
  (define (experiment)
    (apply p (random-point x1 x2 y1 y2)))
  (monte-carlo trials experiment))

(define (estimate-pi trials)
  (define (p x y)
    (<= (+ (square (- x 5)) (square (- y 7)))
        (square 3)))
  ; (πr^2) / (2r * 2r) = π / 4
  (let ([quarter-of-pi (estimate-integral p 2 8 4 10 trials)])
    (* 4 quarter-of-pi)))

(* 1.0 (estimate-pi 100000))
#+end_src

#+RESULTS:
: 3.13584

** 3.6

#+begin_src racket
(define random-init 65537)
(define rand-update random)

(define (rand op)
  (define seed random-init)
  (cond [(eq? op 'generate)
         (begin (set! seed (rand-update seed))
                seed)]
        [(eq? op 'reset)
         (lambda (new-seed) (begin (set! seed new-seed)
                                   seed))]))

(list
 (rand 'generate)
 (rand 'generate)
 ((rand 'reset) 42)
 )
#+end_src

#+RESULTS:
: (61533 6785 42)

** 3.7

#+begin_src racket :noweb yes
;<<account-password>>
(define (make-joint account password new-password)
  (define (correct-password?)
    (not (string? (account password 'deposit))))
  (if (correct-password?)
      (lambda (input op)
        (if (eq? input new-password)
            (account password op)
            "Incorrect password"))
      "Invalid account"))

nil
(define peter-acc (make-account 100 'open-sesame))
(define paul-acc (make-joint peter-acc 'open-sesame 'rosebud))
(define a-third-acc (make-joint paul-acc 'rosebud 'a-third)) ; a-third-acc -> paul-acc -> peter-acc
(define invalid-acc (make-joint peter-acc 'other 'newpasswd))

(list
 ((peter-acc 'open-sesame 'withdraw) 10)
 ((paul-acc 'rosebud 'withdraw) 0)
 ((a-third-acc 'a-third 'withdraw) 0)
 (paul-acc 'aaa 'withdraw)
 invalid-acc
)
#+end_src

#+RESULTS:
: (90 90 90 "Incorrect password" "Invalid account")

** 3.8

Well, the test code in the above exercises are all making use of the sequence of evaluation.

My below answer implements the different evaluation order of arguments. This make use of the speciality of `define`. Actually, my test code which uses `repeat` function also utilize this trick, though it's `lambda` other than `define`.

#+begin_src racket :noweb yes
(define (plus-left-right proc1 proc2)
  (+ (proc1) (proc2)))

(define (plus-right-left proc1 proc2)
  (+ (proc2) (proc1)))

(define (get-and-set x)
  (lambda (y)
    (let ([before x])
      (begin (set! x y)
             before))))

nil

;<<displayln>>
(define f1 (get-and-set 0))
(displayln (plus-left-right (lambda () (f1 0)) (lambda () (f1 1))))

(define f2 (get-and-set 0))
(displayln (plus-right-left (lambda () (f2 0)) (lambda () (f2 1))))
#+end_src

#+RESULTS:
: 0
: 1
: #<void>

*** macro?

I asked LLM if I can use some machenism to remove the `lambda`s, because I heard there are something about macro and `define-syntax`. Here is it's answer:

#+begin_src racket :noweb yes
;<<displayln>>
(define (get-and-set x)
  (lambda (y)
    (let ([before x])
      (begin (set! x y)
             before))))

(let-syntax ([plus-left-right
              (syntax-rules ()
                [(_ a b)
                 (let ([x a])
                   (let ([y b])
                     (+ x y)))])]
            [plus-right-left
              (syntax-rules ()
                [(_ a b)
                 (let ([y b])
                   (let ([x a])
                     (+ x y)))])])
  (define f1 (get-and-set 0))
  (displayln (plus-left-right (f1 0) (f1 1)))

  (define f2 (get-and-set 0))
  (displayln (plus-right-left (f2 0) (f2 1))))
#+end_src

#+RESULTS:
: 0
: 1
: #<void>

* 3.2 The Environment Model of Evaluation

** 3.9

I will use this form "table <- E1: (global)" to refer a frame table and it's contents, and the pointer points to a frame. In this example, `E1` points to this frame which related to the global frame.

#+begin_src racket :results none
(define (factorial n)
  (if (= n 1)
      1
      (* n (factorial (- n 1)))))

(factorial 6)
#+end_src

table1 <- global: factorial((n), (if (= n 1) 1 (* n (factorial (- n 1)))))

factorial6 <- E1: (global), n(6), (if (= n 1) 1 (* n (factorial (- n 1)))

factorial5 <- E2: (global), n(5), (if (= n 1) 1 (* n (factorial (- n 1)))

...

factorial1 <- E6: (global), n(1), (if (= n 1) 1 (* n (factorial (- n 1)))

#+begin_src racket
(define (factorial n)
  (fact-iter 1 1 n))
(define (fact-iter product counter max-count)
  (if (> counter max-count)
      product
      (fact-iter (* counter product)
                 (+ counter 1)
                 max-count)))
(factorial 6)
#+end_src

table1 <- global: factorial((n), (fact-iter 1 1 n)), fact-iter((product counter max-count), ...)

factorial <- E1: (global), n(6), (fact-iter 1 1 n)

fact-iter1 <- E2: (global), product(1), counter(1), max-count(6), (...)

fact-iter2 <- E3: (global), product(1), counter(2), max-count(6), (...)

fact-iter3 <- E4: (global), product(2), counter(3), max-count(6), (...)

fact-iter3 <- E4: (global), product(6), counter(3), max-count(6), (...)

...

fact-iter7 <- E2: (global), product(1), counter(7), max-count(6), (...)

** 3.10

#+begin_src racket
(define (make-withdraw initial-amount)
  (let ((balance initial-amount))
    (lambda (amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))))
#+end_src

After src_racket[:exports code]{(define W1 (make-withdraw 100))}:

#+begin_src
table <- global: make-withdraw((initial-amount), ...), W1(#<procedure:E1:((amount), ...)>)

by-make-withdraw <- E1: (global), initial-amount(100), balance(100)
#+end_src

After src_racket[:exports code]{(W1 50)}:

#+begin_src
table <- global: make-withdraw((initial-amount), ...), W1(#<procedure:E1:((amount), ...)>)

by-make-withdraw <- E1: (global), initial-amount(100), balance(50)
#+end_src

After src_racket[:exports code]{(define W2 (make-withdraw 100))}:

#+begin_src
table <- global: make-withdraw((initial-amount), ...), W1(#<procedure:E1:((amount), ...)>), W2(#<procedure:E2:((amount), ...)>)

by-make-withdraw <- E1: (global), initial-amount(100), balance(50)

by-another-make-withdraw <- E2: (global), initial-amount(100), balance(100)
#+end_src

Compare this example in book section 3.2.3, in this environment a new table item `initial-amount` is created.

** 3.11

#+begin_src racket :results none
(define (make-account balance)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch m)
    (cond [(eq? m 'withdraw) withdraw]
          [(eq? m 'deposit) deposit]
          [else (error "Unknown request -- MAKE-ACCOUNT" m)]))
  dispatch)
#+end_src

For src_racket[:exports code]{(define acc (make-account 50))}:

#+begin_src
table <- global: make-account((balance), ...), acc(#<procedure(dispatch):E1:((m), ...)>)

by-make-accunt <- E1: (global), balance(50), withdraw((amount), ...), deposit((amount), ...), dispatch((m), ...)
#+end_src

src_racket[:exports code]{((acc 'deposit) 40)}:

#+begin_src
table <- global: make-account((balance), ...), acc(#<procedure(dispatch):E1:((m), ...)>)

by-make-accunt <- E1: (global), balance(90), withdraw(...), deposit(...), dispatch(...)

by-dispatch <- E2: (E1), m('deposit)

by-deposit <- E3: (E1), amount(40)
#+end_src

src_racket[:exports code]{((acc 'withdraw) 60)}:

#+begin_src
table <- global: make-account((balance), ...), acc(#<procedure(dispatch):E1:((m), ...)>)

by-make-accunt <- E1: (global), balance(30), withdraw(...), deposit(...), dispatch(...)

by-dispatch <- E2: (E1), m('withdraw)

by-withdraw <- E3: (E1), amount(60)
#+end_src

src_racket[:exports code]{(define acc2 (make-account 100))}:

#+begin_src
table <- global: make-account((balance), ...), acc(#<procedure(dispatch):E1:((m), ...)>, acc2(#<procedure(dispatch):E2:((m), ...)>)

by-make-accunt <- E1: (global), balance(30), withdraw(...), deposit(...), dispatch(...)

by-make-accunt2 <- E2: (global), balance(100), withdraw(...), deposit(...), dispatch(...)
#+end_src

The `acc` and `acc2` share the statement `dispatch` in `make-account`.

* 3.3 Modeling with Mutable Data

** 3.12

#+NAME: append-bang
#+begin_src racket :results none
(define (append! x y)
  (set-cdr! (last-pair x) y)
  x)

(define (last-pair x)
  (if (null? (cdr x))
      x
      (last-pair (cdr x))))
nil
#+end_src


#+begin_src racket :noweb yes
;<<append-bang>>
;<<displayln>>
(define x (list 'a 'b))
(define y (list 'c 'd))
(define z (append x y))

(displayln (cdr x)) ; => (b)

(define w (append! x y))
(displayln (cdr x)) ; => (b c d)
(displayln z)
#+end_src

#+RESULTS:
: (b)
: (b c d)
: (a b c d)
: #<void>

Before calling `append!`:

#+begin_src
x -> [a] -> [b] -> nil
y -> [c] -> [d] -> nil
z -> [a] -> [b] -> [c] -> [d] -> nil
#+end_src

After calling `append!`:

#+begin_src
x -> [a] -> [b] -> (y)   ; x -> [a] -> [b] -> [c] -> [d] -> nil
y -> [c] -> [d] -> nil
z -> [a] -> [b] -> [c] -> [d] -> nil
#+end_src

** 3.13

#+NAME: make-cycle
#+begin_src racket :noweb yes :results none
;<<append-bang>>
(define (make-cycle! x)
  (set-cdr! (last-pair x) x)
  x)
#+end_src

src_racket[:exports code]{(define z (make-cycle! (list 'a 'b 'c)))}:

#+begin_src
z -> [a] -> [b] -> [c] -> (z)
; z -> [a] -> [b] -> [c] -> [a] -> [b] -> [c] -> [a] -> [b] -> [c] -> ...
#+end_src

Evaluating src_racket[:exports code]{(last-pair z)} goes to endless recusion.

** 3.14

#+begin_src racket
(define (mystery x)
  (define (loop x y)
    (if (null? x)
        y
        (let ([temp (cdr x)])
          (set-cdr! x y)
          (loop temp x))))
  (loop x '()))

nil
(define reversed! mystery)

(define v (list 'a 'b 'c 'd))
(define w (reversed! v))
(display v) ; => (a)
(display w)
#+end_src

#+RESULTS:
: (a)(d c b a)#<void>

#+begin_src
v -> [a] -> [b] -> [c] -> [d] -> nil
---
v -> [a] -> nil
(loop {[b] -> [c] -> [d] -> nil} v) => (loop {[c] -> [d] -> nil} {[b] -> [a] -> nil}) => ... => w
w -> [d] -> [c] -> [b] -> [a] -> nil
#+end_src

** 3.15

#+begin_src racket
(define (set-to-wow! x)
  (set-car! (car x) 'wow)
  x)

nil
(define x (list 'a 'b))
(define z1 (cons x x))
(define z2 (cons (list 'a 'b) (list 'a 'b)))

(list
 (set-to-wow! z1)
 (set-to-wow! z2))
#+end_src

#+RESULTS:
: (((wow b) wow b) ((wow b) a b))

#+begin_src
x -> [a] -> [b] -> nil
z1 -> ((x)) -> (x) ; z1 -> ([a] -> [b] -> nil) -> [a] -> [b] -> nil
z2 -> ([a] -> [b] -> nil) -> [a] -> [b] -> nil
---
x -> [wow] -> [b] -> nil
z1 -> ((x)) -> (x) ; z1 -> ([wow] -> [b] -> nil) -> [wow] -> [b] -> nil
z2 -> ([wow] -> [b] -> nil) -> [a] -> [b] -> nil
#+end_src

** 3.16

#+begin_src racket
(define (count-pairs x)
  (if (not (pair? x))
      0
      (+ (count-pairs (car x))
         (count-pairs (cdr x))
         1)))
(define p (cons 'a 'b))
(define l (list 'a 'b))

(list
 (count-pairs (list 1 1 1)) ; => 3
 (count-pairs (list 1 1 p)) ; => 4
 (count-pairs (list p p l)) ; => 7
 ; (count-pairs (make-cycle! (list 1 2)))
 )
#+end_src

#+RESULTS:
: (3 4 7)

Well, I don't understand this exercise.

** 3.17

I think the expression of the exercise is obscure. I guess it means this:

#+begin_src racket :noweb yes
;<<make-cycle>>
(define (count-pairs x)
  (define counted nil)
  (define (iter x)
    (if (or (not (pair? x)) (memq x counted))
        0
        (begin (set! counted (cons x counted))
               (+ 1 (iter (car x)) (iter (cdr x))))))
  (iter x))
(define p (cons 'a 'b))
(define l (list 'a 'b))

(list
 (count-pairs (list 1 1 1)) ; => 3
 (count-pairs (list 1 1 p)) ; => 4
 (count-pairs (list p p l)) ; => 6
 (count-pairs (make-cycle! (list 1 2)))
 )
#+end_src

#+RESULTS:
: (3 4 6 2)

** 3.18, 3.19

#+begin_src racket :noweb yes
;<<make-cycle>>
(define (cycle-list? lst)
  (define (iter xs)
    (cond [(or (not (pair? xs)) (list? xs)) #f]
          [(eq? lst xs) #t]
          [else (iter (cdr xs))]))
  (iter (cdr lst)))

(define x (make-cycle! (list 1 2)))
(list
 (list (list? x) (pair? x))            ; NOTE cycled list is not list.
 (cycle-list? (list 1 2))
 (cycle-list? (list 1 2 (list 1 2)))
 (cycle-list? x)
 )
#+end_src

#+RESULTS:
: ((#f #t) #f #f #t)

** 3.20

#+begin_src racket
(define (cons x y)
  (define (set-x! x v) (set! x v))
  (define (set-y! y v) (set! y v))
  (define (dispatch m)
    (cond [(eq? m 'car) x]
          [(eq? m 'cdr) y]
          [(eq? m 'set-car) set-x!]
          [(eq? m 'set-cdr) set-y!]
          [else (error "Undefined operation -- CONS" m)]))
  dispatch)

(define (car z) (z 'car))
(define (cdr z) (z 'cdr))
(define (set-car! z v) ((z 'set-car) v) z)
(define (set-cdr! z v) ((z 'set-cdr) v) z)
#+end_src

For src_racket[:exports code]{(define x (cons 1 2)) (define z (cons x x))}:

#+begin_src
table <- global: car(...), cdr(...), set-car!(...), set-cdr!(...), x(#<procedure(dispatch):E1:((m), ...)>), z(#<procedure(dispatch):E2:((m), ...)>)

cons-x <- E1: (global), x(1), y(2), set-x!((x v), ...), set-y!((y v), ...), dispatch((m, ...))

cons-z <- E2: (global), x(x (in global)), y(x (in global)), set-x!(...), set-y!(...), dispatch(...)
#+end_src

src_racket[:exports code]{(set-car! (cdr z) 17)}:

#+begin_src
table <- global: car(...), cdr(...), set-car!(...), set-cdr!(...), x(#<procedure(dispatch):E1:((m), ...)>), z(#<procedure(dispatch):E2:((m), ...)>)

cons-x <- E1: (global), x(1), y(2), set-x!((x v), ...), set-y!((y v), ...), dispatch((m, ...))

cons-z <- E2: (global), x(17), y(x), set-x!(...), set-y!(...), dispatch(...)

set-car-z-17 <- E3: (global), z((cdr z) => x), v(17)

cdr-z-17 <- E4: (global), z(z => #<procedure(dispatch):E2:...>)

dispatch-z-cdr <- E5: (E2), m('cdr)

dispatch-z-set-car-17 <- E6: (E2), m('set-cdr)

z-set-car-17-set-x <- E7: (E2), x(x => #procedure(dispatch):E1:...>), v(17)
#+end_src

src_racket[:exports code]{(car x)}:

#+begin_src
table <- global: car(...), cdr(...), set-car!(...), set-cdr!(...), x(#<procedure(dispatch):E1:((m), ...)>), z(#<procedure(dispatch):E2:((m), ...)>)

cons-x <- E1: (global), x(1), y(2), set-x!((x v), ...), set-y!((y v), ...), dispatch((m, ...))

cons-z <- E2: (global), x(17), y(x), set-x!(...), set-y!(...), dispatch(...)

car-x <- E8: (global), z(x)

dispatch-car-x <- E9: (global), m('car)
#+end_src

** 3.21 print queue

#+NAME: queue
#+begin_src racket
;; construction
(define (make-queue) (cons nil nil))
(define front-ptr car)
(define rear-ptr cdr)
(define set-front-ptr! set-car!)
(define set-rear-ptr! set-cdr!)
(define (empty-queue? que) (null? (front-ptr que)))

(define (front-queue que) (car (front-ptr que)))
(define (rear-queue que) (car (rear-ptr que)))

;; modification
(define (insert-queue! que item)
  (let ([new-pair (cons item nil)])
    (cond [(empty-queue? que)
           (set-front-ptr! que new-pair)
           (set-rear-ptr! que new-pair)
           que]
          [else (set-cdr! (rear-ptr que) new-pair)
                (set-rear-ptr! que new-pair)
                que])))

(define (delete-queue! que)
  (cond [(empty-queue? que)
         (error "DELETE! called with an empty queue" que)]
        [else (set-front-ptr! que (cdr (front-ptr que)))
              que]))
#+end_src

#+begin_src racket :noweb yes
;<<queue>>
(define (print-queue que) (display (front-ptr que)))

nil
(define q1 (make-queue))
(print-queue (insert-queue! q1 'a))
(print-queue (insert-queue! q1 'b))
(print-queue (delete-queue! q1))
(print-queue (delete-queue! q1))
#+end_src

#+RESULTS:
: (a)(a b)(b)()#<void>

** 3.22

#+begin_src racket
(define (make-queue)
  (let ([front-ptr nil]
        [rear-ptr nil])
    (define (set-front-ptr! v) (set! front-ptr v))
    (define (set-rear-ptr! v) (set! rear-ptr v))
    (define (empty?) (null? front-ptr))
    (define (view) front-ptr)
    (define (insert! v)
      (let ([new-pair (cons v nil)])
        (cond [(empty?) (set-front-ptr! new-pair)
                        (set-rear-ptr! new-pair)
                        (view)]
              [else (set-cdr! rear-ptr new-pair)
                    (set-rear-ptr! new-pair)
                    (view)])))
    (define (delete!)
      (cond [(empty?) (error "DELETE! called with an empty queue")
                      dispatch]
            [else (set-front-ptr! (cdr front-ptr))
                  (view)]))
    (define (print) (display (view)))

    (define (dispatch m)
      (cond [(eq? m 'front-ptr) front-ptr]
            [(eq? m 'rear-ptr) rear-ptr]
            [(eq? m 'empty?) (empty?)]
            [(eq? m 'insert!) insert!]
            [(eq? m 'delete!) (delete!)]
            [(eq? m 'print) (print)]
            ))
    dispatch))

nil
(define q1 (make-queue))

((q1 'insert!) 'a) (q1 'print)
((q1 'insert!) 'b) (q1 'print)
(q1 'delete!)      (q1 'print)
(q1 'delete!)      (q1 'print)
#+end_src

#+RESULTS:
: (a)(a b)(b)()#<void>

** 3.23 deque

#+NAME: deque
#+begin_src racket :noweb yes :results none
(define (make-node-deque v) (cons v (cons nil nil)))
(define value-node car)
(define last-node cadr)
(define next-node cddr)
(define (set-last-node! node last)
  (set-car! (cdr node) last))
(define (set-next-node! node next)
  (set-cdr! (cdr node) next))

(define (make-deque) (cons 0 (cons nil nil)))
(define length-deque car)
(define front-ptr-deque cadr)
(define rear-ptr-deque cddr)
(define set-length-deque! set-car!)
(define (set-front-ptr-deque! que v) (set-car! (cdr que) v))
(define (set-rear-ptr-deque! que v) (set-cdr! (cdr que) v))
(define (empty-deque? que) (null? (front-ptr-deque que)))
(define (one-deque? que) (and (not (empty-deque? que))
                              (eq? (front-ptr-deque que) (rear-ptr-deque que))))

(define (front-deque que)
  (cond [(empty-deque? que)
         (error "Operation on an empty deque -- FRONT-DEQUE" que)]
        [else (value-node (front-ptr-deque que))]))
(define (rear-deque que)
  (cond [(empty-deque? que)
         (error "Operation on an empty deque -- REAR-DEQUE" que)]
        [else (value-node (rear-ptr-deque que))]))
(define (inc-length-deque! que)
  (set-length-deque! que (+ (length-deque que) 1)))
(define (dec-length-deque! que)
  (set-length-deque! que (- (length-deque que) 1)))
(define (front-insert-deque! que v)
  (inc-length-deque! que)
  (let ([new-node (make-node-deque v)])
    (cond [(empty-deque? que) (set-front-ptr-deque! que new-node)
                              (set-rear-ptr-deque! que new-node)
                              que]
          [else (let ([front (front-ptr-deque que)])
                  (set-last-node! front new-node)
                  (set-next-node! new-node front)
                  (set-front-ptr-deque! que new-node))])))
(define (rear-insert-deque! que v)
  (inc-length-deque! que)
  (let ([new-node (make-node-deque v)])
    (cond [(empty-deque? que) (set-front-ptr-deque! que new-node)
                              (set-rear-ptr-deque! que new-node)
                              que]
          [else (let ([rear (rear-ptr-deque que)])
                  (set-next-node! rear new-node)
                  (set-last-node! new-node rear)
                  (set-rear-ptr-deque! que new-node))])))
(define (front-delete-deque! que)
  (dec-length-deque! que)
  (cond [(empty-deque? que)
         (error "FRONT-DELETE! an empty deque" que)]
        [(one-deque? que) (set-front-ptr-deque! que nil)
                          (set-rear-ptr-deque! que nil)]
        [else (set-front-ptr-deque! que (next-node (front-ptr-deque que)))
              (set-last-node! (front-ptr-deque que) nil)]))
(define (rear-delete-deque! que)
  (dec-length-deque! que)
  (cond [(empty-deque? que)
         (error "REAR-DELETE! an empty deque" que)]
        [(one-deque? que) (set-rear-ptr-deque! que nil)
                          (set-front-ptr-deque! que nil)]
        [else (set-rear-ptr-deque! que (last-node (rear-ptr-deque que)))
              (set-next-node! (rear-ptr-deque que) nil)]))

(define (print-deque que)
  (define (iter node)
    (if (null? node)
        (display nil)
        (begin (display (value-node node))
               (display " ")
               (iter (next-node node)))))
  (display "(")
  (iter (front-ptr-deque que))
  (display ")"))
#+end_src

#+begin_src racket :noweb yes
;<<deque>>
;<<higher-order>>
nil
(define q1 (make-deque))
(print-deque q1)
(front-insert-deque! q1 1)
(front-insert-deque! q1 2)
(front-insert-deque! q1 3)
(print-deque q1)
(rear-delete-deque! q1)
(rear-delete-deque! q1)
(rear-delete-deque! q1)
(print-deque q1)
((repeat 3 rear-insert-deque!) q1 1)
(print-deque q1)
((repeat 3 front-delete-deque!) q1)
(print-deque q1)
#+end_src

#+RESULTS:
: (())(3 2 1 ())(())(1 1 1 ())(())#<void>

** 3.24

#+begin_src racket
(define (make-table same-key?)
  (let ([local-table (list '*table*)])
    (define (assoc k table)
      (cond [(null? table) #f]
            [(same-key? (caar table) k) (car table)]
            [else (assoc k (cdr table))]))
    ; -- snip --
    ))
#+end_src

** 3.25, 3.26

It's kind of difficult to combine these two. Better to image the data structure clearly.

A record is like src_racket[:exports code]{(cons k v)}, and association list is like src_racket[:exports code]{(list (cons k1 v1) (cons k2 v2) ...)}. Replace data structure to tree, it's like src_racket[:exports code]{(tree (cons k1 v2) (cons k2 v2) ...)}.

How about more dimentions? They may be like src_racket[:exports code]{(tree (cons k1 tree1) (cons k2 tree2) ...) => (tree (cons k1 (tree (cons k11 v11) (cons k12 v12) ...)) (tree (cons k21 v21) (cons k22 v22)))}. Notice that I replaced the `v` to a tree, this implies a structure src_racket[:exports code]{(key tree)}.

How a powerful observation! This means the type of a table is "type of key + type of another tree". If a `v` is of type of tree and it's a node, the type system will be simpler. It's like:

#+begin_src
(cons k t)
=> (cons k (cons k1 t1) (cons k2 t2) ...)
=> (cons k (cons k1 (cons k11 t11) (cons k12 t12) ...) (cons k2 (cons k21 t21) (cons k22 t22) ...) ...)
=> (cons k (cons k1 (cons k11 (... node1)) (cons k12 (... node2)) ...) (cons k2 (cons k21 (... node3)) ...)
#+end_src

The types are:

#+begin_src
type record = {key, tree}
type table = record
type tree = tree(records) | node(value)
;; while key and value can be any type.
#+end_src

#+NAME: table
#+begin_src racket :results none
(define (attach-tag tag contents)
  (cons tag contents))

(define ord (list 'LT 'EQ 'GT))
(define (number-cmp a b)
  (cond [(= a b) 'EQ]
        [(< a b) 'LT]
        [else 'GT]))

(define (binary-tree cmp)
  (define (make) (cons nil (cons nil nil)))
  (define (make-node v) (cons v (cons nil nil)))
  (define (empty? t) (null? (value t)))
  (define (node? t) (and (null? (left t)) (null? (right t))))
  (define value car)
  (define left cadr)
  (define right cddr)
  (define (set-value! t v) (set-car! t v))
  (define (set-left! t sub) (set-car! (cdr t) sub))
  (define (set-right! t sub) (set-cdr! (cdr t) sub))
  (define (insert! t v)
    (cond [(empty? t) (set-value! t v)
                      t]
          [(eq? (cmp (value t) v) 'LT)
           (if (null? (left t))
               (begin (set-left! t (make-node v))
                      t)
               (insert! (left t) v))]
          [else
           (if (null? (right t))
               (begin (set-right! t (make-node v))
                      t)
               (insert! (right t) v))]))
  (define (search t target)
    (if (or (null? t) (empty? t)) #f
        (let ([cmp-res (cmp (value t) target)])
          (cond [(eq? cmp-res 'EQ) (value t)]
                [(eq? cmp-res 'LT) (search (left t) target)]
                [(eq? cmp-res 'GT) (search (right t) target)]))))

  (define (view-tagged t)
    (cond [(tagged-tree? t)
           (let ([untagged (remove-tag t)])
             (list (view-tagged (value untagged)) (view-tagged (left untagged)) (view-tagged (right untagged))))]
          [else t]))

  (define (tag x) (list (attach-tag 'B x)))
  (define (tagged-tree? x) (and (list? x) (not (null? x)) (pair? (car x)) (eq? (caar x) 'B)))
  (define (remove-tag x)
    (if (tagged-tree? x)
        (cdar x)
        (error "Not tree -- REMOVE-TAG" x)))
  (define (dispatch m)
    (cond
      [(eq? m 'left) (lambda (t) (left (remove-tag t)))]
      [(eq? m 'right) (lambda (t) (right (remove-tag t)))]
      [(eq? m 'tree?) tagged-tree?]
      [(eq? m 'make) (lambda () (tag (make)))]
      [(eq? m 'make-node) (lambda (v) (tag (make-node v)))]
      [(eq? m 'empty?) (lambda (t) (empty? (remove-tag t)))]
      [(eq? m 'node?) (lambda (t) (node? (remove-tag t)))]
      [(eq? m 'value) (lambda (t) (value (remove-tag t)))]
      [(eq? m 'view) view-tagged]
      [(eq? m 'insert!) (lambda (t v) (insert! (remove-tag t) v))]
      [(eq? m 'search) (lambda (t v) (search (remove-tag t) v))]
      [else (error "No method -- BINARY-TREE" m)]))
  dispatch)

(define (make-table init-key valid-key? key-cmp)
  (define (key table) (car table))
  (define (tree table) (cdr table))
  (define (drop-key x)
    (if (valid-key? x) x (key x)))
  (define (record-key-cmp a b)
    (key-cmp (drop-key a) (drop-key b)))
  nil
  (define tree-method (binary-tree record-key-cmp))
  (define (make key) (cons key ((tree-method 'make))))
  (define (empty? table) ((tree-method 'empty?) (cdr table)))
  (define set-tree! set-cdr!)
  (define (validated-key k)
    (if (valid-key? k)
        k
        (error "Invalid key:" k)))
  (define (table? t)
    (and (pair? t)
         (valid-key? (key t))
         ((tree-method 'tree?) (tree t))))
  (define (lookup-layer table k)
    ((tree-method 'search) (tree table) k))
  (define (not-nesting-record? tr)
    (and ((tree-method 'node?) tr)
         (not (table? ((tree-method 'value) tr)))))

  (let ([local-table (make init-key)])
    (define (lookup keys)
      (define (iter table rest-keys)
        (if (null? rest-keys) table
            (let ([k (validated-key (car rest-keys))])
              (let ([record (lookup-layer table k)])
                (cond [(not record) #f]
                      [(and (not-nesting-record? (tree record))
                            (not (null? (cdr rest-keys))))
                       (eq? (record-key-cmp record (validated-key (cadr rest-keys))) 'EQ)]
                      [else (iter record (cdr rest-keys))])))))
      (let ([res (iter local-table keys)])
        (if res
            ((tree-method 'value) (tree res))
            #f)))

    (define (insert! keys v)
      (define (iter table rest-keys)
        (if (null? rest-keys) (set-tree! table ((tree-method 'make-node) v))
            (let ([k (validated-key (car rest-keys))])
              (if (and (not (empty? table))
                       (not-nesting-record? (tree table))
                       (not (null? rest-keys)))
                  (begin
                    (display "!") (display table) (display " ") (display k) (display "!")
                    (set-tree! table ((tree-method 'make)))))
              (let ([record (lookup-layer table k)])
                (cond [(not record)
                       (let ([new-record (make k)])
                         ((tree-method 'insert!) (tree table) new-record)
                         (iter new-record (cdr rest-keys)))]
                      [else (iter record (cdr rest-keys))])))))
      (iter local-table keys)
      'done)

    ;; (define (view)
    ;;   (define left (tree-method 'left))
    ;;   (define right (tree-method 'right))
    ;;   (define value (tree-method 'value))
    ;;   (define (view-table table)
    ;;     (if (empty? table) nil
    ;;         (list (key table) (view-tree (tree table)))))
    ;;   (define (view-tree t)
    ;;     (cond
    ;;       [(not-nesting-record? t) ((tree-method 'view) t)]
    ;;       [((tree-method 'node?) t) (view-table (value t))]
    ;;       [else (list (view-table (value t)) ((tree-method 'view) (left t)) ((tree-method 'view) (right t)))]))
    ;;   (view-table local-table))

    (define (view-raw) local-table)
    (define (dispatch m)
      (cond [(eq? m 'view) view-raw]
            [(eq? m 'lookup) lookup]
            [(eq? m 'insert!) insert!]
            [else (error "No method -- MAKE-TABLE" m)]))
    dispatch))
#+end_src

#+begin_src racket :noweb yes
;<<table>>
(define (cmp-string a b)
  (cond [(string=? a b) 'EQ]
        [(string<? a b) 'LT]
        [else 'GT]))

nil
(define table (make-table "*table*" string? cmp-string))

;<<displayln>>
(begin
  (displayln ((table 'view)))
  (displayln ((table 'lookup) nil))
  (displayln ((table 'lookup) (list "1")))
  (displayln ((table 'insert!) (list "i" "j" "k") 1))
  (displayln ((table 'view)))
  (displayln ((table 'lookup) (list "i" "j" "k")))
  (displayln ((table 'insert!) (list "i" "j" "l") 2))
  (displayln ((table 'view)))
  (displayln ((table 'lookup) (list "i" "j" "l")))
  (displayln ((table 'insert!) (list "a") 3))
  (displayln ((table 'view)))
  (displayln ((table 'insert!) (list "a" "b" "c") 2))
  (displayln ((table 'lookup) (list "a" "b" "c")))
  (displayln ((table 'view)))
  (displayln ((table 'insert!) (list "a") 3))
  (displayln ((table 'lookup) (list "a")))
  (displayln ((table 'view)))
  (displayln ((table 'lookup) nil))
  )
#+end_src

#+RESULTS:
#+begin_example
(*table* (B () ()))
()
#f
done
(*table* (B (i (B (j (B (k (B 1 ())) ())) ())) ()))
1
done
(*table* (B (i (B (j (B (k (B 1 ())) ((l (B 2 ())) ()))) ())) ()))
2
done
(*table* (B (i (B (j (B (k (B 1 ())) ((l (B 2 ())) ()))) ())) () (a (B 3 ())) ()))
!(a (B 3 ())) b!done
2
(*table* (B (i (B (j (B (k (B 1 ())) ((l (B 2 ())) ()))) ())) () (a (B (b (B (c (B 2 ())) ())) ())) ()))
done
3
(*table* (B (i (B (j (B (k (B 1 ())) ((l (B 2 ())) ()))) ())) () (a (B 3 ())) ()))
(i (B (j (B (k (B 1 ())) ((l (B 2 ())) ()))) ()))
#<void>
#+end_example

This takes me many hours... I shouldn't do this. :(

** 3.27

#+NAME: table-1d
#+begin_src racket :results none
(define (make-table)
  (list '*table*))

(define (lookup key table)
  (let ([record (assoc key (cdr table))])
    (if record
        (cdr record)
        #f)))

(define (insert! k v table)
  (let ([record (assoc k (cdr table))])
    (if record
        (set-cdr! record v)
        (set-cdr! table
                  (cons (cons k v) (cdr table))))))
#+end_src

#+begin_src racket :noweb yes
;<<table-1d>>
(define (memorize f)
  (let ([table (make-table)])
    (lambda (x)
      (let ([saved (lookup x table)])
        (if saved
            saved
            (let ([result (f x)])
              (insert! x result table)
              result))))))
nil
(define (fib n)
  (cond [(= n 0) 0]
        [(= n 1) 1]
        [else (+ (fib - n 2)
                 (fib (- n 1)))]))

(define memo-fib
  (memorize (lambda (n)
              (cond [(= n 0) 0]
                    [(= n 1) 1]
                    [else (+ (memo-fib (- n 1))
                             (memo-fib (- n 2)))]))))

(memo-fib 100)
#+end_src

#+RESULTS:
: 354224848179261915075

The old `fib` is tree recursively computed, while the memorized fib is iterative. Each call the `memo-fib` will lookup the inner table to examine whether it was computed in the past. If the table is a hash table, it will be of $\Theta$(1) for each lookup, and `memo-fib` will be of $\Theta$(n).

** Book 3.3.4 A Simulator for Digital Circuits

*** 3.28

#+begin_src racket :noweb-ref circuit :results none
(define (logical-or a b)
  (cond [(and (= a 0) (= b 0)) 0]
        [(or (= a 1) (= b 1)) 1]
        [else (error "Invalid signal -- LOGICAL-OR" (list a b))]))

(define (or-gate a b out)
  (define (or-action-procedure)
    (let ([new-value (logical-or (get-signal a) (get-signal b))])
      (after-delay or-gate-delay
                   (lambda ()
                     (set-signal! out new-value)))))
  (add-action! a or-action-procedure)
  (add-action! b or-action-procedure)
  'ok)
#+end_src

*** 3.29

First, I realized that `a or b = not (both_zero a b) = not ((not a) and (not b))`, so I can use not-gate and and-gate to implement or-gate.

Then, it comes again to my favourite contents to image an API of an abstruaction layer. I image a src_racket[:exports code]{(define (make-delay delay-proc) ...)}, and the or-gate in this implementation should wait the not-gate firstly, and and-gate secondly, and not-gate finally.

#+begin_src racket :results none
(define (or-gate a b out)
  (let ([na (make-wire)] [nb (make-wire)] [o1 (make-wire)])
    (not-gate a na)
    (not-gate b nb)
    (and-gate na nb o1)
    (not-gate o1 out)
    'ok))
#+end_src

#+begin_src racket
(define (do-nothing) (lambda () '()))
(define or-gate-delay
  (let ([delay-proc (lambda ()
                      (after-delay not-gate-delay do-nothing)
                      (after-delay and-gate-delay do-nothing)
                      (after-delay not-gate-delay do-nothing))])
        (make-delay delay-proc)))
#+end_src


*** 3.30

#+begin_src racket :noweb yes :results none
;<<circuit-construction>>
;<<not-and-gates>>
;<<adder>>
(define half-adder-delay-time
  (+ (time-delay and-gate-delay)
     (max (time-delay or-gate-delay)
          (+ (time-delay and-gate-delay)
             (time-delay not-gate-delay)))))

(define half-adder-delay
  (let ([delay-proc (lambda ()
                      (after-delay (make-delay-by-time half-adder-delay-time)
                                   do-nothing))])
    (make-delay delay-proc)))

(define full-adder-delay
  (let ([delay-proc (lambda ()
                      (after-delay half-adder-delay do-nothing)
                      (after-delay or-gate-delay do-nothing))])
    (make-delay delay-proc)))

(define (make-ripple-carry-adder-delay n)
  (define (iter-delay i)
    (if (= i 0)
        do-nothing
        (begin (after-delay full-adder-delay do-nothing)
               (iter-delay (- n 1)))))
  (make-delay (lambda () (iter-delay n))))

(define (ripple-carry-adder As Bs Ss c)
  (cond [(and (null? As) (null? Bs) (null? Cs)) 'ok]
        [(or (null? As) (null? Bs) (null? Cs))
         (error "Input length not match -- RIPPLE-CARRY-ADDER" (list As Bs Ss))]
        [else (let ([c1 (make-delay)])
                (full-adder (car As) (car Bs) c (car Ss) c1)
                (ripple-carry-adder (cdr As) (cdr Bs) (cdr Ss) c1))]))
#+end_src

*** 3.31

I successfully guess the API wrong. According to the book content, the delay should be number. So my answer to Exercise 3.29, 3.30 are not fit for the system described in the book. I don't care, and let me do the Exercise 3.31.

The below comments show the output of the procedures.

#+begin_src racket :noweb yes
;<<agenda>>
nil
(define the-agenda (make-agenda))
;<<delay>>
(define not-gate-delay 2)
(define and-gate-delay 3)
(define or-gate-delay 5)
;<<circuit-construction>>
;<<probe>>
;<<not-and-gates>>
;<<or-gate>>
;<<adder>>
nil
(define input-1 (make-wire))
(define input-2 (make-wire))
(define sum (make-wire))
(define carry (make-wire))

(probe 'sum sum)
; sum 0  New-value = 0

(probe 'carry carry)
; carry 0 New-value = 0

(half-adder input-1 input-2 sum carry)
; ok

(set-signal! input-1 1)
; done

(propagate)
; sum 8  New-value = 1
; done

(set-signal! input-2 1)
; done

(propagate)
#+end_src

#+RESULTS:
:
: sum 0  New-value = 0
: carry 0  New-value = 0
: sum 8  New-value = 1
: carry 11  New-value = 1
: sum 16  New-value = 0done

All above outputs are based to that the action added to the gate will be instantly done once.

Otherwise, the circuit system can't be the right state when doing constructing gates. This means after the gate circuit is contructed, the gates in circuit are not powered on, and all the values in each wire are zeros. Not only that, all the `after-delay` procedure won't be executed, so no action will be added to the agenda. The actions in the agenda would be none! And the `propagate` makes no use, wires in the circuit will be 0(initial value) forerver.

*** 3.32

The system must use a queue to manage the actions because it must simulate the change of digital signal which should be evaluated by time order.

Both src_racket[:exports code]{(logical-and 0 1)} and src_racket[:exports code]{(logical-and 0 1)} should be evaluated to `0`.

#+begin_src racket :noweb yes
;<<agenda>>
nil
(define the-agenda (make-agenda))
;<<delay>>
(define not-gate-delay 2)
(define and-gate-delay 3)
(define or-gate-delay 5)
;<<circuit-construction>>
;<<probe>>
;<<not-and-gates>>
;<<or-gate>>
nil
(define input-1 (make-wire))
(define input-2 (make-wire))
(define out (make-wire))

(probe 'out out)
(and-gate input-1 input-2 out)

(set-signal! input-1 0)
(set-signal! input-2 1)
(propagate)

(newline) (display "---")

(set-signal! input-1 1)
(set-signal! input-2 0)
(propagate)
#+end_src

#+RESULTS:
:
: out 0  New-value = 0
: ---
: out 6  New-value = 1
: out 6  New-value = 0done

See the result of the code. Before the wire out is evaluated to correct result, the signal of out jumps to 1 firstly.
This is because the action of `set-signal!` would call all actions to add the assignmeent procedure after delay. If the segment actions are be executed by FIFO order, the reversed order of execution may cause incorrect result.
For example, above code generate a segment src_racket[:exports code]{(3 ((lambda () (set-signal! out 0)) (lambda () (set-signal! out 1))))}. With FILO behavior the result signal will jump to correct 0 and results an incorrect 1.

*** other

#+NAME: circuit-construction
#+begin_src racket :noweb yes :noweb-ref circuit :results none
(define (make-wire)
  (let ([signal-value 0] [action-procedures '()])
    (define (set-my-signal! v)
      (if (not (= signal-value v))
               (begin (set! signal-value v)
                      (call-each action-procedures))
               'done))
    (define (accept-action-procedure! proc)
      (set! action-procedures (cons proc action-procedures))
      (proc))
    (define (dispatch m)
      (cond [(eq? m 'get-signal) signal-value]
            [(eq? m 'set-signal!) set-my-signal!]
            [(eq? m 'add-action!) accept-action-procedure!]
            [else (error "Unknown operation -- WIRE" m)]))
    dispatch))
;<<fold>>
(define (call-each fs)
  (fold-left (lambda (acc f) (f)) nil fs)
  'done)

(define (get-signal wire) (wire 'get-signal))
(define (set-signal! wire v) ((wire 'set-signal!) v))
(define (add-action! wire proc) ((wire 'add-action!) proc))
#+end_src

#+NAME: agenda
#+begin_src racket :noweb yes :noweb-ref circuit
;<<queue>>
(define (make-time-segment time queue)
  (cons time queue))
(define segment-time car)
(define segment-queue cdr)

(define (make-agenda) (cons 0 '()))
(define current-time car)
(define segments cdr)
(define set-current-time! set-car!)
(define set-segments! set-cdr!)

(define (empty-agenda? agenda) (null? (segments agenda)))
(define (first-segment agenda) (car (segments agenda)))
(define (rest-segments agenda) (cdr (segments agenda)))

(define (first-agenda-item agenda)
  (if (empty-agenda? agenda)
      (error "Agenda is empty -- FIRST-AGENDA-ITEM" agenda)
      (let ([first-seg (first-segment agenda)])
        (set-current-time! agenda (segment-time first-seg))
        (front-queue (segment-queue first-seg)))))

(define (remove-first-agenda-item! agenda)
  (let ([q (segment-queue (first-segment agenda))])
    (delete-queue! q)
    (if (empty-queue? q)
        (set-segments! agenda (rest-segments agenda)))))

(define (add-to-agenda! time action agenda)
  (define (belongs-before? segments)
    (or (null? segments)
        (< time (segment-time (car segments)))))
  (define (make-new-time-segment time action)
    (let ([q (make-queue)])
      (insert-queue! q action)
      (make-time-segment time q)))
  (define (add-to-segments! segments)
    (if (= (segment-time (car segments)) time)
        (insert-queue! (segment-queue (car segments))
                       action)
        (let ([rest (cdr segments)])
          (if (belongs-before? rest)
              (set-cdr! segments
                        (cons (make-new-time-segment time action)
                              (cdr segments)))
              (add-to-segments! rest)))))
  (let ([segments (segments agenda)])
    (if (belongs-before? segments)
        (set-segments!
         agenda
         (cons (make-new-time-segment time action) segments))
        (add-to-segments! segments))))
#+end_src

#+NAME: delay
#+begin_src racket :noweb-ref circuit
(define (after-delay delay action)
  (add-to-agenda! (+ delay (current-time the-agenda))
                  action
                  the-agenda))

(define (propagate)
  (if (empty-agenda? the-agenda)
      'done
      (let ([first-item (first-agenda-item the-agenda)])
        (first-item)
        (remove-first-agenda-item! the-agenda)
        (propagate))))
#+end_src

#+NAME: probe
#+begin_src racket :noweb-ref circuit
(define (probe name wire)
  (add-action! wire
               (lambda ()
                 (newline)
                 (display name)
                 (display " ")
                 (display (current-time the-agenda))
                 (display "  New-value = ")
                 (display (get-signal wire)))))
#+end_src

#+NAME: or-gate
#+begin_src racket
(define (or-gate a b out)
  (define (or-action-procedure)
    (let ([v (logical-or (get-signal a) (get-signal b))])
      (after-delay or-gate-delay
                   (lambda ()
                     (set-signal! out v)))))
  (add-action! a or-action-procedure)
  (add-action! b or-action-procedure)
  'ok)

(define (logical-or a b)
  (cond [(and (= a 0) (= b 0)) 0]
        [(or (= a 1) (= b 1)) 1]
        [else "Invalid signal -- LOGICAL-OR" (list a b)]))
#+end_src

#+NAME: not-and-gates
#+begin_src racket :noweb-ref circuit
(define (not-gate in out)
  (define (invert-input)
    (let ([new-value (logical-not (get-signal in))])
      (after-delay not-gate-delay
                   (lambda ()
                     (set-signal! out new-value)))))
  (add-action! in invert-input)
  'ok)

(define (and-gate a b out)
  (define (and-action-procedure)
    (let ([new-value (logical-and (get-signal a) (get-signal b))])
      (after-delay and-gate-delay
                   (lambda ()
                     (set-signal! out new-value)))))
  (add-action! a and-action-procedure)
  (add-action! b and-action-procedure)
  'ok)

(define (logical-not s)
  (cond [(= s 1) 0]
        [(= s 0) 1]
        [else (error "Invalid Signal" s)]))

(define (logical-and a b)
  (cond [(and (= a 1) (= b 1)) 1]
        [(or (= a 0) (= b 0)) 0]
        [else (error "Invalid signal -- LOGICAL-AND" (list a b))]))
#+end_src

#+NAME: adder
#+begin_src racket :noweb-ref circuit :results none
(define (half-adder a b s c)
  (let ([d (make-wire)] [e (make-wire)])
    (or-gate a b d)
    (and-gate a b c)
    (not-gate c e)
    (and-gate d e s)
    'ok))

(define (full-adder a b cin sum cout)
  (let ([s (make-wire)]
        [c1 (make-wire)]
        [c2 (make-wire)])
    (half-adder b cin s c1)
    (half-adder a s sum c2)
    (or-gate c1 c2 cout)
    'ok))
#+end_src

** Book 3.3.5 Propagation of Constraints

*** example

#+begin_src racket :noweb yes :results output
;<<connector>>
;<<constraint>>
(define C (make-connector))
(define F (make-connector))

(define (celsius-fahrenheit-converter c f)
  (let ([u (make-connector)]
        [v (make-connector)]
        [w (make-connector)]
        [x (make-connector)]
        [y (make-connector)])
    (multiplier c w u)
    (multiplier v x u)
    (adder v y f)
    (constant 9 w)
    (constant 5 x)
    (constant 32 y)
    'ok))

(celsius-fahrenheit-converter C F)
(probe "Celsius temp" C)
(probe "Fahrenheit temp" F)

(set-value! C 25 'user)

(forget-value! C 'user)

(set-value! F 212 'user)
#+end_src

#+RESULTS:
#+begin_example
ok
#<procedure:...rg-babel-0BlBXV.rkt:142:2>
#<procedure:...rg-babel-0BlBXV.rkt:142:2>

Probe: Celsius temp = 25
Probe: Fahrenheit temp = 77done

Probe: Celsius temp = ?
Probe: Fahrenheit temp = ?done

Probe: Fahrenheit temp = 212
Probe: Celsius temp = 100done
#+end_example

#+begin_src scheme :results none
(define (has-value? x)
  ?)
(define (get-value x)
  ?)
(define (set-value! x v informant)
  ?)
(define (forget-value! x retractor)
  ?)
(define (connect conn new-constraint)
  ?)
#+end_src

#+NAME: constraint
#+begin_src racket
(define (adder a1 a2 sum)
  (define (process-new-value)
    (cond [(and (has-value? a1) (has-value? a2))
           (set-value! sum
                       (+ (get-value a1) (get-value a2))
                       me)]
          [(and (has-value? a1) (has-value? sum))
           (set-value! a2
                       (- (get-value sum) (get-value a1))
                       me)]
          [(and (has-value? a2) (has-value? sum))
           (set-value! a1
                       (- (get-value sum) (get-value a2))
                       me)]))
  (define (process-forget-value)
    (forget-value! sum me)
    (forget-value! a1 me)
    (forget-value! a2 me)
    (process-new-value))
  (define (me request)
    (cond [(eq? request 'I-have-a-value)
           (process-new-value)]
          [(eq? request 'I-lost-my-value)
           (process-forget-value)]
          [else (error "Unknown request -- ADDER" request)]))
  (connect a1 me)
  (connect a2 me)
  (connect sum me)
  me)

(define (multiplier m1 m2 product)
  (define (has-value-zero? x)
    (and (has-value? x) (= (get-value x) 0)))
  (define (process-new-value)
    (cond [(or (has-value-zero? m1) (has-value-zero? m2))
           (set-value! product 0 me)]
          [(and (has-value? m1) (has-value? m2))
           (set-value! product
                       (* (get-value m1) (get-value m2))
                       me)]
          [(and (has-value? product) (has-value? m1))
           (set-value! m2
                       (/ (get-value product) (get-value m1))
                       me)]
          [(and (has-value? product) (has-value? m2))
           (set-value! m1
                       (/ (get-value product) (get-value m2))
                       me)]))
  (define (process-forget-value)
    (forget-value! m1 me)
    (forget-value! m2 me)
    (forget-value! product me)
    (process-new-value))
  (define (me request)
    (cond [(eq? request 'I-have-a-value)
           (process-new-value)]
          [(eq? request 'I-lost-my-value)
           (process-forget-value)]
          [else (error "Unknown request -- MULTPLIER" request)]))
  (connect m1 me)
  (connect m2 me)
  (connect product me)
  me)

(define (constant v connector)
  (define (me request)
    (error "Unknown request -- CONSTANT" request))
  (connect connector me)
  (set-value! connector v me)
  me)

(define (probe name connector)
  (define (print-probe value)
    (newline)
    (display "Probe: ")
    (display name)
    (display " = ")
    (display value))
  (define (process-new-value)
    (print-probe (get-value connector)))
  (define (process-forget-value)
    (print-probe "?"))
  (define (me request)
    (cond [(eq? request 'I-have-a-value)
           (process-new-value)]
          [(eq? request 'I-lost-my-value)
           (process-forget-value)]
          [else (error "Unknown request -- PROBE" request)]))
  (connect connector me)
  me)


(define (inform-about-value constraint)
  (constraint 'I-have-a-value))
(define (inform-about-no-value constraint)
  (constraint 'I-lost-my-value))
#+end_src

#+NAME: connector
#+begin_src racket :results none
(define (for-each-except exception procedure lst)
  (define (loop items)
    (cond [(null? items) 'done]
          [(eq? (car items) exception) (loop (cdr items))]
          [else (procedure (car items))
                (loop (cdr items))]))
  (loop lst))

(define (make-connector)
  (let ([value #f] [informant #f] [constraints '()])
    (define (set-my-value! newval setter)
      (cond [(not (has-value? me))
             (set! value newval)
             (set! informant setter)
             (for-each-except setter
                              inform-about-value
                              constraints)]
            [(not (= value newval))
             (error "Contradiction" (list value newval))]
            [else 'ignored]))
    (define (forget-my-value! retractor)
      (if (eq? retractor informant)
          (begin (set! informant #f)
                 (for-each-except retractor
                                  inform-about-no-value
                                  constraints))
          'ignored))
    (define (connect new-constraint)
      (if (not (memq new-constraint constraints))
          (set! constraints
                (cons new-constraint constraints)))
      (if (has-value? me)
          (inform-about-value new-constraint))
      'done)
    (define (me request)
      (cond [(eq? request 'has-value?)
             (if informant true false)]
            [(eq? request 'value) value]
            [(eq? request 'set-value!) set-my-value!]
            [(eq? request 'forget!) forget-my-value!]
            [(eq? request 'connect) connect]
            [(eq? request 'debug)
             (map display (list value "," informant "," constraints ".")) 'done]
            [else (error "Unknown request -- MAKE-CONNECTOR" request)]))
    me))

(define (has-value? connector)
  (connector 'has-value?))
(define (get-value connector)
  (connector 'value))
(define (set-value! connector v informant)
  ((connector 'set-value!) v informant))
(define (forget-value! connector retractor)
  ((connector 'forget!) retractor))
(define (connect connector new-constraint)
  ((connector 'connect) new-constraint))
#+end_src

*** 3.33

The constraint network is like this:

#+begin_src racket :noweb yes :results output
;<<connector>>
;<<constraint>>
(define (average-constraint a b res)
  (let ([sum (make-connector)]
        [two (make-connector)])
    (constant 2 two)
    (list (adder a b sum) (multiplier res two sum))))

(define x (make-connector))
(define y (make-connector))
(define avg (make-connector))

(average-constraint x y avg)
(probe "x" x)
(probe "y" y)
(probe "avg" avg)

(set-value! x 4 'user)
(set-value! y 2 'user)

(forget-value! x 'user)
(set-value! avg 5 'user)
#+end_src

#+RESULTS:
#+begin_example
(#<procedure:...rg-babel-X2kgeO.rkt:79:2> #<procedure:...rg-babel-X2kgeO.rkt:113:2>)
#<procedure:...rg-babel-X2kgeO.rkt:142:2>
#<procedure:...rg-babel-X2kgeO.rkt:142:2>
#<procedure:...rg-babel-X2kgeO.rkt:142:2>

Probe: x = 4done

Probe: y = 2
Probe: avg = 3done

Probe: x = ?
Probe: avg = ?done

Probe: avg = 5
Probe: x = 8done
#+end_example

Add a `me` into this, and combine the adder and multiplier to be a new constraint.

#+begin_src racket :noweb yes :results output
;<<connector>>
;<<constraint>>
(define (averager a b c)
  (let ([sum (make-connector)]
        [two (make-connector)])
    (constant 2 two)
    (let ([add (adder a b sum)]
          [mul (multiplier two c sum)])
      (define (process-new-value)
        (cond [(and (has-value? a) (has-value? b))
               (inform-about-value add)
               (inform-about-value mul)]
              [else
               (inform-about-value mul)
               (inform-about-value add)])
        me)
      (define (process-forget-value)
        (forget-value! a add)
        (forget-value! b add)
        (forget-value! sum add)
        (forget-value! c mul)
        (process-new-value))
      (define (me req)
        (cond [(eq? req 'I-have-a-value) (process-new-value)]
              [(eq? req 'I-lost-my-value) (process-forget-value)]
              [else (error "Unknown request -- AVERAGER" req)]))
      (connect a me)
      (connect b me)
      (connect c me)
      me)))

(define x (make-connector))
(define y (make-connector))
(define avg (make-connector))

(averager x y avg)
(probe "x" x)
(probe "y" y)
(probe "avg" avg)

(set-value! x 4 'user)
(set-value! y 2 'user)

(forget-value! x 'user)
(set-value! avg 5 'user)

(x 'debug)
#+end_src

#+RESULTS:
#+begin_example
#<procedure:...rg-babel-astWvv.rkt:176:6>
#<procedure:...rg-babel-astWvv.rkt:142:2>
#<procedure:...rg-babel-astWvv.rkt:142:2>
#<procedure:...rg-babel-astWvv.rkt:142:2>

Probe: x = 4done

Probe: y = 2
Probe: avg = 3done

Probe: x = ?
Probe: avg = ?done

Probe: avg = 5
Probe: x = 8done
8,#<procedure:...rg-babel-astWvv.rkt:79:2>,(#<procedure:...rg-babel-astWvv.rkt:142:2> #<procedure:...rg-babel-astWvv.rkt:176:6> #<procedure:...rg-babel-astWvv.rkt:79:2>).done
#+end_example

This code looks elegant. But there is one thing to be concerned: the constraints stored in a connector are now not irrelative. Let me consider the `x` in above test code: it have constraints of src_racket[:exports code]{(list averager add probe)}, and the `add` constraint is added by `averager`.

*** 3.34

#+NAME: 3-34
#+begin_src racket :results none
(define (squarer a b)
  (multiplier a a b))
#+end_src

Let me consider the src_racket[:exports code]{(set-value! a 2)}, this connect multiplier constraints twice to the `a`. The `process-new-value` in the constraint will be executed twice but still evaluated to right result.

While for src_racket[:exports code]{(set-value! b 9)}, the constraint find that only b have value and the other to don't. So there will be no result.

#+begin_src racket :results none :noweb-ref test-squarer
(define a (make-connector))
(define b (make-connector))
(probe "a: " a) (probe "b: " b)

(squarer a b)
(set-value! a 2 'user)

(forget-value! a 'user)
(set-value! b 9 'user)
(a 'debug)
#+end_src

#+begin_src racket :noweb yes :results output
;<<connector>>
;<<constraint>>
;<<3-34>>
;<<test-squarer>>
#+end_src

#+RESULTS:
#+begin_example
#<procedure:...rg-babel-6KMMSF.rkt:142:2>
#<procedure:...rg-babel-6KMMSF.rkt:142:2>
#<procedure:...rg-babel-6KMMSF.rkt:113:2>

Probe: b:  = 4
Probe: a:  = 2done

Probe: b:  = ?
Probe: a:  = ?done

Probe: b:  = 9done
2,#f,(#<procedure:...rg-babel-6KMMSF.rkt:113:2> #<procedure:...rg-babel-6KMMSF.rkt:142:2>).done
#+end_example

*** 3.35

#+begin_src racket :noweb yes :results output
;<<connector>>
;<<constraint>>
;<<square>>
(define (squarer a b)
  (define (process-new-value)
    (if (has-value? b)
        (if (< (get-value b) 0)
            (error "square less than 0 -- SQUARER" (get-value b))
            (begin (set-value! a (sqrt (get-value b)) me)
                   me))
        (if (has-value? a)
            (begin (set-value! b (square (get-value a)) me)
               me))))
  (define (process-forget-value)
    (forget-value! a me)
    (forget-value! b me)
    (process-new-value)
    )
  (define (me req)
    (cond [(eq? req 'I-have-a-value) (process-new-value)]
          [(eq? req 'I-lost-my-value) (process-forget-value)]
          [else (error "Unknown request -- SQUARER" req)]))
  (connect a me)
  (connect b me)
  me)
;<<test-squarer>>
#+end_src

#+RESULTS:
#+begin_example
#<procedure:...rg-babel-YPWdV3.rkt:142:2>
#<procedure:...rg-babel-YPWdV3.rkt:142:2>
#<procedure:...rg-babel-YPWdV3.rkt:172:2>

Probe: b:  = 4
Probe: a:  = 2done

Probe: b:  = ?
Probe: a:  = ?done

Probe: a:  = 3
Probe: b:  = 9done
3,#<procedure:...rg-babel-YPWdV3.rkt:172:2>,(#<procedure:...rg-babel-YPWdV3.rkt:172:2> #<procedure:...rg-babel-YPWdV3.rkt:142:2>).done
#+end_example

*** 3.36

For code:

#+begin_src racket :results none
(define a (make-connector))
(define b (make-connector))
(set-value! a 10 'user)
#+end_src

When evaluating src_racket[:exports code]{(for-each-except setter inform-about-value constraints)} of connector a, the environment diagram is:

#+begin_src
table <- global: a(#<procedure:((request), ...)>), b(...), make-connector(...), set-value!((connector, v, informant), ...), has-value?(...), ...

by-make-connector-a <- E1: (global), value(#f), informant(#f), constraints(nil), me((request), ...), set-my-value!(...), ...

by-make-connector-b <- E2: (global), ...

by-set-a-10-user <- E3: (global), connector(a), v(10), informat('user), ...

by-connector-set-value <- E4: (E1), request('set-value!)

by-set-my-value <- E5: (E1), newval(10), setter('user), ...

by-for-each-except <- E6: (global), exception('user), procedure(inform-about-value), lst(nil)
#+end_src

*** 3.37

#+begin_src racket :noweb yes :results output
;<<connector>>
;<<constraint>>
(define (c+ x y)
  (let ([z (make-connector)])
    (adder x y z)
    z))

(define (c3-third constraint-three x y)
  (let ([z (make-connector)])
    (constraint-three x y z)
    z))
(define (c3-second constraint-three x z)
  (let ([y (make-connector)])
    (constraint-three x y z)
    y))
(define (c* x y) (c3-third multiplier x y))
(define (c/ z x) (c3-second multiplier x z))
(define (cv v)
  (let ([new-constant (make-connector)])
    (constant v new-constant)
    new-constant))

(define (celsius-fahrenheit-converter x)
  (c+ (c* (c/ (cv 9) (cv 5))
          x)
      (cv 32)))

(define C (make-connector))
(define F (celsius-fahrenheit-converter C))

(probe "Celsius temp" C)
(probe "Fahrenheit temp" F)

(set-value! C 25 'user)

(forget-value! C 'user)

(set-value! F 212 'user)
#+end_src

#+RESULTS:
#+begin_example
#<procedure:...rg-babel-CpHojq.rkt:142:2>
#<procedure:...rg-babel-CpHojq.rkt:142:2>

Probe: Celsius temp = 25
Probe: Fahrenheit temp = 77done

Probe: Celsius temp = ?
Probe: Fahrenheit temp = ?done

Probe: Fahrenheit temp = 212
Probe: Celsius temp = 100done
#+end_example

* Book 3.4 Concurrency: Time Is of the Essence

** Book 3.4.1 The Nature of Time in Concurrent Systems

*** 3.38

Peter, Paul and Mary share an account and:

#+begin_src
(Balance is 100 at begin)
Peter: (set! balance (+ balance 10))
Paul:  (set! balance (- balance 20))
Mary:  (set! balance (- balance (/ balance 2)))
#+end_src

a) If they are not executed concurrently. When Mary withdraw matters. All four passible result of balance can be: 40(50+10-20), 35(110/2-20), 50(80/2+10), 45(90/2).
b) Concurrently. There's a lot possibilities. I tend to consider that each operation can be divided to read balance and write new balance. Thus an arrangement $A_6^6 = 720$ or maybe less, considering the three people may all read the balance then anyone to change and the order of reading not matters, to be $A_3^3 + C_3^2C_3^1A_3^3 + C_3^1C_3^1A_3^3 = 19 * 6 = 114$. Or less? $A_4^3 + C_3^1A_4^2 + A_4^1 = 24 + 36 + 4 = 94$. This still more than 4 in question a).
   For example, after Mary withdraw, Peter is about to deposit and Paul is about to withdraw. Peter read the balance is 50 and then try to change the balance to 60, before this Paul read the balance 50 and change to 30. In the end, balance changes to 60.

** Book 3.4.2 Mechanisms of Controlling Concurrency

*** example

The 20 possibilities to combine the can be generated by
#+begin_src racket :results none
(permutation ('a 'b 'c 'x 'y 'z))
(define (ordered? order lst)
  (if (null? order) #t
      (let ([res (memq (car order) lst)])
        (if res (ordered? (cdr order) res)
            #f)))
(filter (lambda (lst) (and (ordered? ('a 'b 'c) lst)
                           (ordered? ('x 'y 'z)))) possibilities)
#+end_src


Or use interpolation method: there's 4 position of (a b c) to insert events in (x y z), or expressed as [? a ? b ? c ?] while the "?" can be [x y z] or [x y] or [y z] or [x] or [z]. Thus to $20 = C_2^1 \cdot (C_4^1 + (1 + 2 + 3) \cdot 2 \div 2)$.

*** 3.39

#+begin_src racket :results none
(define x 10)
(define s (make-serializer))
(parallel-execute (lambda () (set! x ((s (lambda () (* x x))))))
                  (s (lambda () (set! x (+ x 1)))))
#+end_src

From 101, 121, 110, 11, 100, the results of x may be one of 100, 101, 121.

There are only 3 operations: get-x-and-square, inc-x, set-the-square, and the set-the-square should be executed after get-x-and-square. So there's only 3 possibility.

*** 3.40

#+begin_src racket :results none
(define x 10)
(parallel-execute (lambda () (set! x (* x x)))
                  (lambda () (set! x (* x x x))))
#+end_src

100^3 and 1000^2, 100 and 1000, 10*1000 and 10*100*100 and 10*10*100: 10^2, 10^3, 10^4, 10^5, 10^6.

For below, only 10^6. (100^3 or 1000^2)

#+begin_src racket :results none
(define x 10)
(parallel-execute (s (lambda () (set! x (* x x))))
                  (s (lambda () (set! x (* x x x)))))
#+end_src

*** 3.41

#+begin_src racket
(define (make-account balance)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (let ((protected (make-serializer)))
    (define (dispatch m)
      (cond ((eq? m 'withdraw) (protected withdraw))
            ((eq? m 'deposit) (protected deposit))
            ((eq? m 'balance)
             ((protected (lambda () balance)))) ; serialized
            (else (error "Unknown request -- MAKE-ACCOUNT"
                         m))))
    dispatch))
#+end_src

But the getter of `balance` doesn't change its value.

Although, here's a embarassing condition that, if Bob share a same account with Paul, and the Bob deside to withdraw 100 after he see the balance is 100 but failed because Paul withdraw first right before Bob withdraw 100.

*** 3.42

#+begin_src racket :results none
(define (make-account balance)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (let ((protected (make-serializer)))
    (let ((protected-withdraw (protected withdraw))
          (protected-deposit (protected deposit)))
      (define (dispatch m)
        (cond ((eq? m 'withdraw) protected-withdraw)
              ((eq? m 'deposit) protected-deposit)
              ((eq? m 'balance) balance)
              (else (error "Unknown request -- MAKE-ACCOUNT"
                           m))))
      dispatch)))
#+end_src

This disallow parallel execution between withdraw and deposit. But this can't prevent parallel of multiple withdraw executing or multiple deposit executing.

Just like Exercise 3.40, in this form:

#+begin_src racket :results none
(define balance x)
(parallel-execute (lambda () (set! balance (+ balance amout1)))
                  (lambda () (set! balance (+ balance amout2))))
#+end_src

*** 3.43

#+NAME: account-exchange
#+begin_src racket :results none
(define (exchange acc1 acc2)
  (let ([diff (- (acc1 'balance) (acc2 'balance))])
    ((acc1 'withdraw) diff)
    ((acc2 'deposit) diff)))
#+end_src

Maybe we can accept that the src_racket[:exports code]{((acc1 'withdraw) diff)} and src_racket[:exports code]{((acc2 'deposit) diff)} executed parallelly since the change of balance is serialized. The vulnerability lays at getting the value of `diff`.

**** exp1

As for src_racket[:exports code]{(exchange acc1 acc2)} and src_racket[:exports code]{(exchange acc1 acc3)}:

#+begin_src
execution diff1=10-20 -> diff2=10-30 -> acc1 'withdraw diff1 -> acc1 'withdraw diff2 -> acc2 'deposit diff1 -> acc3 'depost diff2
acc1            10            10                20                        40                     40                      40
acc2            20            20                10                        10                     20                      20
acc3            30            30                30                        30                     30                      10
#+end_src

This due to the the computation of `diff` can be executed between the other exchange process when the other have computed its `diff` to goto modifying the value of accounts.

**** exp2

src_racket[:exports code]{(exchange acc1 acc2)} and src_racket[:exports code]{(exchange acc2 acc3)}:

#+begin_src
execution diff1=10-20 -> acc1 'withdraw diff1 -> diff2=20-30 -> acc2 'withdraw diff2 -> acc3 'depost diff2 -> acc2 'deposit diff1
acc1            10               20                   20                  20                      20                   20
acc2            20               20                   20                  30                      30                   20
acc3            30               30                   30                  30                      20                   20
#+end_src

This due to the computation of `diff` to get the balance of two account is not atomic.

*** 3.44

#+begin_src racket :results none
(define (transfer from-acc to-acc amount)
  ((from-acc 'withdraw) amout)
  ((to-acc 'deposit) amout))
#+end_src

This is correct code since the operation to change the balance is atmoic. Not like the `exchange` in Exercise 3.43, the value of the amount is determinted as the argument, and the wrong cases not happen with this code.

*** 3.45

Firstly I'd like to define a expression method for a queue. The `|c b a>` means a queue with element `a`, `b`, `c`, and, the head is `a` follows a ">" and rear is `c` followed by "|".

The serial execution behaves like a FIFO queue. I use this to express serials.

#+begin_src racket :results none
(define (make-account-and-serializer balance)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (let ((balance-serializer (make-serializer)))
    (define (dispatch m)
      (cond ((eq? m 'withdraw) (balance-serializer withdraw))
            ((eq? m 'deposit) (balance-serializer deposit))
            ((eq? m 'balance) balance)
            ((eq? m 'serializer) balance-serializer)
            (else (error "Unknown request -- MAKE-ACCOUNT"
                         m))))
    dispatch))

(define (deposit account amount)
 ((account 'deposit) amount))
#+end_src

The above codes are all right. But when it comes to `serialized-exchange`, these code are not proper.

#+begin_src racket :noweb yes
;<<account-exchange>>
(define (serialized-exchange account1 account2)
  (let ((serializer1 (account1 'serializer))
        (serializer2 (account2 'serializer)))
    ((serializer1 (serializer2 exchange))
     account1
     account2)))
#+end_src

When executing a process of `serialized-exchange`, the serial from `|(serializer2 exchange) exchange>` to `|(acc1 'withdraw) (serializer2 exchange) exchange>`.
The `(acc1 'withdraw)` is waiting the `exchange` to complete even if there's a single process(thread)! This is a deadlock.

*** 3.46

#+begin_src racket :results none
(define (make-serializer)
  (let ([mutex (make-mutex)])
    (lambda (p)
      (define (serialized-p . args)
        (mutex 'aquire)
        (let ([val (apply p args)])
          (mutex 'release)
          val))
      serialized-p)))

(define (make-mutex)
  (let ([cell (list false)])
    (define (the-mutex m)
      (cond [(eq? m 'aquire)
             (if (test-and-set! cell)
                 (the-mutex 'aquire))]
            [(eq? m 'release) (clear! cell)]))
    the-mutex))

(define (clear! cell)
  (set-car! cell false))
(define (test-and-set! cell)
  (if (car cell)
      true
      (begin (set-car! cell true)
             false)))
#+end_src

If the `test-and-set!` is not atomic, two process may execute the `if` statement simultaneously, the mutex will fail.

#+begin_src
execute (make-mutex) -> proc1: (mutex 'aquire),  -into> proc1: (test-and-set! cell), -into> proc1: (if (car cell) ...), -into> proc1: (begin (set-car! cell ture) ...)
                        proc2: (mutex 'aquire)          proc2: (test-and-set! cell)         proc2: (if (car cell) ...)         proc2: (begin (set-car! cell ture) ...)
cell         (#f)                  (#f)                         (#f)                               (#f)                                   (#t)
#+end_src

*** 3.47

The interface names are from racket standard library, see the extra section below.

**** a) semaphore based on mutex

#+begin_src racket :results none
(define (mutex-execute mutex f . args)
  (mutex 'aquire)
  (apply f args)
  (mutex 'release))

(define (make-semaphore max-proc-num)
  (let ([mutex (make-mutex)] [n max-proc-num])
    (define (semaphore-wait)
      (define spin semaphore-wait)
      (mutex-execute mutex
                     (lambda ()
                       (if (= n 0) (spin)
                           (set! n (dec n))))))
    (define (semaphore-post)
      (mutex-execute mutex
                     (lambda ()
                       (if (= n max-proc-num)
                           (error "Do not support increase maximum process number -- MAKE-SEMAPHORE" n)
                           (set! n (inc n))))))
    (define (dispatch m)
      (cond [(eq? m 'semaphore-wait) semaphore-wait]
            [(eq? m 'semaphore-post) semaphore-post]
            [else (error "Unknown operation -- MKAE-SEMAPHORE" m)]))))
#+end_src

**** b) semaphore based on test-and-set

#+begin_src racket :results none
(define (make-cell) (list false))
(define (atomic-execute-by-cell cell f . args)
  (define (spin) (atomic-execute-by-cell
                  cell (lambda () (apply f args))))
  (if (test-and-set! cell)
      (spin)
      (apply f args)))

(define (make-semaphore max-proc-num)
  (let ([mutex (make-mutex)] [n max-proc-num])
    (define (semaphore-wait)
      (define spin semaphore-wait)
      (atomic-execute-by-cell cell
                              (lambda ()
                                (if (= n 0) (spin)
                                    (set! n (dec n))))))
    (define (semaphore-post)
      (atomic-execute-by-cell cell
                              (lambda ()
                                (if (= n max-proc-num)
                                    (error "Do not support increase maximum process number -- MAKE-SEMAPHORE" n)
                                    (set! n (inc n))))))
    (define (dispatch m)
      (cond [(eq? m 'semaphore-wait) semaphore-wait]
            [(eq? m 'semaphore-post) semaphore-post]
            [else (error "Unknown operation -- MKAE-SEMAPHORE" m)]))))
#+end_src

*** extra

I use racket and there's no `without-interrupts` which in the MIT scheme.

#+begin_src racket
without-interrupts
#+end_src

#+RESULTS:
: c:\Users\asu\AppData\Local\Temp\org-babel-Ddl7WA.rkt:5:0: without-interrupts: unbound identifier
:   in: without-interrupts
:   location...:
:    c:\Users\asu\AppData\Local\Temp\org-babel-Ddl7WA.rkt:5:0

I can use semaphore in racket standard library to simulate a `test-and-set!`. This means they can implement each other.

Below use `#lang racket` with racket standard library, and these may not follow sicp scheme syntax.

#+begin_src racket :lang racket
(define (make-cell)
  (let ([v #f] [sema (make-semaphore 1)])
    (define (clear!) (call-with-semaphore sema (lambda () (set! v #t) #f)))
    (define (test-and-set!)
      (let ([res #f])
        (call-with-semaphore sema
                             (lambda ()
                               (if v true (begin (set! v true)
                                                 false))))))
    (define (dispatch m)
      (cond [(eq? m 'clear!) clear!]
            [(eq? m 'test-and-set!) test-and-set!]
            [else (error "Unknown opearaion -- MAKE-CELL" m)]))
    dispatch))
(define (clear! cell) ((cell 'clear!)))
(define (test-and-set! cell) ((cell 'test-and-set!)))
#+end_src

*** 3.48

#+begin_src racket :noweb yes :results none
(define (make-counter start)
  (define (count)
    (begin (set! start (inc start))
           start))
  count)

(define (make-id-generator) (make-counter 1))
(define id-generator (make-id-generator))

(define (make-account-and-serializer balance)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (let ((balance-serializer (make-serializer)) (id (id-generator)))
    (define (dispatch m)
      (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            ((eq? m 'balance) balance)
            ((eq? m 'serializer) balance-serializer)
            ((eq? m 'id) id)
            (else (error "Unknown request -- MAKE-ACCOUNT"
                         m))))
    dispatch))

;<<account-exchange>>
(define (serialized-exchange account1 account2)
  (let ((serializer1 (account1 'serializer))
        (serializer2 (account2 'serializer)))
    ((if (< (account1 'id) (account2 'id))
         (serializer2 (serializer1 exchange))
         (serializer1 (serializer2 exchange)))
     account1
     account2)))
#+end_src

By this way, parallel execution of `(exchange acc1 acc2)` with `(exchange acc2 acc1)` won't makes simultaneous aquires of mutex of two exchange processes to each other.
Or to say, it force the lock order to prevent the case leads to deadlock.

Anothet thing to concern is that the `make-id-generator` is not implemented to be thread safe. (It could be but I'm lazy)

*** 3.49

This question is hard and I really don't know how to design a case which deadlock inevitable by any solution.
If this question only means to image a situation that the id method will failure, there's a example: in a certain time, to exchange balance of one certain account with the account have greatest balance; execute this by multiple processes parallelly. While this can be solved by use `big lock` to all accounts.

*  3.5 Streams

** 3.5.1 Streams are Delayed Lists

*** exp

#+NAME: cons-stream
#+begin_src racket :results none :noweb-ref stream
; `the-empty-stream`, `stream-null?`, `cons-stream` are defined in sicp

(define (stream-car stream) (car stream))
(define (stream-cdr stream) (force (cdr stream)))

(define (stream-ref s n)
  (if (= n 0) (stream-car s)
      (stream-ref (stream-cdr s) (dec n))))
(define (stream-for-each f s)
  (if (stream-null? s) 'done
      (begin (f (stream-car s))
             (stream-for-each f (stream-cdr s)))))
(define (stream-enumerate-interval a b)
  (if (> a b) the-empty-stream
      (cons-stream a (stream-enumerate-interval (inc a) b))))
(define (stream-filter pred s)
  (cond [(stream-null? s) the-empty-stream]
        [(pred (stream-car s))
         (cons-stream (stream-car s) (stream-filter pred (stream-cdr s)))]
        [else (stream-filter pred (stream-cdr s))]))
(define (stream-take s n)
  (if (zero? n) '()
      (cons (stream-car s) (stream-take (stream-cdr s) (dec n)))))
#+end_src

I go to see some docs of R5RS and implement this.

#+begin_src racket :results output :noweb yes
(define (memo-proc proc)
  (let ([already-run #f] [result #f])
    (lambda ()
      (if already-run
          result
          (begin (set! already-run #t)
                 (set! result (proc))
                 result)))))

;; (define (delay expr) (memo-proc (lambda () expr))) ; not lazy
(define-syntax delay
  (syntax-rules ()
    ([delay expr]
     (memo-proc (lambda () expr)))))
(define (force delayed) (delayed))

(define the-empty-stream '())
(define-syntax stream-cons
  (syntax-rules ()
    [(_ a b) (cons a (delay b))]))
(define stream-car car)
(define (stream-cdr s) (force (cdr s)))

(define (stream-take s n)
  (if (zero? n) '()
      (cons (stream-car s) (stream-take (stream-cdr s) (dec n)))))

(stream-cons 1 the-empty-stream)
(stream-cdr (stream-cons 1 the-empty-stream))
(define ones (stream-cons 1 ones)) ; see book 3.5.2
(stream-take ones 10)
#+end_src

#+RESULTS:
: (1 . #<procedure:...rg-babel-TNZDcj.rkt:6:4>)
: ()
: (1 1 1 1 1 1 1 1 1 1)

I find that I can't implement a lazy fold function of stream...

#+NAME: list->stream
#+begin_src racket :noweb yes
;<<fold>>
(define (stream-fold-right-eager f init s)
  (if (stream-null? s) init
      (f (stream-car s) (stream-fold-right-eager f init (stream-cdr s)))))

(define (list->stream lst)
  ;; cannot use cons-stream directly to fold-right because it's not function
  (fold-right (lambda (x acc) (cons-stream x acc)) the-empty-stream lst))
(define (stream->list s)
  (stream-fold-right-eager cons '() s))
#+end_src

Below fold is inspired from Exercise 3.63.

#+NAME: stream-fold
#+begin_src racket
(define (stream-accumulate-fold-left f init s)
  (if (stream-null? s) the-empty-stream
      (cons-stream
       init
       (stream-accumulate-fold-left f
                                    (f init (stream-car s))
                                    (stream-cdr s)))))
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<stream-fold>>
;<<higher-order>>
(define (flip f2) (lambda (x y) (f2 y x)))
(stream-take (stream-accumulate-fold-left (flip cons) nil ones) 10)
#+end_src

#+RESULTS:
: (() (1) (1 1) (1 1 1) (1 1 1 1) (1 1 1 1 1) (1 1 1 1 1 1) (1 1 1 1 1 1 1) (1 1 1 1 1 1 1 1) (1 1 1 1 1 1 1 1 1))


*** 3.50

#+NAME: stream-map
#+begin_src racket :noweb yes :results none :noweb-ref stream
(define (stream-map proc . argstreams)
  (if (stream-null? (car argstreams))
      the-empty-stream
      (cons-stream
       (apply proc (map stream-car argstreams))
       (apply stream-map
              (cons proc (map stream-cdr argstreams))))))
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<list->stream>>
(stream->list (stream-map +
                          (list->stream (list 1 2 3))
                          (list->stream (list 40 50 60))
                          (list->stream (list 700 800 900))))
#+end_src

#+RESULTS:
: (741 852 963)

*** 3.51

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<displayln>>
(define (show x) (displayln x) x)

(define x (stream-map show (stream-enumerate-interval 0 10)))

(stream-ref x 5) ; => 5
; print integers in [0, 5], each number a line, then 5.
(stream-ref x 7) ; => 7
; print integers in 6 and 7, each number a line, then 7.
#+end_src

#+RESULTS:
#+begin_example
0
1
2
3
4
5
5
6
7
7
#+end_example

*** 3.52

This reminds me arithmetic sequence: $a_1 = 1, a_{n+1} = a_n + 1, S_n = a_1 + a_2 + ... + a_n$.

See some values of `seq`, it's easy to know that in `seq`, two odd numbers follows two even numbers, and two even numbers follows to odd numbers. So the 8th number in `y` is the 2*8 + 8 mod 2 = 16th in `seq`, and it's 210-20-19-18-17=136.

Notice that $1+2+3+4=10$ is multiple of 5, and $6+7+8+9=1+2+3+4+4*5$ is multiple of 5. For every 5 numbers in `seq`, the last two in the 5 numbers are multiple of 5.
They are $0+10+0*4*5=10, 10+5=15, 15+10+1*4*5=30+15=45, 45+10=55, 55+10+2*4*5=105, 105+15=120, 190, 210$.

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<displayln>>
;<<list->stream>>
(define display-stream stream->list)

(define sum 0)
(define (accum x)
  (set! sum (+ x sum))
  sum)

(define seq (stream-map accum (stream-enumerate-interval 1 20))) ; 1, 3, 6, 10, ..., 210
(define y (stream-filter even? seq))
(define z (stream-filter (lambda (x) (= (remainder x 5) 0)) seq))

(displayln (stream-ref y 7)) ; => 136
(display-stream z) ; => 10, 15, 30, 35, ..., 190, 210
#+end_src

#+RESULTS:
: 136
: (10 15 45 55 105 120 190 210)

If the `delay` is not implemented with `memo-proc`, the src_racket[:exports code]{(display-stream z)} would be wrong, because it will accumulate `sum` again from 1 in `seq`, while `sum` now is not 0 anymore.
It will print 28+1, 29+2, 31+3, 34+4, ..., 28*20+190+20.

And this is why some implementation of stream can only be consumed(iterated) once.

** Book 3.5.2 Infinite Streams

*** exp

#+NAME: divisible
#+begin_src racket :noweb yes :results output
;<<cons-stream>>
(define (integers-starting-from n)
  (cons-stream n (integers-starting-from (inc n))))

(define integers (integers-starting-from 1))

(define (divisible? a m) (= (remainder a m) 0))

(define no-sevens
  (stream-filter (lambda (x) (not (divisible? x 7))) integers))

(stream-take no-sevens 10)
(stream-ref no-sevens 100)
#+end_src

#+RESULTS:
: (1 2 3 4 5 6 8 9 10 11)
: 117

#+begin_src racket :noweb yes :results output
;<<stream>>
(define (fibgen a b)
  (cons-stream a (fibgen b (+ a b))))

(define fib (fibgen 1 1))

(stream-take fib 10)
#+end_src

#+RESULTS:
: (1 1 2 3 5 8 13 21 34 55)

#+begin_src racket :noweb yes :results output
;<<divisible>>
(define (sieve stream)
  (cons-stream
   (stream-car stream)
   (sieve (stream-filter
           (lambda (x)
             (not (divisible? x (stream-car stream))))
           (stream-cdr stream)))))

(define primes (sieve (integers-starting-from 2)))
(stream-take primes 10)
(stream-ref primes 50)
#+end_src

#+RESULTS:
: (1 2 3 4 5 6 8 9 10 11)
: 117
: (2 3 5 7 11 13 17 19 23 29)
: 233

#+NAME: add-streams
#+begin_src racket :results none :noweb-ref stream
(define (add-streams s1 s2) (stream-map + s1 s2))
#+end_src

#+NAME: integer
#+begin_src racket :results none :noweb-ref stream
(define ones (cons-stream 1 ones))
(define integers (cons-stream 1 (add-streams ones integers)))
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
(define fibs
  (cons-stream 0
               (cons-stream 1 (add-streams fibs (stream-cdr fibs)))))

(stream-take ones 10)
(stream-take integers 10)
(stream-take fibs 10)
#+end_src

#+RESULTS:
: (1 1 1 1 1 1 1 1 1 1)
: (1 2 3 4 5 6 7 8 9 10)
: (0 1 1 2 3 5 8 13 21 34)

#+NAME: scale-stream
#+begin_src racket :results none :noweb-ref stream
(define (scale-stream s factor)
  (stream-map (lambda (x) (* x factor)) s))
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
(define double (cons-stream 1 (scale-stream double 2)))
(stream-take double 10)
#+end_src

#+RESULTS:
: (1 2 4 8 16 32 64 128 256 512)

#+begin_src racket :noweb yes :results output
;<<divisible>>
;<<square>>
(define primes
  (let ([prime? (lambda (n)
                  (define (iter ps)
                    (cond [(> (square (stream-car ps)) n) #t]
                          [(divisible? n (stream-car ps)) #f]
                          [else (iter (stream-cdr ps))]))
                  (iter (integers-starting-from 2)))])
    (cons-stream
     2
     (stream-filter prime? (integers-starting-from 3)))))

(stream-take primes 10)
#+end_src

#+RESULTS:
: (1 2 3 4 5 6 8 9 10 11)
: 117
: (2 3 5 7 11 13 17 19 23 29)

*** 3.53

But I should run the code to confirm I'm right. This below stream constructs a geometric sequence: $a_n = 2^{(n-1)}$.

#+begin_src racket :noweb yes :results output
;<<stream>>
(define s (cons-stream 1 (add-streams s s)))

(stream-take s 10)
#+end_src

#+RESULTS:
: (1 2 4 8 16 32 64 128 256 512)

***  3.54

#+NAME: mul-streams
#+begin_src racket :results none :noweb-ref stream
(define (mul-streams a b) (stream-map * a b))
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
(define factorials (cons-stream 1 (mul-streams factorials integers)))

(stream-take factorials 10)
#+end_src

#+RESULTS:
: (1 1 2 6 24 120 720 5040 40320 362880)

*** 3.55

#+NAME: partial-sums
#+begin_src racket :results none :noweb-ref stream
(define (partial-sums s) (cons-stream (stream-car s) (add-streams (partial-sums s) (stream-cdr s))))
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>

(stream-take (partial-sums integers) 10)
#+end_src

#+RESULTS:
: (1 3 6 10 15 21 28 36 45 55)

*** 3.56

I've solved this problem to generate an array of this in C++ using recursion: for each number in array generates 3 recursion calls, the most tricky point is to make choice between current function execution and newer 3 numbers with their 9 function calls. This implementation use merge other than make choices.

#+NAME: merge-streams
#+begin_src racket :results none
(define (merge s1 s2)
  (cond [(stream-null? s1) s2]
        [(stream-null? s2) s1]
        [else
         (let ([s1car (stream-car s1)]
               [s2car (stream-car s2)])
           (cond [(< s1car s2car)
                  (cons-stream s1car (merge (stream-cdr s1) s2))]
                 [(> s1car s2car)
                  (cons-stream s2car (merge s1 (stream-cdr s2)))]
                 [else
                  (cons-stream s1car (merge (stream-cdr s1)
                                            (stream-cdr s2)))]))]))
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<merge-streams>>
(define s (cons-stream 1 (merge
                          (scale-stream s 2)
                          (merge (scale-stream s 3)
                                 (scale-stream s 5)))))

(stream-take s 20)
#+end_src

#+RESULTS:
: (1 2 3 4 5 6 8 9 10 12 15 16 18 20 24 25 27 30 32 36)

*** 3.57

#+begin_src racket :noweb yes :results output
;<<stream>>
(define fibs (cons-stream 0
                          (cons-stream 1
                                       (add-streams fibs (stream-cdr fibs)))))

(stream-take fibs 10)
#+end_src

By this way, the stream values will be memorized, so it needs only one `+` operation to compute a next item of fibonacci sequence.
To compute the n-th item(n from 0), it needs $n-1 + floor(x^{-n})$ plus operation.

If this mechanism(`memo-proc`) is not used, it needs to calucate the before item and a more before item($fib_{n-1}, fib_{n-2}$), but these two needs the more before items too. So this becomes to a tree recursion just like the function in Book 1.2.2.

*** 3.58

Below codes generates the fractional part of a division $\frac{num}{den}$ in order in base `radix`, if the input `num` is less than `den`; other wise the first element is sum of a quotient of a one-left-shifted of the division with the first firactional digit, then generates the fractional part. All results are expressed by base 10.

#+begin_src racket :noweb yes :results output
;<<stream>>
(define (expand num den radix)
  (cons-stream
   (quotient (* num radix) den)
   (expand (remainder (* num radix) den) den radix)))

(stream-take (expand 1 7 10) 10) ; 1 4 2 8 5 7 ...
(stream-take (expand 3 8 10) 10) ; 3 7 5 0 0 0 0 0 0 0
(stream-take (expand 50 7 10) 10) ; 70 1 4 2 8 5 7 ...
(stream-take (expand 3 8 8) 10) ; 3 0 0 0 0 0 ...
(stream-take (expand 3 8 16) 10) ; 6 0 0 0 0 0 ...
#+end_src

#+RESULTS:
: (1 4 2 8 5 7 1 4 2 8)
: (3 7 5 0 0 0 0 0 0 0)
: (71 4 2 8 5 7 1 4 2 8)
: (3 0 0 0 0 0 0 0 0 0)
: (6 0 0 0 0 0 0 0 0 0)

*** 3.59

#+NAME: negative-stream
#+begin_src racket :results none :noweb-ref stream
(define (negative-stream s)
  (define (negative x) (- 0 x))
  (stream-map negative s))
#+end_src

#+begin_src racket :noweb yes :results none :noweb-ref series
(define (invert x) (/ 1 x))
(define (stream-inexact s) (stream-map exact->inexact s))
(define (accumulate-stream s) (stream-inexact (partial-sums s)))
(define (items x series)
  (define vars (cons-stream 1 (scale-stream vars x)))
  (mul-streams vars series))
(define (eval-series x item-number s)
  (stream-ref (accumulate-stream (items x s)) (dec item-number)))

(define (integrate-series s)
  (mul-streams s (stream-map invert integers)))

(define exp-series
  (cons-stream 1 (integrate-series exp-series)))

(define cosine-series
  (cons-stream 1 (integrate-series (negative-stream sine-series))))
(define sine-series
  (cons-stream 0 (integrate-series cosine-series)))
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<series>>
(stream-take (integrate-series ones) 10)
(stream-take exp-series 10)
(stream-take cosine-series 10)
(stream-take sine-series 10)

(stream-take (accumulate-stream exp-series) 10)
(stream-take (accumulate-stream sine-series) 10)
(stream-take (accumulate-stream cosine-series) 10)
#+end_src

#+RESULTS:
: (1 1/2 1/3 1/4 1/5 1/6 1/7 1/8 1/9 1/10)
: (1 1 1/2 1/6 1/24 1/120 1/720 1/5040 1/40320 1/362880)
: (1 0 -1/2 0 1/24 0 -1/720 0 1/40320 0)
: (0 1 0 -1/6 0 1/120 0 -1/5040 0 1/362880)
: (1.0 2.0 2.5 2.6666666666666665 2.7083333333333335 2.716666666666667 2.7180555555555554 2.7182539682539684 2.71827876984127 2.7182815255731922)
: (0.0 1.0 1.0 0.8333333333333334 0.8333333333333334 0.8416666666666667 0.8416666666666667 0.841468253968254 0.841468253968254 0.8414710097001764)
: (1.0 1.0 0.5 0.5 0.5416666666666666 0.5416666666666666 0.5402777777777777 0.5402777777777777 0.5403025793650794 0.5403025793650794)

*** 3.60

#+NAME: mul-series
#+begin_src racket :noweb yes :noweb-ref series
(define (mul-series s1 s2)
  (cons-stream (* (stream-car s1) (stream-car s2))
               (add-streams (scale-stream (stream-cdr s2) (stream-car s1))
                            (mul-series (stream-cdr s1) s2))))
#+end_src


#+begin_src racket :noweb yes :results output
;<<stream>>
;<<series>>
(define (square-series s) (mul-series s s))

(stream-take (add-streams (square-series cosine-series)
                          (square-series sine-series))
             10)
#+end_src

#+RESULTS:
: (1 0 0 0 0 0 0 0 0 0)

*** 3.61

#+NAME: invert-series
#+begin_src racket :noweb yes :results none
(define (invert-series s)
  (cons-stream
   1
   (negative-stream (mul-series (stream-cdr s)
                                (invert-series s)))))
#+end_src

*** 3.62

#+NAME: div-series
#+begin_src racket :noweb yes :results output
;<<stream>>
;<<series>>
;<<invert-series>>
(define (div-series s t)
  (cond [(zero? (stream-car t)) (error "Division by zero -- DIV-SERIES" t)]
        [(= (stream-car t) 1) (mul-series s (invert-series t))]
        [else (mul-series s (scale-stream t (/ 1 (stream-car t))))]))

(define tangent-series (div-series sine-series cosine-series))
(eval-series (atan 0.5) 20 tangent-series)
#+end_src

#+RESULTS: div-series
: 0.4999999999896264

** Book 3.5.3 Exploiting the Stream Paradigm

*** exp

#+NAME: sqrt-stream
#+begin_src racket :noweb yes :results none
;<<average>>
(define (sqrt-improve guess a)
  (average guess (/ a guess)))
(define (sqrt-stream n)
  (define guesses
    (cons-stream 1.0
                 (stream-map (lambda (guess)
                               (sqrt-improve guess n))
                             guesses)))
  guesses)
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<sqrt-stream>>
(stream-take (sqrt-stream 2) 10)
#+end_src

#+RESULTS:
: (1.0 1.5 1.4166666666666665 1.4142156862745097 1.4142135623746899 1.414213562373095 1.414213562373095 1.414213562373095 1.414213562373095 1.414213562373095)

#+NAME: pi-stream
#+begin_src racket :results none
(define (pi-summands n)
  (cons-stream (/ 1.0 n)
               (stream-map - (pi-summands (+ n 2)))))
(define pi-stream
  (scale-stream (partial-sums (pi-summands 1)) 4))
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<pi-stream>>
(stream-take pi-stream 10)
#+end_src

#+RESULTS:
: (4.0 2.666666666666667 3.466666666666667 2.8952380952380956 3.3396825396825403 2.9760461760461765 3.2837384837384844 3.017071817071818 3.2523659347188767 3.0418396189294032)

#+NAME: euler-transform
#+begin_src racket :results none :noweb yes
;<<square>>
(define (euler-transform s)
  (let ([s0 (stream-ref s 0)]
        [s1 (stream-ref s 1)]
        [s2 (stream-ref s 2)])
    (cons-stream (- s2 (/ (square (- s2 s1))
                          (+ s0 (* -2 s1) s2)))
                 (euler-transform (stream-cdr s)))))
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<pi-stream>>
;<<euler-transform>>
(stream-take (euler-transform pi-stream) 10)
#+end_src

#+RESULTS:
: (3.166666666666667 3.1333333333333337 3.1452380952380956 3.13968253968254 3.1427128427128435 3.1408813408813416 3.142071817071818 3.1412548236077655 3.1418396189294033 3.141406718496503)

#+NAME: accelerated-sequence
#+begin_src racket
(define (make-tableau transform s)
  (cons-stream s
               (make-tableau transform
                             (transform s))))

(define (accelerated-sequence transform s)
  (stream-map stream-car (make-tableau transform s)))
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<pi-stream>>
;<<euler-transform>>
;<<accelerated-sequence>>
(stream-take (accelerated-sequence euler-transform pi-stream) 10)
#+end_src

#+RESULTS:
: (4.0 3.166666666666667 3.142105263157895 3.141599357319005 3.1415927140337785 3.1415926539752927 3.1415926535911765 3.141592653589778 3.1415926535897953 3.141592653589795)

*** 3.63

#+begin_src racket
(define (sqrt-stream x)
  (cons-stream 1.0
               (stream-map (lambda (guess)
                             (sqrt-improve guess x))
                           (sqrt-stream x))))
#+end_src

This reminds me about Exercise 3.61. I exactly do like this. Compare to the `guesses` version, this would call `sqrt-stream` more times but fortunately they're memorized by the `memo-proc` before. If there's no memorization mechanism, this procedure would be slow.

*** 3.64

#+NAME: stream-limit
#+begin_src racket :results none
(define (stream-limit s err)
  (define (iter before s)
    (cond [(stream-null? s) #f]
          [(stream-null? (stream-cdr s)) #f]
          [else (if (< (abs (- (stream-car s) before)) err)
                    (stream-car s)
                    (iter (stream-car s) (stream-cdr s)))]))
  (if (stream-null? s) #f
      (iter (stream-car s) (stream-cdr s))))
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<sqrt-stream>>
;<<stream-limit>>
(define (sqrt x tolarance)
  (stream-limit (sqrt-stream x) tolarance))

(sqrt 2 0.00001)
#+end_src

#+RESULTS:
: 1.4142135623746899

*** 3.65

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<series>>
(define positive-negative (cons-stream 1 (scale-stream positive-negative -1)))

(define ln2-series
  (mul-streams (stream-map (lambda (x) (/ 1 x)) integers)
               positive-negative))
(define ln2-stream (partial-sums ln2-series))

;<<euler-transform>>
;<<accelerated-sequence>>
(stream-take (stream-inexact ln2-stream) 10)
(stream-take (stream-inexact (accelerated-sequence euler-transform ln2-stream)) 8)
#+end_src

#+RESULTS:
: (1.0 0.5 0.8333333333333334 0.5833333333333334 0.7833333333333333 0.6166666666666667 0.7595238095238095 0.6345238095238095 0.7456349206349207 0.6456349206349207)
: (1.0 0.7 0.6932773109243697 0.6931488693329254 0.6931471960735491 0.6931471806635636 0.6931471805604039 0.6931471805599444)

It converges slow.

*** exp

#+begin_src racket :results none :noweb-ref stream
(define (interleave s1 s2)
  (if (stream-null? s1) s2
      (cons-stream (stream-car s1)
                   (interleave s2 (stream-cdr s1)))))
#+end_src

#+NAME: pairs
#+begin_src racket :results none :noweb-ref pair
(define (pairs s t)
  (cons-stream
   (list (stream-car s) (stream-car t))
   (interleave
    (stream-map (lambda (x) (list (stream-car s) x)) (stream-cdr t))
    (pairs (stream-cdr s) (stream-cdr t)))))
#+end_src

*** 3.66

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<pairs>>
(stream-take (pairs integers integers) 198)
#+end_src

#+RESULTS:
: ((1 1) (1 2) (2 2) (1 3) (2 3) (1 4) (3 3) (1 5) (2 4) (1 6) (3 4) (1 7) (2 5) (1 8) (4 4) (1 9) (2 6) (1 10) (3 5) (1 11) (2 7) (1 12) (4 5) (1 13) (2 8) (1 14) (3 6) (1 15) (2 9) (1 16) (5 5) (1 17) (2 10) (1 18) (3 7) (1 19) (2 11) (1 20) (4 6) (1 21) (2 12) (1 22) (3 8) (1 23) (2 13) (1 24) (5 6) (1 25) (2 14) (1 26) (3 9) (1 27) (2 15) (1 28) (4 7) (1 29) (2 16) (1 30) (3 10) (1 31) (2 17) (1 32) (6 6) (1 33) (2 18) (1 34) (3 11) (1 35) (2 19) (1 36) (4 8) (1 37) (2 20) (1 38) (3 12) (1 39) (2 21) (1 40) (5 7) (1 41) (2 22) (1 42) (3 13) (1 43) (2 23) (1 44) (4 9) (1 45) (2 24) (1 46) (3 14) (1 47) (2 25) (1 48) (6 7) (1 49) (2 26) (1 50) (3 15) (1 51) (2 27) (1 52) (4 10) (1 53) (2 28) (1 54) (3 16) (1 55) (2 29) (1 56) (5 8) (1 57) (2 30) (1 58) (3 17) (1 59) (2 31) (1 60) (4 11) (1 61) (2 32) (1 62) (3 18) (1 63) (2 33) (1 64) (7 7) (1 65) (2 34) (1 66) (3 19) (1 67) (2 35) (1 68) (4 12) (1 69) (2 36) (1 70) (3 20) (1 71) (2 37) (1 72) (5 9) (1 73) (2 38) (1 74) (3 21) (1 75) (2 39) (1 76) (4 13) (1 77) (2 40) (1 78) (3 22) (1 79) (2 41) (1 80) (6 8) (1 81) (2 42) (1 82) (3 23) (1 83) (2 43) (1 84) (4 14) (1 85) (2 44) (1 86) (3 24) (1 87) (2 45) (1 88) (5 10) (1 89) (2 46) (1 90) (3 25) (1 91) (2 47) (1 92) (4 15) (1 93) (2 48) (1 94) (3 26) (1 95) (2 49) (1 96) (7 8) (1 97) (2 50) (1 98) (3 27) (1 99) (2 51) (1 100))

This version of `pair` tries to take from row first, although the order of taking make little difference. The first row have more chances to be taken since the function call stack is not deep so the chances to be taken is not `dilute` by deep function calls.

By the implementation of `interleave` I know that the `dilute` rate is 50%. Staring from the stream picked out the first pair, for each 16 pairs are taken in the 1st row(out of choosing 32 pairs), the pairs in the 2nd row are taken by 8 times, and 4 pairs in the 3rd row are taken.

Thus the `(1, 100)` is the (100-1)*2=198-th pair in the pair stream.

The `(100, 100)` is the first pair of the 100th row. To take this pair, 2 pairs in the 99th row are taken, with 4 pairs in the 98 row, ... They are $2^{100} - 2$ before this pair is choosed. This is about $10^{16}$.

*** 3.67

To combine all pairs in the table:

|----------+-----------------------|
| (S0, T0) | (S0, T1) (S0, T2) ... |
|----------+-----------------------|
| (S1, T0) | (S1, T1) (S1, T2) ... |
| (S2, T0) | (S2, T1) (S2, T2) ... |
| ...      | ...      ...          |
|----------+-----------------------|

I should regard them as four parts.

#+NAME: pairs-swap
#+begin_src racket :results none
(define (pairs s t)
  (cons-stream
   (list (stream-car s) (stream-car t))
   (interleave (stream-map (lambda (x) (list (stream-car s) x)) (stream-cdr t))
               (interleave (stream-map (lambda (x) (list x (stream-car t))) (stream-cdr s))
                           (pairs (stream-cdr s) (stream-cdr t))))))
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<pairs-swap>>>
(stream-take (pairs integers integers) 10)
#+end_src

#+RESULTS:
: #<procedure:>>
: ((1 1) (1 2) (2 1) (1 3) (2 2) (1 4) (3 1) (1 5) (2 3) (1 6))

*** 3.68

The below codes doesn't use `cons-stream`, so is not lazy. So it would executes to endless recursion.

#+begin_src racket :noweb yes :results output
;<<stream>>
(define (pairs s t)
  (interleave
   (stream-map (lambda (x) (list (stream-car s) x)) t)
   (pairs (stream-cdr s) (stream-cdr t))))

;; (pairs integers integers)
#+end_src

*** 3.69

#+NAME: triples
#+begin_src racket :noweb-ref pair
(define (triples s t r)
  (let ([ps (pairs t r)])
      (cons-stream
       (cons (stream-car s) (stream-car ps))
       (interleave (stream-map (lambda (pair) (cons (stream-car s) pair))
                               ps)
                   (triples (stream-cdr s) (stream-cdr t) (stream-cdr r))))))
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<pair>>
;<<square>>
(define triple-integers
  (triples integers integers integers))

(define pythagorean-triple
  (stream-filter (lambda (triple) (= (+ (square (car triple))
                                         (square (cadr triple)))
                                      (square (caddr triple))))
                 triple-integers))

(stream-take triple-integers 20)
(stream-take pythagorean-triple 5)
#+end_src

#+RESULTS:
: ((1 1 1) (1 1 1) (2 2 2) (1 1 2) (2 2 2) (1 2 2) (3 3 3) (1 1 3) (2 2 3) (1 2 3) (3 3 3) (1 1 4) (2 3 3) (1 3 3) (4 4 4) (1 1 5) (2 2 4) (1 2 4) (3 3 4) (1 1 6))
: ((3 4 5) (6 8 10) (5 12 13) (9 12 15) (8 15 17))

*** 3.70

Notice that the `merge-by` will filter out the element weigh the same value.
The `weight` should be implemented carefully to distinguish `(1 3)` with `(2 2)` when the sum of elements is used in weight.

Here I use a trick to descript difference of the pairs of the same weight in the fraction part of a number, and make use of the feature that the `>`, `<`, `=` can compare integers and real numbers, and scheme implements the rational number.
The key to do this is to compress two numbers in the pair into one dimention, and put the value of the dimention into the original weights. This reminds me about a story about Hilbert's hotel...

#+begin_src racket :results none :noweb-ref pair
(define (merge-by weight s1 s2)
  (cond [(stream-null? s1) s2]
        [(stream-null? s2) s1]
        [else
         (let ([e1 (stream-car s1)] [e2 (stream-car s2)])
           (let ([w1 (weight e1)] [w2 (weight e2)])
             (cond
               [(= w1 w2)
                (cons-stream e1 (merge-by weight (stream-cdr s1)
                                          (stream-cdr s2)))]
               [(< w1 w2)
                (cons-stream e1 (merge-by weight (stream-cdr s1) s2))]
               [else ; >
                (cons-stream e2 (merge-by weight s1 (stream-cdr s2)))])))]))
(define (weighted-pairs w s1 s2)
  (cons-stream
   (list (stream-car s1) (stream-car s2))
   (merge-by w
             (stream-map
              (lambda (x) (list (stream-car s1) x))
              (stream-cdr s2))
             (weighted-pairs w (stream-cdr s1) (stream-cdr s2)))))

(define (weight-order-same-weight-pair w)
  (define (combine-to-fraction x y)
    (define (digits n)
      (define (iter i acc)
        (if (zero? i) acc
            (iter (quotient i 10) (cons (remainder i 10) acc))))
      (iter n '()))
    (define (interleave-digits a b)
      (cond [(and (null? a) (null? b)) '()]
            [(null? a) (interleave-digits (list 0) b)]
            [(null? b) (interleave-digits a (list 0))]
            [else (cons (car a)
                        (cons (car b)
                              (interleave-digits (cdr a) (cdr b))))]))
    (define (digits->fraction ds)
      (define (iter rests f dividend)
        (if (null? rests) f
            (iter (cdr rests) (+ f (/ (car rests) dividend)) (* 10 dividend))))
      (iter ds 0 10))
    (digits->fraction (interleave-digits (digits x) (digits y))))
  (lambda (pair)
    (let ([weight (w pair)])
      (+ (combine-to-fraction (car pair) (cadr pair))
         weight))))
#+end_src

(Since I learned about the `define-syntax` by implementing the `cons-stream`, I know how to make use of the macro functionalities... Let me try parial argument application!!!)

For $z = 2x + 3y + 5xy$, it's hard to image there's a mountain that the line of it's ridge leans to y axis more... So I add the value of the pair in the test codes.

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<pair>>
;<<higher-order>>
(define merge (partial merge-by identity))

(define order-by-sum
  (weighted-pairs
   (weight-order-same-weight-pair (lambda (pair) (apply + pair)))
   integers integers))
(define one-and-235
  (cons-stream 1
               (merge (stream-map (partial * 2) one-and-235)
                      (merge (stream-map (partial * 3) one-and-235)
                             (stream-map (partial * 5) one-and-235)))))
; it's good that the names can have prefixes of numbers.
(define (2i-3j-5ij pair)
  (let ([i (car pair)] [j (cadr pair)])
    (+ (* 2 i) (* 3 j) (* 5 i j))))
(define order-by-2i-3j-5ij
  (let ([2-3-5 (stream-cdr one-and-235)])
    (weighted-pairs (weight-order-same-weight-pair 2i-3j-5ij)
                    2-3-5 2-3-5)))

(stream-take one-and-235 10)

(stream-take order-by-sum 10)
(stream-take
 (stream-map (lambda (pair) (cons (2i-3j-5ij pair) pair))
             order-by-2i-3j-5ij)
 20)
(stream-take
 (stream-map
  (lambda (pair)
    (cons (exact->inexact ((weight-order-same-weight-pair 2i-3j-5ij) pair)) pair))
             order-by-2i-3j-5ij)
 20)
#+end_src

#+RESULTS:
: (1 2 3 4 5 6 8 9 10 12)
: ((1 1) (1 2) (1 3) (2 2) (1 4) (2 3) (1 5) (2 4) (3 3) (1 6))
: ((30 2 2) (43 2 3) (56 2 4) (60 3 3) (69 2 5) (78 3 4) (82 2 6) (96 3 5) (100 4 4) (108 2 8) (114 3 6) (121 2 9) (123 4 5) (134 2 10) (146 4 6) (150 3 8) (150 5 5) (160 2 12) (168 3 9) (178 5 6))
: ((30.22 2 2) (43.23 2 3) (56.24 2 4) (60.33 3 3) (69.25 2 5) (78.34 3 4) (82.26 2 6) (96.35 3 5) (100.44 4 4) (108.28 2 8) (114.36 3 6) (121.29 2 9) (123.45 4 5) (134.21 2 10) (146.46 4 6) (150.38 3 8) (150.55 5 5) (160.2102 2 12) (168.39 3 9) (178.56 5 6))

Emm... There's another way to order the same weight pairs, so that the pairs of with the same weight is ordered by the first/last number. In this implementation, just change where to pad zeros to generate the digits.

*** 3.71

#+NAME: 3-71
#+begin_src racket :noweb yes :results none
;<<stream>>
;<<pair>>
(define (cube x) (* x x x))
(define (sum-cubes pair)
  (+ (cube (car pair)) (cube (cadr pair))))

(define ramanujan-number-pairs
  (let ([s (stream-map (lambda (pair) (cons (sum-cubes pair) pair))
                       (weighted-pairs (weight-order-same-weight-pair
                                        sum-cubes)
                                       integers integers))])
    (define (combine-number-pairs p1 p2)
      (cons (car p1) (cons (cdr p1) (cons (cdr p2) '()))))
    (define (next before-pair ss)
      (if (= (car before-pair) (car (stream-car ss)))
          (cons-stream (combine-number-pairs before-pair (stream-car ss))
                       (next (stream-car (stream-cdr ss))
                             (stream-cdr (stream-cdr ss))))
          (next (stream-car ss) (stream-cdr ss))))
    (next (stream-car s) (stream-cdr s))))
(define ramanujan-numbers
  (stream-map car ramanujan-number-pairs))
#+end_src

#+begin_src racket :noweb yes :results output
;<<3-71>>
(stream-take ramanujan-number-pairs 10)
(stream-take ramanujan-numbers 10)
#+end_src

#+RESULTS:
: ((1729 (1 12) (9 10)) (4104 (2 16) (9 15)) (13832 (18 20) (2 24)) (20683 (10 27) (19 24)) (32832 (18 30) (4 32)) (39312 (15 33) (2 34)) (40033 (16 33) (9 34)) (46683 (27 30) (3 36)) (64232 (17 39) (26 36)) (65728 (12 40) (31 33)))
: (1729 4104 13832 20683 32832 39312 40033 46683 64232 65728)

*** 3.72

#+begin_src racket :noweb yes :results output
;<<3-71>>
;<<higher-order>>
(define (stream-cadr ss) (stream-car (stream-cdr ss)))
(define (stream-cddr ss) (stream-cdr (stream-cdr ss)))

(define ramanujan-3-number-pairs
  (let ([s (stream-map (lambda (pair) (cons (sum-cubes pair) pair))
                       (weighted-pairs (weight-order-same-weight-pair
                                        sum-cubes)
                                       integers integers))])
    (define (combine-number-pairs p1 p2 p3)
      (cons (car p1)
            (cons (cdr p1) (cons (cdr p2) (cons (cdr p3) '())))))
    (define (next p-2 p-1 ss)
      (if (= (car p-2) (car (stream-car ss)))
          (cons-stream (combine-number-pairs p-2 p-1 (stream-car ss))
                       (next (stream-cadr ss)
                             (stream-car (stream-cddr ss))
                             (stream-cdr (stream-cddr ss))))
          (next p-1 (stream-car ss) (stream-cdr ss))))
    (next (stream-car s) (stream-cadr s) (stream-cddr s))))

(stream-take ramanujan-3-number-pairs 5) ; this line costs me 2 mins...
#+end_src

#+RESULTS:
: ((87539319 (167 436) (228 423) (255 414)) (119824488 (11 493) (346 428) (90 492)) (143604279 (111 522) (359 460) (408 423)) (175959000 (198 552) (315 525) (70 560)) (327763000 (300 670) (339 661) (510 580)))

*** exp: streams as signals

#+begin_src racket :noweb-ref signals
(define (integral integrand initial-value dt)
  (define int
    (cons-stream initial-value
                 (add-streams (scale-stream integrand dt)
                              int)))
  int)
#+end_src

*** 3.73

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<signals>>
(define (RC r c timestep)
  (define (v is v0)
    (add-streams
     (scale-stream is r)
     (integral (scale-stream is (/ 1 c)) v0 timestep)))
  v)
(define RC1 (RC 5 1 0.5))

(stream-take (RC1 integers 5) 10)
#+end_src

#+RESULTS:
: (10 15.5 21.5 28.0 35.0 42.5 50.5 59.0 68.0 77.5)

*** 3.74

#+NAME: 3-74
#+begin_src racket :results none
(define (sgn x)
  (cond [(> x 0) 1] [(< x 0) -1] [else 0]))

(define (sign-change-detector a b)
  (if (negative? (* a b)) (sgn (- a b)) 0))
(define (zero-crossings-from sense-data)
  (define zero-crossings
    (stream-map sign-change-detector sense-data (stream-cdr sense-data)))
  zero-crossings)
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<3-74>>
(define positive-negative (cons-stream 1 (stream-map (lambda (x) (* -1 x)) positive-negative)))

(stream-take positive-negative 10)
(stream-take (zero-crossings-from positive-negative) 10)
;<<series>>
(stream-take sine-series 10)
(stream-take (zero-crossings-from sine-series) 10)
#+end_src

#+RESULTS:
: (1 -1 1 -1 1 -1 1 -1 1 -1)
: (1 -1 1 -1 1 -1 1 -1 1 -1)
: (0 1 0 -1/6 0 1/120 0 -1/5040 0 1/362880)
: (0 0 0 0 0 0 0 0 0 0)

If there's a zip procedure to combine to according elements in streams, it's no need for a generailized version of `stream-map`.

#+NAME: stream-zip2
#+begin_src racket :results none
(define (stream-zip2 f ass bss)
  (cond [(and (stream-null? ass) (stream-null? bss)) the-empty-stream]
        [(or (stream-null? ass) (stream-null? bss)) the-empty-stream]
        [else
         (cons-stream (f (stream-car ass) (stream-car bss))
                      (stream-zip2 f (stream-cdr ass) (stream-cdr bss)))]))
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<stream-zip2>>
(stream-take (stream-zip2 list integers integers) 10)
#+end_src

#+RESULTS:
: ((1 1) (2 2) (3 3) (4 4) (5 5) (6 6) (7 7) (8 8) (9 9) (10 10))

*** 3.75

Change this:

#+begin_src racket :results none
(define (make-zero-crossings input-stream last-value)
  (let ((avpt (/ (+ (stream-car input-stream) last-value) 2)))
    (cons-stream (sign-change-detector avpt last-value)
                 (make-zero-crossings (stream-cdr input-stream)
                                      avpt))))
#+end_src

To:

#+begin_src racket :noweb yes :results output
(define (make-zero-crossings input-stream last-value last-avpt)
  (let ((avpt (/ (+ (stream-car input-stream) last-value) 2)))
    (cons-stream (sign-change-detector avpt last-avpt)
                 (make-zero-crossings (stream-cdr input-stream)
                                      (stream-car input-stream)
                                      avpt))))
#+end_src

*** 3.76

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<stream-zip2>>
;<<average>>
;<<3-74>> ; import sign-change-detector
(define (smooth ss)
  (stream-zip2 average ss (stream-cdr ss)))

(define (make-zero-crossings ss)
  (let ([smoothed (smooth ss)])
    (stream-map sign-change-detector smoothed (stream-cdr smoothed))))

;<<series>>
(stream-take sine-series 10)
(stream-take (smooth sine-series) 10)
(stream-take (make-zero-crossings sine-series) 9)
#+end_src

#+RESULTS:
: (0 1 0 -1/6 0 1/120 0 -1/5040 0 1/362880)
: (1/2 1/2 -1/12 -1/12 1/240 1/240 -1/10080 -1/10080 1/725760 1/725760)
: (0 1 0 -1 0 1 0 -1 0)

** Book 3.5.4 Stream and Delayed Evaluation

*** exp: delayed integral

#+NAME: delayed-integral
#+begin_src racket
(define (integral delayed-integrand initial-value dt)
  (define int
    (cons-stream initial-value
                 (let ([integrand (force delayed-integrand)])
                   (add-streams (scale-stream integrand dt)
                                int))))
  int)
#+end_src

To solve $y' = y$ when $y(0) = 1$.

Racket #lang sicp cannot execute this below...

#+NAME: delayed-solve
#+begin_src racket :results none
(define (solve f y0 dt)
  (define y (integral (delay dy) y0 dt))
  (define dy (stream-map f y))
  y)
(stream-ref (solve (lambda (y) y) 1 0.001) 1000)
#+end_src

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<delayed-integral>>
;<<delayed-solve>>
#+end_src

#+RESULTS:
: y: undefined;
:  cannot use before initialization
:   context...:
:    c:\Users\asu\AppData\Local\Temp\org-babel-QiZrUD.rkt:55:0: solve
:    c:\Users\asu\AppData\Local\Temp\org-babel-QiZrUD.rkt:59:0
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-QiZrUD.rkt"

But this is executable.

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<delayed-integral>>
(define (solve f y0 dt)
  (define y (integral (delay (stream-map f y)) y0 dt))
  y)
(stream-ref (solve (lambda (y) y) 1 0.001) 1000)
#+end_src

#+RESULTS:
: 2.716923932235896

**** Racket stream

It seems that the delay in #lang sicp is derived from #lang racket. And there may be other reasons. I am expecting to know why in Book 4.1.6.

I may use racket in next a few exercises.

#+begin_src racket :lang racket :results none :noweb-ref racket-stream
(module stream racket
  (provide (rename-out [stream-cons cons-stream]) the-empty-stream stream-null?
           stream-cdr stream-car
           add-streams scale-stream
           stream-map-expand
           (rename-out [stream-take-list stream-take])
           ones integers)
  (define the-empty-stream empty-stream)
  (define stream-null? stream-empty?)
  (define stream-car stream-first)
  (define (stream-cdr ss) (stream-tail ss 1))

  (define (stream-take-list ss n)
    (stream->list (stream-take ss n)))

  (define (stream-map-expand f . sss)
    (if (stream-empty? (car sss)) empty-stream
        (stream-cons
         (apply f (map stream-first sss))
         (apply stream-map-expand
                (cons f (map stream-cdr sss))))))

  (define (add-streams s1 s2)
    (stream-map-expand + s1 s2))
  (define (scale-stream ss factor)
    (stream-map ((curry *) factor) ss))

  (define ones (stream-cons 1 ones))
  (define integers (stream-cons 1 (add-streams integers ones)))
  )

(require 'stream)
#+end_src

#+begin_src racket :lang racket :noweb yes :results output
;<<racket-stream>>
;<<delayed-integral>>
;<<delayed-solve>>
#+end_src

#+RESULTS:
: 2.716923932235896

*** 3.77

#+begin_src racket :lang racket :noweb yes :results output
;<<racket-stream>>
(define (integral delayed-integrand initial-value dt)
  (cons-stream initial-value
               (let ([integrand (force delayed-integrand)])
                 (if (stream-null? integrand)
                     the-empty-stream
                     (integral (stream-cdr integrand)
                               (+ (* dt (stream-car integrand))
                                  initial-value)
                               dt)))))
;<<delayed-solve>>
#+end_src

#+RESULTS:
: 2.716923932235896

*** 3.78

$y'' = y'$ when $y(0) = 1, y'(0) = 1$. Result is still e $y''=e$.

#+begin_src racket :lang racket :noweb yes :results output
;<<racket-stream>>
;<<delayed-integral>>
(define (solve-2nd a b dt y0 dy0)
  (define y (integral (delay dy) y0 dt))
  (define dy (integral (delay ddy) dy0 dt))
  (define ddy (add-streams (scale-stream dy a)
                           (scale-stream y b)))
  y)

(stream-ref (solve-2nd 1 0 0.001 1 1) 1000)
#+end_src

#+RESULTS:
: 2.716923932235896

*** 3.79

#+begin_src racket :lang racket :noweb yes :results output
;<<racket-stream>>
;<<delayed-integral>>
(define (solve-2nd f dt y0 dy0)
  (define y (integral (delay dy) y0 dt))
  (define dy (integral (delay ddy) dy0 dt))
  (define ddy (f dy y))
  y)

(stream-ref (solve-2nd (lambda (x y) x) 0.001 1 1) 1000)
#+end_src

#+RESULTS:
: 2.716923932235896

*** 3.80

#+begin_src racket :lang racket :noweb yes :results output
;<<racket-stream>>
;<<delayed-integral>>
(define (RLC R L C dt)
  (define (circuit vC0 iL0)
    (define vC (integral (delay dvC) vC0 dt))
    (define iL (integral (delay diL) iL0 dt))
    (define diL (add-streams (scale-stream vC (/ 1 L))
                             (scale-stream iL (- (/ R L)))))
    (define dvC (scale-stream iL (- (/ 1 C))))
    (cons vC iL))
  circuit)

(define circuit-v-i ((RLC 1 1 0.2 0.1) 10 0))
(define circuit-v (car circuit-v-i))
(define circuit-i (cdr circuit-v-i))
(stream-take circuit-i 10)
(stream-take circuit-v 10)
#+end_src

#+RESULTS:
: '(0 1.0 1.9 2.66 3.249 3.6461 3.84104 3.834181 3.6359559 3.2658442599999997)
: '(10 10 9.5 8.55 7.220000000000001 5.5955 3.77245 1.8519299999999999 -0.0651605000000004 -1.8831384500000004)

** Book 3.5.5 Modularity of Functional Programs and Modularity of Objects

*** 3.81

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<higher-order>>
;<<square>>
(define (make-prng seed)
  (define (rand requests)
    (define (next now) ; choose a simple algorithm to generate random number
      (modulo (+ (* 1664525 now) 1013904223) ((compose square square) 256))) ; 2^32
    (define (handle now req)
      (cond [(eq? req 'generate) (next now)]
            [(and (list? req) (not (null? req))
                  (eq? (car req) 'reset)) (cadr req)]
            [else (error "Unknown operation -- MAKE-PRNG")]))
    (define ss
      (cons-stream seed (stream-map handle ss requests)))
    ss)
  rand)

(define prng (make-prng 7))
;<<series>>
(define requests
  (cons-stream 'generate
               (stream-map (lambda (x) (if (zero? x) 'generate
                                           (list 'reset 65535)))
                           sine-series)))
(stream-take requests 10)
(stream-take (prng requests) 10)
#+end_src

#+RESULTS:
: (generate generate (reset 65535) generate (reset 65535) generate (reset 65535) generate (reset 65535) generate)
: (7 1025555898 3923423697 65535 2724367698 65535 2724367698 65535 2724367698 65535)

*** 3.82

#+begin_src racket :noweb yes :results output
;<<stream>>
;<<square>>
;<<higher-order>>
(define (monte-carlo experiment)
  (define success-times
    (partial-sums (stream-map (lambda _ (if (experiment) 1 0)) ones)))
  (stream-map / success-times integers))

(define (random-f int . precisions)
  (define default-precision 1000000)
  (define (random-by-precision precision)
    (* int (/ (random precision) precision)))
  (if (null? precisions)
      (random-by-precision default-precision)
      (map random-by-precision precisions)))

(define (random-in-range low high)
  (let ([range (- high low)])
    (+ low (random-f range))))

(define (estimate-integral p x1 x2 y1 y2)
  (define (random-point x1 x2 y1 y2)
    (cond [(> x1 x2) (random-point x2 x1 y1 y2)]
          [(> y1 y2) (random-point x1 x2 y2 y1)]
          [else (list (random-in-range x1 x2)
                      (random-in-range y1 y2))]))
  (define (experiment)
    (apply p (random-point x1 x2 y1 y2)))
  (monte-carlo experiment))

(define (estimate-pi)
  (define (p x y)
    (<= (+ (square (- x 5)) (square (- y 7)))
        (square 3)))
  ; (πr^2) / (2r * 2r) = π / 4
  (let ([quarter-of-pi (estimate-integral p 2 8 4 10)])
    (stream-map (compose exact->inexact (partial * 4)) quarter-of-pi)))

(stream-take (estimate-pi) 20)
(stream-ref (estimate-pi) 10000)
#+end_src

#+RESULTS:
: (4.0 4.0 4.0 3.0 3.2 3.3333333333333335 3.4285714285714284 3.0 3.111111111111111 3.2 3.272727272727273 3.3333333333333335 3.3846153846153846 3.4285714285714284 3.466666666666667 3.5 3.5294117647058822 3.5555555555555554 3.5789473684210527 3.4)
: 3.136086391360864

* Helper procedures

#+NAME: higher-order
#+begin_src racket :results none
(define (always res) (lambda _args res))

(define (compose f g)
  (lambda (x) (f (g x))))

(define (repeat n func)
  (define (iter n acc)
    (if (= n 1)
        (lambda args (apply acc args))
        (iter (- n 1) (lambda args
                        (cons (apply func args)
                              (apply acc args))))))
  (if (<= n 0) identity
      (iter n (lambda args (list (apply func args))))))

(define (partial f . args1)
  (lambda args2 (apply f (append args1 args2))))
#+end_src

Test the higher-order functions.
#+begin_src racket :noweb yes :results output
;<<higher-order>>
(define inc (partial + 1))
(list (inc 2)
      ((partial * 2) 7))

;<<square>>
((compose square square) 3)
#+end_src

#+RESULTS:
: (3 14)
: 81

#+NAME: fold
#+begin_src racket
(define (fold-left f init lst)
  (if (null? lst) init
      (fold-left f (f init (car lst)) (cdr lst))))

(define (fold-right f init lst)
  (if (null? lst) init
      (f (car lst) (fold-right f init (cdr lst)))))
#+end_src

#+NAME: take
#+begin_src racket
(define (take n lst)
  (if (= n 0) nil
      (cons (car lst) (take (- n 1) (cdr lst)))))

(define (take-when f lst)
  (cond [(null? lst) nil]
        [(f (car lst))
         (cons (car lst) (take-when f (cdr lst)))]
        [else nil]))
#+end_src

#+NAME: square
#+begin_src racket :results none :noweb-ref sicp
(define (square x) (* x x))
#+end_src

#+NAME: average
#+begin_src racket :results none :noweb-ref sicp
(define (average a b)
  (/ (+ a b) 2))
#+end_src

#+NAME: displayln
#+begin_src racket :results none :noweb-ref sicp
(define (displayln x) (display x) (newline))
#+end_src

* COMMENT Local Variables
# Local Variables:
# org-babel-noweb-wrap-start: ";<<"
# org-babel-noweb-wrap-end: ">>"
# End:
