#+title: Exercise
#+property: header-args:racket :lang sicp :results output :noweb yes

Chapter 4: Metalinguistic Abstraction

* 4.1 The Metacircular Evaluator

** 4.1.1 The Core of the Evaluator

*** exp

#+begin_src racket :noweb-ref eval-core-exp
(define (eval expr env)
  (cond
    [(self-evaluating? expr) expr]
    [(variable? expr) (lookup-variable-value expr env)]
    [(quoted? expr) (text-of-quotation expr)]
    [(assignment? expr) (eval-assignment expr env)]
    [(definition? expr) (eval-definition expr env)]
    [(lambda? expr)
     (make-procedure (lambda-parameters expr)
                     (scan-out-defines (lambda-body expr)) ; Exercise 4.16
                     env)]
    [(begin? expr)
     (eval-sequence (begin-actions expr) env)]
    [(if? expr) (eval-if expr env)]
    [(cond? expr) (eval (cond->if expr) env)]
    [(and? expr) (eval-and expr env)] ; and & or: Exercise 4.4
    [(or? expr) (eval-or expr env)]
    [(let? expr) (eval (let->combination expr) env)] ; let: Exercise 4.6
    [(let*? expr) (eval (let*->nested-lets expr) env)] ; let*: Exercise 4.7
    [(letrec? expr) (eval (letrec->let expr) env)] ; letrec: Exercise 4.20
    [(application? expr)
     (my-apply (eval (operator expr) env)
               (list-of-values (operands expr) env))]
    [else (error "Unknown expression type -- EVAL" expr)]))

(define (my-apply procedure arguments)
  (cond
    [(primitive-procedure? procedure)
     (apply-primitive-procedure procedure arguments)]
    [(compound-procedure? procedure)
     (eval-sequence
      (procedure-body procedure)
      (extend-environment
       (procedure-parameters procedure)
       arguments
       (procedure-environment procedure)))]
    [else (error "Unknown procedure type -- APPLY" (list procedure arguments))]))
#+end_src

#+begin_src racket :noweb-ref eval-core-exp
(define (list-of-values exprs env)
  (if (no-operands? exprs)
      '()
      (cons (eval (first-operand exprs) env)
            (list-of-values (rest-operands exprs) env))))

(define (eval-if expr env)
  (if (true? (eval (if-predicate expr) env))
      (eval (if-consequent expr) env)
      (eval (if-alternative expr) env)))

(define (eval-sequence exprs env)
  (cond [(last-expr? exprs) (eval (first-expr exprs) env)]
        [else (eval (first-expr exprs) env)
              (eval-sequence (rest-exprs exprs) env)]))

(define (eval-assignment expr env)
  (set-variable-value! (assignment-variable expr)
                 (eval (assignment-value expr) env)
                 env)
  'ok)

(define (eval-definition expr env)
  (define-variable! (definition-variable expr)
                    (eval (definition-value expr) env)
                    env)
  'ok)
#+end_src

*** 4.1

Comparing to the example of `list-of-values`, this version of `list-of-values` evals from left to right(first to end):

#+begin_src racket
(define (list-of-values exprs env)
  (if (no-operands? exprs)
      '()
      (let ([first-value (eval (first-operand exprs) env)])
        (cons first-value
              (list-of-values (rest-exprs exprs) env)))))
#+end_src

And this version evals from right to left:

#+begin_src racket
(define (list-of-values exprs env)
  (if (no-operands? exprs)
      '()
      (let ([rest-values (list-of-values (rest-exprs exprs) env)])
        (cons (eval (first-operand exprs) env)
              rest-values))))
#+end_src

*** exp

#+begin_src racket :noweb-ref eval-core-exp
(define (self-evaluating? expr)
  (cond [(number? expr) true]
        [(string? expr) true]
        [(boolean? expr) true]
        [else false]))

(define (variable? expr) (symbol? expr))

;; quote
(define (quoted? expr)
  (tagged-list? expr 'quote))
(define (text-of-quotation expr) (cadr expr))

(define (tagged-list? expr tag)
  (if (pair? expr)
      (eq? (car expr) tag)
      false))

;; assignment
(define (make-assignment var val)
  (list 'set! var val))
(define (assignment? expr)
  (tagged-list? expr 'set!))
(define (assignment-variable expr) (cadr expr))
(define (assignment-value expr) (caddr expr))

;; definition
(define (definition? expr)
  (tagged-list? expr 'define))
(define (definition-variable expr)
  (if (symbol? (cadr expr))
      (cadr expr)           ; (define <var> <value>)
      (caadr expr)))        ; (define (function_name arg...) <value>)
(define (definition-value expr)
  (if (symbol? (cadr expr))
      (caddr expr)
      (make-lambda (cdadr expr)
                   (cddr expr))))
; lambda
(define (make-lambda parameters body)
  (cons 'lambda (cons parameters body)))
(define (lambda? expr) (tagged-list? expr 'lambda))
(define lambda-parameters cadr)
(define lambda-body cddr)

;; if
(define (make-if predicate consequent alternative)
  (list 'if predicate consequent alternative))
(define (if? expr) (tagged-list? expr 'if))
(define if-predicate cadr)
(define if-consequent caddr)
(define (if-alternative expr)
  (if (not (null? (cdddr expr)))
      (cadddr expr)
      false))

;; begin
(define (begin? expr) (tagged-list? expr 'begin))
(define (begin-actions expr) (cdr expr))
(define (last-expr? seq) (null? (cdr seq)))
(define first-expr car)
(define rest-exprs cdr)

(define (sequence->expr seq)
  (cond [(null? seq) seq]
        [(last-expr? seq) (first-expr seq)]
        [else (make-begin seq)]))
(define (make-begin seq) (cons 'begin seq))

;; apply
(define (application? expr) (pair? expr))
(define operator car)
(define operands cdr)
(define (no-operands? ops) (null? ops))
(define first-operand car)
(define rest-operands cdr)

;; cond
(define (cond? expr) (tagged-list? expr 'cond))
(define cond-clauses cdr)
(define (cond-predicate clause) (car clause))
(define (cond-actions clause) (cdr clause))
(define (cond-else-clause? clause) (eq? (cond-predicate clause) 'else))

(define (cond->if expr)
  (expand-clauses (cond-clauses expr)))

(define (expand-clauses clauses)
  (if (null? clauses)
      false              ; clause else
      (let ([first (car clauses)] [rest (cdr clauses)])
        (if (cond-else-clause? first)
            (if (null? rest)
                (sequence->expr (cond-actions first))
                (error "ELSE clause is not last -- COND->IF" clauses))
            (make-if (cond-predicate first)
                     (sequence->expr (cond-actions first))
                     (expand-clauses rest))))))
#+end_src

** 4.1.2 Representing Expressions

*** 4.2

a) The `application?` clause in `cond` clauses in `eval` should be a last clause before `else` clause. This is because the `application?` is implemented by a simple `pair?` and recognise almost all expression as application other than the `if`s, `define`s and so on.
b) Known the reason, I know how to improve, adding a tag to the application expression:

   #+begin_src racket
(define (application? expr) (tagged-list? expr 'call))
(define operator cadr)
(define operands cddr)
   #+end_src

*** 4.3 data directed eval

#+begin_src BNF
<expr> ::= <value> | <statement>

<value> ::= <literal> | <variable>
<literal> ::= <number> | <string>
<variable> ::= <literal> | <procedure>
<procedure> ::= <parameters><body>
<body> ::= <sequence>
<sequence> ::= "(" <expr> | <expr> <expr> ")"

<statement> ::= <quoted> | <lambda> | <definition> | <assignment> | <if> | <cond> | <begin> | <apply>
<quoted> ::= "(" <quote-identifier><expr> ")"
<lambda> ::= "(" <lambda-identifier><procedure> ")"
...
#+end_src

|--------------------+---------+-----+-------+--------+-------+---------+-------+-------|
| Op\Expr            | literal | var | quote | assign | λ/def | if/cond | apply | begin |
| eval               | yes     | yes | yes   | yes    | yes   | yes     | yes   | yes   |
| self type identify | yes     | yes | yes   | yes    | yes   | yes     | yes   | yes   |
| ...                |         |     |       |        |       |         |       |       |
|--------------------+---------+-----+-------+--------+-------+---------+-------+-------|

#+begin_src racket :results none
(define (tag? x) (symbol? x))
(define (tagged-list-tag lst)
  (car lst))

(define (literal-pkg)
  (define (literal? x)
    (cond [(number? x) true]
          [(string? x) true]
          [else false]))
  (define (eval x env) x)

  (put 'literal? '(expr) literal?)
  (put 'eval '(literal env) eval)
  'done)

(define (variable-pkg)
  (define variable? symbol?)
  (define (eval x env)
    (lookup-variable-value x env))

  (put 'variable? '(expr) variable?)
  (put 'eval '(variable env) eval)
  'done)

(define (quote-pkg)
  (define (quoted? x) (tagged-list? x 'quote))
  (define (eval x env)
    (text-of-quotation x))
  (define (text-of-quotation x)
    (cadr x))

  (put 'quoted? '(expr) quoted?)
  (put 'eval '(quote env) eval)
  'done)

(define (assignment-pkg)
  (define (assignment? x) (tagged-list? x 'set!))
  (define (eval-assignment x env)
    (define-variable! (definition-variable expr)
      (eval (assignment-value expr) env)
      env))
  (define assignment-variable cadr)
  (define assignment-value caddr)

  (put 'assignment? '(expr) assignment?)
  (put 'eval '(assignment env) eval-assignment)
  'done)

(define (lambda-definition-pkg)
  (define (lambda? x) (tagged-list? x 'lambda))
  (define (definition? x) (tagged-list? x 'define))

  (define (make-lambda parameters body)
    (cons 'lambda (cons parameters body)))
  (define lambda-parameters cadr)
  (define lambda-body cddr)

  (define (difinition-varible expr)
    (if (symbol? (cadr expr))
        (cadr expr)
        (caadr expr)))
  (define (difinition-value expr)
    (if (symbol? (cadr expr))
        (caddr expr)
        (make-lambda (cdadr expr)
                     (cddr expr))))

  (define (eval-lambda expr env)
    (make-procedure (lambda-parameters expr)
                    (lambda-body expr)
                    env))
  (define (eval-definition expr env)
    (define-variable! (definition-variable expr)
      (eval (definition-value expr) env)
      env))

  (put 'lambda? '(expr) lambda?)
  (put 'definition? '(expr) definition?)
  (put 'eval '(lambda env) eval-lambda)
  (put 'eval '(definition env) eval-definition)
  'done)

(define (if-cond-pkg)
  (define (if? expr) (tagged-list? expr 'if))
  (define (make-if predicate consequent alternative)
    (list 'if predicate consequent alternative))
  (define if-predicate cadr)
  (define if-consequent caddr)
  (define (if-alternative expr)
    (if (null? (cdddr expr)) false
        (cadddr expr)))

  (define (eval-if expr env)
    (if (true? (if-predicate expr))
        (eval (if-consequent expr) env)
        (eval (if-alternative expr) env)))

  (define (cond? expr) (tagged-list? expr 'cond))
  (define cond-clauses cdr)
  (define (cond-predicate clause) (car clause))
  (define (cond-actions clause) (cdr clause))
  (define (cond-else-clause? clause) (eq? (cond-predicate clause) 'else))
  (define (cond->if expr)
    (expand-clauses (cond-clauses expr)))
  (define (expand-clauses clauses)
    (if (null? clauses)
        false
        (let ([first (car clauses)] [rest (cdr clauses)])
          (if (cond-else-clause? first)
              (if (null? rest)
                  (sequence->expr (cond-actions first))
                  (error "ELSE clause is not last -- COND->IF"))
              (make-if (cond-predicate first)
                       (sequence->expr (cond-actions first))
                       (expand-clauses rest))))))

  (define (eval-cond expr env)
    (eval (cond->if expr env)))

  (put 'if? '(expr) if?)
  (put 'cond? '(expr) cond?)
  (put 'eval '(if env) eval-if)
  (put 'eval '(cond env) eval-cond)
  'done)

(define (apply-pkg)
  (define (application? expr) (pair? expr))
  (define operator car)
  (define operands cdr)
  (define (no-operands? ops) (null? ops))
  (define first-operand car)
  (define rest-operands cdr)
  (define (list-of-values exprs env)
    (if (no-operands? exprs)
        '()
        (cons (eval (first-operand exprs) env)
              (list-of-values (rest-operands exprs) env))))

  (define (eval-application expr env)
    (apply (eval (operator expr) env)
           (list-of-values (operands expr) env)))

  (put 'application? '(expr) application?)
  (put 'eval '(application env) eval-application)
  'done)

(define (begin-pkg)
  (define (make-begin seq) (cons 'begin seq))
  (define (begin? expr) (tagged-list? expr 'begin))
  (define (begin-actions expr) (cdr expr))
  (define (eval-begin expr env)
    (eval-sequence (begin-actions expr) env))

  (define (last-expr? seq) (null? (cdr seq)))
  (define first-expr car)
  (define rest-exprs cdr)
  (define (sequence->expr seq)
    (cond [(null? seq) seq]
          [(last-expr? seq) (first-expr seq)]
          [else (make-begin seq)]))
  (define (eval-sequence exprs env)
    (cond [(last-expr? exprs) (eval (first-expr exprs) env)]
          [else (eval (first-expr exprs) env)
                (eval-sequence (rest-exprs exprs) env)]))

  (put 'begin? '(expr) begin?)
  (put 'sequence->expr '(sequence) sequence->expr)
  (put 'eval '(begin env) eval-begin)
  (put 'eval '(sequence env) eval-sequence)
  'done)

(define (sequence->expr seq) (get 'sequence->expr '(sequence)))

(define (lookup-variable-value var env)
  ??)

(define literal? (get 'literal? '(expr)))
(define variable? (get 'variable?) '(expr))
(define (type-of-value value)
  (cond [(literal? value) 'literal]
        [(variable? value) 'variable]
        [else false]))
(define (type-of-expr expr)
  (let ([value-type (type-of-value expr)])
    (if (value-type) value-type
        (let ([expr-tag (tagged-list-tag expr)])
          (if (tag? expr-tag) expr-tag
              'application)))))
(define (eval expr env)
  ((get 'eval (list (type-of-expr expr) 'env)) expr env))
#+end_src

It seems I did too much.

The implementation of `eval` is quite alike to the `deriv` in Exercise 2.73.

*** 4.4 and & or

#+begin_src BNF
<sequence> ::= "(" <sequence-exprs> ")"
<sequence-exprs> ::= <expr> | <expr> <sequence-exprs>

<and> ::= "(" <and-identifier> <sequence> ")"
<or> ::= "(" <or-identifier> <sequence> ")"
#+end_src

Wait, until now the Book haven't told me any implementation or interface of the booleans...

#+begin_src racket :noweb-ref eval-core-exp
(define (and? expr) (tagged-list? expr 'and))
(define (eval-and expr env)
  (define (iter seq)
    (let ([curr (eval (first-expr seq) env)])
      (if (not curr) false
          (if (last-expr? seq)
              curr
              (iter (rest-exprs seq))))))
  (if (null? (cdr expr)) true
      (iter (cdr expr))))

(define (or? expr) (tagged-list? expr 'or))
(define (eval-or expr env)
  (define (iter seq)
    (let ([curr (eval (first-expr seq) env)])
      (if curr true
          (if (last-expr? seq)
              curr
              (iter (rest-exprs seq))))))
  (if (null? (cdr expr)) false
      (iter (cdr expr))))
#+end_src

It seems that the book didn't define the `derived expression` clearly. I guess it means the syntax function which don't call the `eval` directly.

Derived expression version:

#+begin_src racket :results none
; implementation of `and?` and `or`
(define (and->if expr)
  (define (iter seq)
    (cond [(null? seq) true]
          [(last-expr? seq)
           (make-if (first-expr seq)
                    (first-expr seq)
                    false)]
          [else (make-if (first-expr seq)
                         (iter (rest-exprs seq))
                         false)]))
  (iter (cdr expr)))

(define (or->if expr)
  (define (iter seq)
    (cond [(null? seq) false]
          [(last-expr? seq)
           (make-if (first-expr seq)
                    true
                    false)]
          [else (make-if (first-expr seq)
                         true
                         (iter (rest-exprs seq)))]))
  (iter (cdr expr)))
#+end_src

*** 4.5

I can only change the expand-clauses to implement the `(<test> => <recipient>)` grammar. Before this, let me have a try.

#+begin_src racket :lang racket
(define (3n+1-problem n)
  (define (odd-id? x) (and (odd? x) x))
  (define (even-id? x) (and (even? x) x))
  (cond [(odd-id? n) => (lambda (x) (+ (* 3 x) 1))]
        [(even-id? n) => (lambda (x) (/ x 2))]))

; below uses racket standard library functions
(define (3n+1-stream n)
  (define ss (stream-cons n (stream-map 3n+1-problem ss)))
  ss)

(stream->list (stream-take (3n+1-stream 7) 20))
(stream->list (stream-take (3n+1-stream 27) 112))
#+end_src

#+RESULTS:
: '(7 22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 4 2 1)
: '(27 82 41 124 62 31 94 47 142 71 214 107 322 161 484 242 121 364 182 91 274 137 412 206 103 310 155 466 233 700 350 175 526 263 790 395 1186 593 1780 890 445 1336 668 334 167 502 251 754 377 1132 566 283 850 425 1276 638 319 958 479 1438 719 2158 1079 3238 1619 4858 2429 7288 3644 1822 911 2734 1367 4102 2051 6154 3077 9232 4616 2308 1154 577 1732 866 433 1300 650 325 976 488 244 122 61 184 92 46 23 70 35 106 53 160 80 40 20 10 5 16 8 4 2 1)

#+begin_src racket :results none
(define (cond-arrow-clause? clause)
  (eq? (cadr clause) '=>))
(define (cond-arrow-recipient clause) (cddr clause))

(define (make-application proc exprs)
  (cons proc exprs))

(define (expand-clauses clauses)
  (if (null? clauses)
      false              ; clause else
      (let ([first (car clauses)] [rest (cdr clauses)])
        (if (cond-else-clause? first)
            (if (null? rest)
                (sequence->expr (cond-actions first))
                (error "ELSE clause is not last -- COND->IF" clauses))
            (if (cond-arrow-clause? first)
                (make-if (cond-predicate first)
                         (make-application (cond-arrow-recipient first) (cond-predicate first))
                         (expand-clauses rest))
                (make-if (cond-predicate first)
                         (sequence->expr (cond-actions first))
                         (expand-clauses rest)))))))
#+end_src

*** 4.6

#+begin_src BNF
<let> ::= "(" <let-identifier> "(" <bindings> ")" <body> ")"
<let-identifier> ::= 'let
<bindings> :: = <binding> | <bindings>
<binding> :: = "(" <variable> <expr> ")"
#+end_src

The binding itself is also an `expr`.

#+begin_src racket :noweb-ref eval-core-exp
(define (make-application proc exprs)
  (cons proc exprs))

(define (make-let bindings body)
  (list 'let bindings body))
(define (let? expr) (tagged-list? expr 'let))
(define let-bindings cadr)
(define let-body cddr)
(define (binding? expr) (and (pair? expr) (pair? (cdr expr)) (null? (cddr expr))
                             (variable? (car expr))))
(define bindings-first car)
(define bindings-rest cdr)
(define binding-variable car)
(define binding-value cadr)

(define (let->combination expr)
  (define (iter bindings variables exprs)
    (if (null? bindings) (cons variables exprs)
        (let ([first (bindings-first bindings)]
              [rest (bindings-rest bindings)])
          (if (binding? first)
              (iter rest
                    (cons (binding-variable first) variables) ; note that it reverse the order
                    (cons (binding-value first) exprs))
              (error "Binding form illegal -- LET" first)))))

  (let ([parameters-expressions (iter (let-bindings expr) '() '())])
    (make-application (make-lambda (car parameters-expressions)
                                   (list (sequence->expr (let-body expr))))
                      (cdr parameters-expressions))))
#+end_src

*** 4.7

A natural way to implement the `let*` is to use nested environments for orders of bindings.

As for implementing it as derived expression... Let me try to implement one to make it clear.

#+begin_src racket :noweb-ref eval-core-exp
(define (let*? expr) (tagged-list? expr 'let*))
(define (let*->nested-lets expr)
  (let ([bindings (let-bindings expr)])
    (if (or (null? bindings) (last-expr? bindings))
        expr
        (make-let (bindings-first bindings)
                  (let*->nested-lets (make-let (bindings-rest bindings)
                                               (let-body expr)))))))
#+end_src

Well, the evaluation of `let*` exactly updates the environment dynamically, since `let*` evals to nested `let`s then to nested `lambda`s. So I do not need to do more.

*** 4.8

It seems that the `(let <variable> <bindings> <body>)` can be transform to `(define (<variable> vars-in-bindings) <body>))  (let <bindings> (<variable> <vars-in-bindings>))`. Let me compare two versions of a implementation:

#+begin_src racket :results none
(define (fib n)
  (let fib-iter ((a 1)
                 (b 0)
                 (count n))
    (if (= count 0)
        b
        (fib-iter (+ a b) a (- count 1)))))

(define (fib n)
  (define (fib-iter a b count)
    (if (= count 0)
        b
        (fib-iter (+ a b) a (- count 1))))
  (let ((a 1)
        (b 0)
        (count n))
    (fib-iter a b count)))
#+end_src

#+begin_src BNF
<named-let> ::= "(" <let-identifier> <variable> <bindings> <body> ")"
#+end_src

Only list the changed procedures.

#+begin_src racket
(define (let-with-name? expr) (and (let? expr) (not (null? (cdddr expr)))))
(define let-with-name-name cadr)
(define let-with-name-bindings caddr)
(define let-with-name-body cadddr)

(define (make-function-definition name parameters body)
  (list (cons name parameters) body))

(define (let->combination expr)
  (define (iter bindings variables exprs)
    (if (null? bindings) (cons variables exprs)
        (let ([first (bindings-first bindings)]
              [rest (bindings-rest bindings)])
          (if (binding? first)
              (iter rest
                    (cons (binding-variable first) variables) ; note that it reverse the order
                    (cons (binding-value first) exprs))
              (error "Binding form illegal -- LET" first)))))

  (if (let-with-name? expr)
      (let ([name (let-with-name-name expr)]
            [parameters-expressions (iter (let-with-name-bindings expr) '() '())])
        (make-begin
         (make-function-definition name
                                   (car parameters-expressions))
         (make-let (let-with-name-bindings expr)
                   (make-application name
                                     (car parameters-expressions)))))
      (let ([parameters-expressions (iter (let-bindings expr) '() '())])
        (make-application (make-lambda (car parameters-expressions)
                                       (let-body expr))
                          (cdr parameters-expressions)))))
#+end_src

*** 4.9

#+begin_src racket :results none
(for <bindings> <pred> <after-body-bindings> <body>) ->
(let <bindings>
  (define (iter (binding-variable <bindings>) last-res)
    (<if> <pred>
          (let ([res <body>])
            (iter (binding-value <after-body-bindings>) res))
          last-res))
  (iter (binding-variable <bindings>) nil))

(for ([i 0]) (= i 10) ([i (inc i)])
     (display i))
#+end_src

It's more like a fold procedure...

#+begin_src racket
(define (for? expr) (tagged-list? expr 'for))
(define for-init-bindings car)
(define for-pred cadr)
(define for-after-bindings caddr)
(define for-body cadddr)
(define (for->derived expr)
  (let ([variables (binding-variable (for-init-bindings expr))]))
  (make-let (for-init-bindings expr)
            (make-begin
             (list
              (make-function-definition 'iter (append variables (list 'last-res))
                                        (make-if (for-pred expr)
                                                 (make-let (list [list 'res (for-body expr)])
                                                           (make-application 'iter (append variables (list 'res))))
                                                 'last-res)))
             (make-application (append variables '())))))
#+end_src

*** 4.10

Change the application to make operator to the last place in the expr list.

#+begin_src racket
(define (application? expr) (pair? expr))
(define operator tail)
(define operands heads)
(define (no-operands? ops) (null? ops))
(define first-operand car)
(define rest-operands cdr)
;<<heads-tail>>
#+end_src

#+NAME: heads-tail
#+begin_src racket
(define (tail lst)
  (cond [(null? lst) lst]
        [(null? (cdr lst)) (car lst)]
        [else (tail (cdr lst))]))
(define (heads lst)
  (cond [(null? lst) lst]
        [(null? (cdr lst)) '()]
        [else (cons (car lst) (heads (cdr lst)))]))
#+end_src

#+begin_src racket
;<<heads-tail>>
(tail (list 1 2 3))
(heads (list 1 2 3))
#+end_src

#+RESULTS:
: 3
: (1 2)

** 4.1.3 Evaluator Data Structures

*** exp

Predicate:

#+begin_src racket :noweb-ref eval-core-exp
(define (true? x)
  (not (eq? x false)))
(define (false? x)
  (eq? x false))
#+end_src

#+NAME: fix-eval-core-exp-4-1-3
#+begin_src racket
(define (apply-primitive-procedure proc args) ??)
(define (primitive-procedure? proc) ??)
#+end_src

#+begin_src racket :noweb-ref eval-core-exp
(define (make-procedure parameters body env)
  (list 'procedure parameters body env))

(define (compound-procedure? p)
  (tagged-list? p 'procedure))
(define procedure-parameters cadr)
(define procedure-body caddr)
(define procedure-environment cadddr)
#+end_src

#+begin_src racket
(define the-empty-environment '())
(define (enclosing-environment envs) (cdr envs))
(define (first-frame envs) (car envs))

(define (make-frame variables values)
  (cons variables values))
(define frame-variables car)
(define frame-values cdr)
(define (add-binding-to-frame! var val frame)
  (set-car! (cons var (frame-variables frame))
            (cons val (frame-values frame))))

(define (extend-environment vars vals base-env)
  (if (= (length vars) (length vals))
      (cons (make-frame vars vals) base-env)
      (if (< (length vars) (length vals))
          (error "Too many arguments supplied -- EXTEND-ENVIRONMENT" vars vals)
          (error "Too few arguments supplied -- EXTEND-ENVIRONMENT" vars vals))))

(define (lookup-variable-value var env)
  (define (env-loop env)
    (define (scan vars vals)
      (cond [(null? vars)
             (env-loop (enclosing-environment env))]
            [(eq? var (car vars)) (car vals)]
            [else scan (cdr vars) (cdr vals)]))
    (if (eq? env the-empty-environment)
        (error "Unbound variable:" var)
        (let ([frame (first-frame env)])
          (scan (frame-variables frame)
                (frame-values frame)))))
  (env-loop env))

(define (set-variable-value! var val env)
  (define (env-loop env)
    (define (scan vars vals)
      (cond [(null? vars)
             (env-loop  (enclosing-environment env))]
            [(eq? var (car vars))
             (set-car! vals val)]
            [else scan (cdr vars) (cdr vals)]))
    (if (eq? env the-empty-environment)
        (error "Unbound variable -- SET!" var)
        (let ([frame (first-frame env)])
          (scan (frame-variables frame)
                (frame-values frame)))))
  (env-loop env))

(define (define-variable! var val env)
  (let ([frame (first-frame env)])
    (define (scan vars vals)
      (cond [(null? vars)
             (add-binding-to-frame! var val frame)]
            [(eq? var (car vars))
             (set-car! vals val)]
            [else (scan (cdr vars vals))]))
    (scan (frame-variables frame)
          (frame-values frame))))
#+end_src

I wonder why the frame entries is not implemented as an association list. That way the `let` bindings would have the same form with a frame, which makes a simpler system...

So it's at Exercise 4.11!

*** 4.11

Scheme have a helpful builtin procedure `assv` to find record in an association list.

#+begin_src racket
(assv 3 '((1 1) (2 2) (3 3) (4 4)))
(assv 'b '((a 1) (b 2) (c 3) (d 4)))
#+end_src

#+RESULTS:
: (3 3)
: (b 2)


#+begin_src racket :noweb-ref eval-core-exp
(define the-empty-environment '())
(define (enclosing-environment envs) (cdr envs))
(define (first-frame envs) (car envs))

(define (zip2 xs ys)
  (map list xs ys))

(define (make-frame-by-bindings bindings) bindings) ; a frame is bindings
(define (make-frame vars vals) (zip2 vars vals))
(define (make-binding var val) (list var val))
;; (define binding-variable car) ; they are defined above
;; (define binding-value cadr)
(define (bind-new-value! binding val)
  (set-cdr! binding (list val)))

;; this procedure is the same with example in book
(define (extend-environment vars vals base-env)
  (if (= (length vars) (length vals))
      (cons (make-frame vars vals) base-env)
      (if (< (length vars) (length vals))
          (error "Too many arguments supplied -- EXTEND-ENVIRONMENT" vars vals)
          (error "Too few arguments supplied -- EXTEND-ENVIRONMENT" vars vals))))

(define (lookup-variable-value var env)
  (define (env-loop env)
    (if (eq? env the-empty-environment)
        (error "Unbound variable:" var)
        (let ([record (assv var (first-frame env))])
          (if record
              (binding-value record)
              (env-loop (enclosing-environment env))))))
  (env-loop env))
(define (set-variable-value! var val env)
  (define (env-loop env)
    (if (eq? env the-empty-environment)
        (error "Unbound variable -- SET!" var)
        (let ([record (assv var (first-frame env))])
          (if record
              (bind-new-value! record val)
              (env-loop (enclosing-environment env))))))
  (env-loop env))
(define (define-variable! var val env)
  (let* ([frame (first-frame env)]
         [record (assv var frame)])
    (if record
        (bind-new-value! record val)
        (set-car! env (cons (make-binding var val) frame)))))
#+end_src

*** 4.12

As for `define-variable!` in Exercise 4.11, it's precise enough. For the `scan` in the example, the `assv` abstracted it. The rest is the `env-loop`.

#+begin_src racket
(define (search-to-do-with-the-binding env var f)
  (if (eq? env the-empty-environment)
      (error "Unbound variable:" var)
      (let ([record (assv (first-frame env))])
        (if record
            (f record)
            (search-to-do-with-the-binding (enclosing-environment env) var f)))))

(define (lookup-variable-value var env)
  (search-to-do-with-the-binding
   env var binding-value))

(define (set-variable-value! var val env)
  (search-to-do-with-the-binding
   env var (lambda (binding) (begin (bind-new-value! binding val)
                                    binding))))
#+end_src

*** 4.13

I think it is better not to delete all the all bindings of the same named variables in different frames. Take below python code as example:

#+begin_src python :results output
lst = [1,2,3]

def reversed_list(lst):
    res = list(reversed(lst))
    del lst
    return res

print(reversed_list(lst), lst)
#+end_src

#+RESULTS:
: [3, 2, 1] [1, 2, 3]

If the `del lst` also unbound the `lst` in the enclosing environment, the `print` call would raise an error.

I do not allow to unbound variables in enclosing environment, that may introduce dangling-pointer problem. I think it's reasonable for a strong dynamic typed language - scheme.

#+begin_src racket
(assv 2 '((1 1) ((2 2))))

(define x '(a b))
(begin (set-car! x (cadr x))
       (set-cdr! x '())
       x)

(define y '((2 2)))
(begin (set-car! y (cadr y))
       (set-cdr! y '())
       y)
#+end_src

#+RESULTS:
: mcar: contract violation
:   expected: mpair?
:   given: ()
:   context...:
:    body of "c:\Users\asu\AppData\Local\Temp\babel-lPETWE\org-babel-rjQw1z.rkt"
: #f
: (b)

#+begin_src racket
(define (memp f lst)
  (define (iter xs)
    (cond [(null? xs) #f]
          [(f (car lst)) xs]
          [else (iter (cdr xs))]))
  (iter lst))

(define (make-unbound! var env)
  (let* ([frame (first-frame env)]
         [mems (memp (lambda (binding) (eqv? (binding-variable binding) var)) frame)])
    (cond [(or (null? frame) (not mems))
           (error "Variable is not bind -- MAKE-UNBOUND!" var)]
          [(null? (cdr frame))
           (set-car! env '())]
          [else (begin (set-car! y (cadr y))
                       (set-cdr! y '()))])))
#+end_src

** 4.1.4 Running the Evaluator as a Program

***  exp

#+begin_src racket :noweb-ref eval-core-exp
(define (setup-environment)
  (let ([initial-env
         (extend-environment (primitive-procedure-names)
                             (primitive-procedure-objects)
                             the-empty-environment)])
    (define-variable! 'true true initial-env)
    (define-variable! 'false false initial-env)
    initial-env))

(define (primitive-procedure? expr)
  (tagged-list? expr 'primitive))
(define (primitive-implementation proc) (cadr proc))

(define primitive-procedures
  (list
   (list 'car car) (list 'cdr cdr)
   (list 'cons cons) (list 'null? null?)
   (list 'list list) (list 'pair? pair?)
   (list '+ +) (list '- -) (list '* *) (list '/ /)
   (list '= =) (list '< <) (list '> >)
   (list 'display display) (list 'newline newline) ; Exercise 4.30
   (list 'eq? eq?) ; Exercise 4.34
   (list 'not not) (list 'memq memq)         ; Book 4.3.3
   (list 'even? even?)                       ; Exercise 4.52
   (list 'modulo modulo) (list 'floor floor) ; Exercise 4.53
   ))

(define (primitive-procedure-names)
  (map car primitive-procedures))

(define (primitive-procedure-objects)
  (map (lambda (proc) (list 'primitive (cadr proc)))
       primitive-procedures))

(define (apply-primitive-procedure proc args)
  (apply-in-underlying-scheme
   (primitive-implementation proc) args))

(define apply-in-underlying-scheme apply)
#+end_src

**** shadow `apply` in `#lang sicp` in racket

The `apply` is defined as a macro, it's not good to redefine it as a procedure name. In `#lang sicp`, this makes an error:

#+begin_src racket
;<<eval-core-exp>>
(define the-global-environment (setup-environment))
#+end_src

#+RESULTS:
: apply: undefined;
:  cannot reference an identifier before its definition
:   in module: "c:\Users\asu\AppData\Local\Temp\org-babel-mKGmrQ.rkt"
:   context...:
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-mKGmrQ.rkt"

This may because the statements is not evaluated sequentially. If I copy the codes(by `org-babel-expand-src-block`) into a file, it still errors.
If I use geiser other than emacs-ob-racket(which copy codes into a temp file to execute), this won't happen.

#+begin_src scheme :noweb yes :results output
(require sicp)
(define apply-in-underlying-scheme apply)
;<<eval-core-exp>>
(define the-global-environment (setup-environment))
(display the-global-environment)
(display (eval '1 the-global-environment))
#+end_src

#+RESULTS:
: (((false #f) (true #t) (car (primitive #<procedure:mcar>)) (cdr (primitive #<procedure:mcdr>)) (cons (primitive #<procedure:mcons>)) (null? (primitive #<procedure:null?>)) (list (primitive #<procedure:mlist>)) (pair? (primitive #<procedure:mpair?>)) (+ (primitive #<procedure:+>)) (- (primitive #<procedure:->)) (* (primitive #<procedure:*>)) (/ (primitive #<procedure:/>)) (= (primitive #<procedure:=>))))1

I decide to go back to change the name of `apply` to `my-apply` in this system.

#+begin_src racket
;<<eval-core-exp>>
(define the-global-environment (setup-environment))
the-global-environment
(eval 'false the-global-environment)

;<<sicp>>
(for-each (lambda (x) ((sicp 'displayln) (eval x the-global-environment)))
          (list
           '(car (cons 1 2))
           '(define x 1)
           '(+ x 1)
           '(quote (1 car))
           '(define (square x) (* x x))
           '(square 11)))
the-global-environment
#+end_src

#+RESULTS:
: (((false #f) (true #t) (car (primitive #<procedure:mcar>)) (cdr (primitive #<procedure:mcdr>)) (cons (primitive #<procedure:mcons>)) (null? (primitive #<procedure:null?>)) (list (primitive #<procedure:mlist>)) (pair? (primitive #<procedure:mpair?>)) (+ (primitive #<procedure:+>)) (- (primitive #<procedure:->)) (* (primitive #<procedure:*>)) (/ (primitive #<procedure:/>)) (= (primitive #<procedure:=>))))
: #f
: 1
: ok
: 2
: (1 car)
: ok
: 121
: #0=(((square (procedure (x) ((* x x)) #0#)) (x 1) (false #f) (true #t) (car (primitive #<procedure:mcar>)) (cdr (primitive #<procedure:mcdr>)) (cons (primitive #<procedure:mcons>)) (null? (primitive #<procedure:null?>)) (list (primitive #<procedure:mlist>)) (pair? (primitive #<procedure:mpair?>)) (+ (primitive #<procedure:+>)) (- (primitive #<procedure:->)) (* (primitive #<procedure:*>)) (/ (primitive #<procedure:/>)) (= (primitive #<procedure:=>))))

*** exp

Well, the `driver-loop` is a REPL(Read-Eval-Print-Loop), but the book didn't mentioned about this here, it's mentiened at Book 1.1.1.

#+begin_src racket :noweb-ref repl-exp
(define input-prompt ";;; M-Eval input:")
(define output-prompt ";;; M-Eval output:")

(define (driver-loop)
  (prompt-for-input input-prompt)
  (let ([input (read)])
    (let ([output (eval input the-global-environment)])
      (announce-output output-prompt)
      (user-print output))
    (driver-loop)))

(define (prompt-for-input string)
  (newline) (newline) (display string) (newline))
(define (announce-output string)
  (newline) (display string) (newline))

(define (user-print object)
  (if (compound-procedure? object)
      (display (list 'compound-procedure
                     (procedure-parameters object)
                     (procedure-body object)
                     '<procedure-env>))
      (display object)))
#+end_src

#+begin_src racket :tangle "4.1.4-repl.rkt" :comments link :results none
;<<eval-core-exp>>
(define the-global-environment (setup-environment))

;<<repl-exp>>
(driver-loop)
#+end_src

It works perfect:

#+begin_src log
————— run 4.1.4-repl.rkt —————


;;; M-Eval input:
(define (append x y) (if (null? x) y (cons (car x) (append (cdr x) y))))

;;; M-Eval output:
ok

;;; M-Eval input:
(append '(a b c) '(d e f))

;;; M-Eval output:
(a b c d e f)

;;; M-Eval input:
#+end_src

But I don't understand why & how the `'` quote works. Following the book, I didn't add this functionality explicitly.

Let me see:

#+begin_src racket
(number? '1)
(number? 1)
#+end_src

#+RESULTS:
: #t
: #t

In scheme, to execute "(number? '1)" is `(eval (quote (number? '1)))` => `(apply (eval number?) (list (eval '1)))` => `(apply number? '(1))`. So the "`" quote is evaluated by intepreting my input. It seems the new evaluation system is the same.

*** 4.14

`map` recieve a function as one of an argument. In our system, they're either `(primitive #<procedure>)` or `(procedure <body>)`. The procedure tag can't be understand by the implementation of the scheme builtin `map`.

Below implement a `map` in the evaluation system, the `my-apply` will strip the procedure tag, and all things work well.

#+begin_src racket
;<<eval-core-exp>>
(define the-global-environment (setup-environment))
(eval '(define (map f xs)
         (if (null? xs) xs
             (cons (f (car xs)) (map f (cdr xs))))) the-global-environment)
(eval '(map (lambda (x) (+ x 1)) '(1 2)) the-global-environment)
#+end_src

#+RESULTS:
: ok
: (2 3)

** 4.1.5 Data as Programs

*** exp

#+begin_src racket
;<<eval-core-exp>>
;<<higher-order>>
(define global (setup-environment))
(((F 'flip) eval) global '(define (factorial n)
                            (if (= n 1) 1
                                (* n (factorial (- n 1))))))
(((F 'flip) eval) global '(factorial 4))
#+end_src

#+RESULTS:
: ok
: 24

I know how to use this at https://docs.racket-lang.org/r5rs/r5rs-std/r5rs-Z-H-9.html#%25_idx_600.

#+begin_src racket
(eval '1 (null-environment 5))
#+end_src

#+RESULTS:
: 1

*** 4.15

It's the halting problem!

#+begin_src racket :results none
(define (run-forever) (run-forever))

(define (try p)
  (if (halts? p p)
      (run-forever)
      'halted))
#+end_src

To evaluate `(try try)`, if it evaluates to `'halted`, this means `(halts? try try) => false`, `halts?` judges the `try` applied with `try` can be halted. While `halts?` judges the `try` for `try` can halt, the `(halts? try try)` would evaluates to true, and the `(try try)` should run forerver.

If `(try try)` runs forever, this means `halts?` judges the `try` applied with `try` can not halt. While this means `(halts? try try) => false`, it should evaluates to `'halted`.

** 4.1.6 Internal Definitions

*** exp

#+begin_src racket
;<<eval-core-exp>>
;<<higher-order>>
(define global (setup-environment))
(((F 'flip) eval) global
                  '(define (even? x)
                     (define (isodd n)
                       (if (= n 0) false
                           (iseven (- n 1))))
                     (define (iseven n)
                       (if (= n 0) true
                           (isodd (- n 1))))
                     (iseven x)))
(map ((F 'partial) ((F 'flip) eval) global)
     (list
      '(even? 2)
      '(even? 3)))
#+end_src

#+RESULTS:
: ok
: (#t #f)

#+begin_src racket
;<<eval-core-exp>>
(define global (setup-environment))
(eval '(define (main)
         (define (b) 1)
         (define a (b))
         a) global)
(eval '(main) global)
#+end_src

#+RESULTS:
: ok
: 1

In fact, `define` in `#lang sicp` also can't do this:

#+begin_src racket
(define (main)
  (define (b) 1)
  (define a (b))
  a)
(main)
#+end_src

#+RESULTS:
: b: undefined;
:  cannot use before initialization
:   context...:
:    c:\Users\asu\AppData\Local\Temp\org-babel-7CLhFN.rkt:8:0
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-7CLhFN.rkt"

See the error message, it's because the definition of the implementation of internal definition of R5RS. Detail are here and Exercise 4.18, 4.19, 4.20: https://conservatory.scheme.org/schemers/Documents/Standards/R5RS/HTML/r5rs-Z-H-8.html#%_sec_5.2.2.

*** 4.16

**** a)

My implementation of environment of the intepreter is defined in Exercise 4.11.

Just check the return value of the `env-loop`.

#+begin_src racket
(define (lookup-variable-value-check-unassigned var env)
  (define (env-loop env)
    (if (eq? env the-empty-environment)
        (error "Unbound variable:" var)
        (let ([record (assv var (first-frame env))])
          (if record
              (binding-value record)
              (env-loop (enclosing-environment env))))))
  (let ([res (env-loop env)])
    (if (eqv? res '*unassigned*)
        (error "Value of var is unassigned" var))))

;<<eval-core-exp>>
(define global (setup-environment))
(eval '(define x '*unassigned*) global)
(eval 'x global)

(lookup-variable-value-check-unassigned 'x global)
#+end_src

#+RESULTS:
: Value of var is unassigned x
:   context...:
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-Ppx8JL.rkt"
: ok
: *unassigned*

**** b)

In the intepreter, the procedure is expressed as a tagged list of structure `(<procedure-identifer> <parameters> <body> <env>)` (see Book 4.1.3), and <body>s are <sequence>s (see Book 4.1.1 and my answer of Exercise 4.3).

#+NAME: scan-out-defines
#+begin_src racket :noweb-ref eval-core-exp
(define (unassigned-bindings vars)
  (map (lambda (var) (make-binding var ''*unassigned*)) vars))

(define (scan-out-defines proc-body)
  (define (reversed lst)
    (define (iter xs acc)
      (if (null? xs) acc
          (iter (cdr xs) (cons (car xs) acc))))
    (iter lst '()))
  (define (iter rests acc-v acc-e acc-b)
    ;; in r5rs, the last expr of a procedure body should not be a definition;
    ;; but I choose to return a '<void> simply
    (cond [(null? rests) (list (reversed acc-v) (reversed acc-e) ''<void>)]
          [(and (last-expr? rests)
                (not (definition? (first-expr rests))))
           (list (reversed acc-v) (reversed acc-e)
                 (sequence->expr (reversed (cons (first-expr rests) acc-b))))]
          [(definition? (first-expr rests))
           (let ([def (first-expr rests)])
             (iter (cdr rests)
                   (cons (definition-variable def) acc-v)
                   (cons (definition-value def) acc-e)
                   acc-b))]
          [else (iter (cdr rests) acc-v acc-e
                      (cons (first-expr rests) acc-b))]))
  (let ([vars-vals-expr (iter proc-body '() '() '())])
    (let ([vars (car vars-vals-expr)]
          [vals (cadr vars-vals-expr)]
          [expr (caddr vars-vals-expr)])
      (if (null? vars) proc-body
          (list (make-let (unassigned-bindings vars)
                          (sequence->expr
                           (append (map (lambda (var val)
                                          (make-assignment var val)) vars vals)
                                   (list expr)))))))))
#+end_src

#+begin_src racket
;<<eval-core-exp>>
(define global (setup-environment))

(eval '(define (main)
         (define (square x) (* x x))
         (define (double x) (* x 2))
         (double (square 3))) global)
(procedure-body (lookup-variable-value 'main global))
(eval '(main) global)
#+end_src

#+RESULTS:
: ok
: ((let ((square (quote *unassigned*)) (double (quote *unassigned*))) (begin (set! square (lambda (x) (* x x))) (set! double (lambda (x) (* x 2))) (double (square 3)))))
: 18

**** c)

Think what is the mean to add this mechanism to the language. To make inner `define` expand to parallel bindings of `let`, it's better to add it in `eval`. And this will put off the expanding to the evaluation other than parse.
If installing it to `make-procedure`, expanding would be move to parsing process.
It's not good to install it to `procedure-body` to break out abstraction barrier.

Just add the `scan-out-defines` in the `eval` of `(lambda? expr)` options.

#+begin_src racket
    [(lambda? expr)
     (make-procedure (lambda-parameters expr)
                     (scan-out-defines (lambda-body expr)) ;; here
                     env)]
#+end_src

*** 4.17

To expand

#+begin_src racket
(lambda <vars>
  (define u <e1>)
  (define v <e2>)
  <e3>)
#+end_src

into

#+begin_src racket
(lambda <vars>
  (let ((u '*unassigned*)
        (v '*unassigned*))
    (set! u <e1>)
    (set! v <e2>)
    <e3>))
#+end_src

, a new `let` scope is defined, so an extra frame is added. The system finds value from the upper frame so evaluating this would not failure.

Graphs to descript the applications of `((lambda <vars> <expr with inner defines>) <args>)`:

#+begin_src
table1 <- global:  ; nothing special
by-lambda <- E1: <vars>(<args>), u(<e1>), v(<e2>)
#+end_src

#+begin_src
table1 <- global:  ; nothing special
by-lambda <- E1: <vars>(<args>)
by-let <- E2: u(<e1>), v(<e2>)
#+end_src

To make them defines simultaneously, a natural thought is to combine inner definitions with `lambda` or `<e3>`. A viewpoint is that the new `let` bindings with `<e3>` consists to a new expr `<e4>`. In this thinking path, the only is to combine them with `lambda`.
This would transform the above example to be:

#+begin_src racket
(lambda (<vars-without-parentheses> u v)
  ; the value of `u` is `<e1>`, `v` is `<e2>`
  <e3>)
#+end_src

*** 4.18

For this transform:

#+begin_src racket
(lambda <vars>
  (let ((u '*unassigned*)
        (v '*unassigned*))
    (let ((a <e1>)
          (b <e2>))
      (set! u a)
      (set! v b))
    <e3>))
#+end_src

when evaluating `<e2>`, the `u` is not assigned. (So it's more like simultaneous assignments)

But for transform metioned in book(see Exercise 4.17 b or 4.18), when evaluating `<e2>`, `u` is assigned.

So, for this below `solve` procedure in Book 3.5.4, this transform to evaluate `solve` would raises error like `y is not defined`. But the transform mentioned in the book, this is syntax legal.

#+begin_src racket :results none
(define (solve f y0 dt)
  (define y (integral (delay dy) y0 dt))
  (define dy (stream-map f y))
  y)
#+end_src

Alike example see above of my notes with example of Book 4.1.6.

*** 4.19

Before Exercise 4.16, the expr would be evaluated to 16. This is because the system tries to find in upper environment `a` when `a` is not defined in current frame, and there's no `'*unassigned*` mechanism. If there is, it would raise an error.

#+begin_src racket
;<<eval-core-exp>>
(define global (setup-environment))

(eval '(let ((a 1))
         (define (f x)
           (define b (+ a x))
           (define a 5)
           (+ a b))
         (f 10))
      global)
#+end_src

#+RESULTS:
: +: contract violation
:   expected: number?
:   given: *unassigned*
:   context...:
:    c:\Users\asu\AppData\Local\Temp\org-babel-oPVDyH.rkt:58:0: eval-assignment
:    c:\Users\asu\AppData\Local\Temp\org-babel-oPVDyH.rkt:53:0: eval-sequence
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-oPVDyH.rkt"

It's weird to make it evaluates to 20, since the order of the definition is `b a` other than `a b`. To implement this, I come up with a convenient way to use error handling:

#+begin_src racket :results none
(define (f x)
  (define b (+ a x))
  (define a 5)
  (+ a b))

; pseudo code
(define (f x)
  (try (define b (+ a x))
       (unassigned-error
        (try (define a 5)
             (unassigned-error
              (raise-unassigned-error)))
        (define b (+ a x))))
  (+ a b))
#+end_src

This would expands to 2n-1 definition statements if there's n `define`s. But this requires a `try` macro which do not create a new scope and the side effect of `define`. If the body of the inner `define`s makes side effect, this method would computes wrong results!

It's avaliable to adjust the order of `define`s when parsing. Change the implementation of `let->combination` to sort it. It would be kind of complex.

*** 4.20

**** a)

To expand `(letrec ([<var> <val>] <other-bindings>) <body>)` to `(let ([<var> '*unassigned*] <other-bindings>) ((set! <var> <val>) <body-exprs>))`.

#+begin_src racket :noweb-ref eval-core-exp
(define (unzip2 pairs)
  ;<<fold>>
  (define first car)
  (define second cadr)
  (fold-right (lambda (pair acc)
                (cons (cons (first pair) (car acc))
                      (cons (second pair) (cdr acc))))
              pairs (cons nil nil)))
(define (bindings-variables-values bindings)
  (unzip2 bindings))

(define (letrec? expr)
  (tagged-list? expr 'letrec))
(define letrec-bindings cadr)
(define letrec-body cddr)
(define (letrec->let expr)
  (let ([vars-vals (bindings-variables-values (letrec-bindings expr))])
    (make-let (unassigned-bindings (car vars-vals))
              (sequence->expr (append (map (lambda (var val) (make-assignment var val)) (car vars-vals) (cdr vars-vals))
                                      (letrec-body expr))))))
#+end_src

#+begin_src racket
;<<eval-core-exp>>
(define global (setup-environment))

(define expr '(letrec ([fact
                        (lambda (n)
                          (if (= n 1) 1
                              (* n (fact (- n 1)))))])
                (fact 4)))

(letrec->let expr)
(eval expr global)
#+end_src

#+RESULTS:
: (let ((fact (quote *unassigned*))) (begin (set! fact (lambda (n) (if (= n 1) 1 (* n (fact (- n 1)))))) (fact 4)))
: 24

**** b)

#+begin_src racket :results none
(define (f x)
  (letrec ((even?
            (lambda (n)
              (if (= n 0)
                  true
                  (odd? (- n 1)))))
           (odd?
            (lambda (n)
              (if (= n 0)
                  false
                  (even? (- n 1))))))
    <rest of body of f>))
#+end_src

The environment when evaluating `<rest of body of f>` in `(f 5)`:

#+begin_src
table <- global: f((x), (letrec ...))
by-f <- E1: (global), x(5)
by-letrec <- E2: (E1), even?((n), ...), odd?((n), ...), <what defined in the rest of body of f>
by-even? <- E3: (E2), n(5)
#+end_src

#+begin_src
table <- global: f((x), (letrec ...))
by-f <- E1: (global), x(5)
by-let <- E2: (E1), even?((n), ...), odd?((n), ...), <what defined in the rest of body of f>
by-even? <- E3: (E1), n(5)
#+end_src

The only difference is that the inner procedure calling would inherit different environment.

*** 4.21

Wow, it's lambda calculus.

#+begin_src racket
((lambda (n)
   ((lambda (fact)
      (fact fact n))
    (lambda (ft k)
      (if (= k 1)
          1
          (* k (ft ft (- k 1)))))))
 10)
#+end_src

#+RESULTS:
: 3628800

**** a)

I try to refactor it to a understandable form.

#+begin_src racket
(define (factorial n)
  (define (b ft k)
    (if (= k 1)
        1
        (* k (ft ft (- k 1)))))
  (b b n))
(factorial 10)
#+end_src

#+RESULTS:
: 3628800

The `(lambda (n) ...)` to memorize the value of n, the `(lambda (fact) (fact fact n))` to use the `fact` twice. The `(lambda (ft k) ...)` calling it self to recurse.

**** b)

#+begin_src racket
(define (f x)
  ((lambda (even? odd?)
     (even? even? odd? x))
   (lambda (ev? od? n)
     (if (= n 0) true (od? ev? od? (- n 1))))
   (lambda (ev? od? n)
     (if (= n 0) false (ev? ev? od? (- n 1))))))

(f 5) ; => #f
(map f (list 1 3 5 7 2 4 6 8))
#+end_src

#+RESULTS:
: #f
: (#f #f #f #f #t #t #t #t)

** 4.1.7 Separating Syntax Analysis from Execution

*** exp

#+begin_src racket :noweb-ref eval-analyzed
(define (eval expr env)
  ((analyze expr) env))
#+end_src

#+begin_src racket :noweb-ref eval-analyzed
(define (analyze expr)
  (cond [(self-evaluating? expr) (analyze-self-evaluating expr)]
        [(quoted? expr) (analyze-quoted expr)]
        [(variable? expr) (analyze-variable expr)]
        [(assignment? expr) (analyze-assignment expr)]
        [(definition? expr) (analyze-definition expr)]
        [(if? expr) (analyze-if expr)]
        [(lambda? expr) (analyze-lambda expr)]
        [(begin? expr) (analyze-sequence (begin-actions expr))]
        [(cond? expr) (analyze (cond->if expr))]
        [(let? expr) (analyze (let->combination expr))]         ; let: Exercise 4.22
        [(application? expr) (analyze-application expr)]
        [else (error "Unknown expression type -- ANALYZE" expr)]))
#+end_src

#+begin_src racket :noweb-ref eval-analyzed
(define (analyze-self-evaluating expr)
  (lambda (env) expr))
(define (analyze-quoted expr)
  (let ([qval (text-of-quotation expr)])
    (lambda (env) qval)))
(define (analyze-variable expr)
  (lambda (env) (lookup-variable-value expr env)))

(define (analyze-assignment expr)
  (let ([var (assignment-variable expr)]
        [vproc (analyze (assignment-value expr))])
    (lambda (env)
      (set-variable-value! var (vproc env) env)
      'ok)))

(define (analyze-definition expr)
  (let ([var (definition-variable expr)]
        [vproc (analyze (definition-value expr))])
    (lambda (env)
      (define-variable! var (vproc env) env)
      'ok)))

(define (analyze-if expr)
  (let ([pproc (analyze (if-predicate expr))]
        [cproc (analyze (if-consequent expr))]
        [aproc (analyze (if-alternative expr))])
    (lambda (env)
      (if (true? (pproc env))
          (cproc env) (aproc env)))))

(define (analyze-lambda expr)
  (let ([vars (lambda-parameters expr)]
        [bproc (analyze-sequence (lambda-body expr))])
    (lambda (env) (make-procedure vars bproc env))))

(define (analyze-sequence exprs)
  (define (sequentially proc1 proc2)
    (lambda (env) (proc1 env) (proc2 env)))
  (define (loop first-proc rest-procs)
    (if (null? rest-procs)
        first-proc
        (loop (sequentially first-proc (car rest-procs))
              (cdr rest-procs))))
  (let ([procs (map analyze exprs)])
    (if (null? procs)
        (error "Empty sequence -- ANALYZE"))
    (loop (car procs) (cdr procs))))
#+end_src

#+begin_src racket :noweb-ref eval-analyzed
(define (analyze-application expr)
  (let ([fproc (analyze (operator expr))]
        [aprocs (map analyze (operands expr))])
    (lambda (env)
      (execute-application (fproc env)
                           (map (lambda (proc) (proc env)) aprocs)))))

(define (execute-application proc args)
  (cond [(primitive-procedure? proc)
         (apply-primitive-procedure proc args)]
        [(compound-procedure? proc)
         ((procedure-body proc)
          (extend-environment (procedure-parameters proc)
                              args
                              (procedure-environment proc)))]
        [else (error "Unknown procedure type -- EXECUTE-APPLICATION" proc)]))
#+end_src

#+begin_src racket
;<<eval-core-exp>>
(define (test)
  ;<<eval-analyzed>>
  (define (eval-displayln expr env) (display (eval expr env)) (newline))
  (define global (setup-environment))
  (eval-displayln '(define x 10) global)
  (eval-displayln 'x global)
)
(test)
#+end_src

#+RESULTS:
: ok
: 10

Well, I need some noweb to simplify them:

#+begin_src racket-bad-syntax :noweb yes :noweb-ref eval-analyzed-test-start
;<<eval-core-exp>>
(define (eval-analyzed-scope)
  ;<<eval-analyzed>>
  (define (eval-displayln expr env) (display (eval expr env)) (newline))
  (define global (setup-environment))
#+end_src

#+begin_src racket-bad-syntax :noweb yes :noweb-ref eval-analyzed-test-end
)
(eval-analyzed-scope)
#+end_src

#+begin_src racket
;<<eval-analyzed-test-start>>
(eval-displayln '(+ 1 1) global)
;<<eval-analyzed-test-end>>
#+end_src

#+RESULTS:
: 2

*** 4.22

#+begin_src racket
;<<eval-analyzed-test-start>>
(eval-displayln '(let ([x 1]) (+ x x)) global)
;<<eval-analyzed-test-end>>
#+end_src

#+RESULTS:
: 2

*** 4.23

#+begin_src racket :noweb-ref 4-23
(define (analyze-sequence exps)
  (define (execute-sequence procs env)
    (cond ((null? (cdr procs)) ((car procs) env))
          (else ((car procs) env)
                (execute-sequence (cdr procs) env))))
  (let ((procs (map analyze exps)))
    (if (null? procs)
        (error "Empty sequence -- ANALYZE"))
    (lambda (env) (execute-sequence procs env))))
#+end_src

For sequence `((set! x 1))`, this version will be analyzed to:

#+begin_src racket
(lambda (env) ; by anayze-sequence
  ((lambda (env) ; by (map analyze exps)
     (set-variable-value! x (lambda (env) 1)) 'ok)
   env))
#+end_src

The before version analyzes to:

#+begin_src racket
(lambda (env) ; by (map analyze exprs)
  (set-variable-value! x (lambda (env) 1)) 'ok)
#+end_src

This is because the before version will check if there's only one expr in the sequence, but this version do not.

For sequence `((set! x 1) x)`, they are going to be analyzed to:

#+begin_src racket
;; this version
(lambda (env) ; by analyze-sequence
  ((lambda (env)
     (set-variable-value! x (lambda (env) 1)) 'ok)
   env)
  ((lambda (env) (lookup-variable-value 'x env)) env))

;; before version
(lambda (env) ; by sequentially
  ((lambda (env)
     (set-variable-value! x (lambda (env) 1)) 'ok) env)
  ((lambda (env) (lookup-variable-value 'x env)) env))
#+end_src

In this case the two version analyze to the same result.

*** 4.24

**** introspection

I forgot that there is a procedure `runtime` in `#lang sicp`.

#+begin_src racket
(runtime)
#+end_src

#+RESULTS:
: 1782906067715236

**** answer

In racket language, there's some procedures which can be used to count time. I went to learn how to use `#%require` in racket `#lang sicp`. https://docs.racket-lang.org/reference/require.html#%28form._%28%28quote._~23~25kernel%29._~23~25require%29%29

#+begin_src racket
(#%require (only racket current-process-milliseconds
                 stream-cons stream-map stream-ref stream-first stream-rest))

(define (stream-map2 f xs ys)
  (stream-cons (f (stream-first xs) (stream-first ys))
               (stream-map2 f (stream-rest xs) (stream-rest ys))))
(define ones (stream-cons 1 ones))
(define integers (stream-cons 1 (stream-map2 + ones integers)))

(define (time-procedure-milliseconds f)
  (let* ([start (current-process-milliseconds)]
         [res (f)]
         [end (current-process-milliseconds)])
    (map display (list
                  (- end start) " ms: " res))
    (newline)))
(time-procedure-milliseconds (lambda () (stream-ref integers (* 100 1000))))
#+end_src
#+RESULTS:
: 78 ms: 100001

#+begin_src racket :noweb-ref time-repeat-procedure-milliseconds
(#%require (only racket current-process-milliseconds))

(define (time-repeat-procedure-milliseconds n f)
  (define (iter i)
    (if (>= i (- n 1)) (f)
        (begin (f) (iter (+ i 1)))))
  (let* ([start (current-process-milliseconds)]
         [res (iter 0)]
         [end (current-process-milliseconds)])
    (map display (list
                  (- end start) " ms: " res))
    (newline)))
#+end_src

#+begin_src racket
;<<time-repeat-procedure-milliseconds>>
(define dataset
  (list
   '1
   ''x
   '+
   '(set! / 1)           ; randomly choose a symbol to assign
   '(define x 1)
   '(if false true false)
   '(lambda () '())
   '(begin 1 6391)
   '(+ 1 1)
   ))

(define (eval-analyzed expr env) (expr env))
(define times (* 10 1000 1000))

;<<eval-analyzed-test-start>>
(begin
  (map
   (lambda (expr)
     (let ([analyzed (analyze expr)])
       (time-repeat-procedure-milliseconds times (lambda () (eval-analyzed analyzed global)))))
   dataset)
  #f)
;<<eval-analyzed-test-end>>
(define global (setup-environment))
(begin
  (map
   (lambda (expr)
     (time-repeat-procedure-milliseconds times (lambda () (eval expr global))))
   dataset)
  #f)
#+end_src

#+RESULTS:
#+begin_example
31 ms: 1
16 ms: x
250 ms: (primitive #<procedure:+>)
438 ms: ok
93 ms: ok
172 ms: #f
78 ms: (procedure () #<procedure:...rg-babel-hrFwPp.rkt:421:6> (((x 1) (false #f) (true #t) (car (primitive #<procedure:mcar>)) (cdr (primitive #<procedure:mcdr>)) (cons (primitive #<procedure:mcons>)) (null? (primitive #<procedure:null?>)) (list (primitive #<procedure:mlist>)) (pair? (primitive #<procedure:mpair?>)) (+ (primitive #<procedure:+>)) (- (primitive #<procedure:->)) (* (primitive #<procedure:*>)) (/ 1) (= (primitive #<procedure:=>)))))
32 ms: 6391
562 ms: 2
#f
31 ms: 1
32 ms: x
265 ms: (primitive #<procedure:+>)
469 ms: ok
141 ms: ok
250 ms: #f
171 ms: (procedure () ((quote ())) (((x 1) (false #f) (true #t) (car (primitive #<procedure:mcar>)) (cdr (primitive #<procedure:mcdr>)) (cons (primitive #<procedure:mcons>)) (null? (primitive #<procedure:null?>)) (list (primitive #<procedure:mlist>)) (pair? (primitive #<procedure:mpair?>)) (+ (primitive #<procedure:+>)) (- (primitive #<procedure:->)) (* (primitive #<procedure:*>)) (/ 1) (= (primitive #<procedure:=>)))))
79 ms: 6391
578 ms: 2
(#<void> #<void> #<void> #<void> #<void> #<void> #<void> #<void> #<void>)
#f
#+end_example

Let me see how much time it costs when combining analyzing and evaluating.

#+begin_src racket
;<<time-repeat-procedure-milliseconds>>

(define expr
  '(define (factorial n)
     "hello"
     '1
     ''x
     (define y 1)
     (set! y 4)
     (+ (* 2 y) 3)))

(define (eval-analyzed expr env) (expr env))
(define times (* 1000 1000))

;<<eval-analyzed-test-start>>
(let ([analyzed (analyze expr)])
  (time-repeat-procedure-milliseconds times (lambda () (eval-analyzed analyzed global))))
(time-repeat-procedure-milliseconds times (lambda () (eval expr global)))
;<<eval-analyzed-test-end>>
(define global (setup-environment))
(time-repeat-procedure-milliseconds times (lambda () (eval expr global)))
#+end_src

#+RESULTS:
: 47 ms: ok
: 172 ms: ok
: 62 ms: ok

* 4.2 Variations on a Scheme -- Lazy Evaluation

** 4.2.1 Normal Order and Applicative Order

*** 4.25

#+begin_src racket :results none
(define (factorial n)
  (unless (= n 1)
          (* n (factorial (- n 1)))
          1))
#+end_src

With applicative order, this runs into endless recusion. While it works well in normal order.

*** 4.26

Well, it's possible to implement the `unless` as a special form in applicative evaluating ordered language. Essentially, it's just a expand, and this needs the interpreter to support.

#+begin_src racket :results none
(define (unless? expr) (tagged-list? 'unless))
(define unless-condition cadr)
(define unless-usual caddr)
(define unless-exceptional cadddr)
(define (unless->if expr)
  (make-if (unless-condition expr)
           (unless-exceptional expr)
           (unless-usual expr)))
#+end_src

Another implementation by scheme macro mechanism.

#+NAME: unless-macro
#+begin_src racket
(define-syntax unless
  (syntax-rules ()
    ([_ condition usual exception]
     (if condition exception usual))))

(unless (> 1 2) 1 2)
#+end_src

#+RESULTS:
: 1

This special form cannot be used in conjunction with higher-order procedures.

#+begin_src racket
;<<unless-macro>>
(map unless (list (list '(> 1 2) '1 '2)))
#+end_src

#+RESULTS:
: c:\Users\asu\AppData\Local\Temp\org-babel-Wg0olZ.rkt:10:5: unless: bad syntax
:   in: unless
:   location...:
:    c:\Users\asu\AppData\Local\Temp\org-babel-Wg0olZ.rkt:10:5

** 4.2.2 An Interpreter with Lazy Evaluation

*** exp

#+begin_src racket :noweb-ref eval-lazy
(define (actual-value expr env)
  (force-it (eval-lazy expr env)))

(define (eval-lazy expr env)
  (cond
    [(self-evaluating? expr) expr]
    [(variable? expr) (lookup-variable-value expr env)]
    [(quoted? expr) (text-of-quotation expr)]
    [(assignment? expr) (eval-assignment expr env)]
    [(definition? expr) (eval-definition expr env)]
    [(lambda? expr)
     (make-procedure (lambda-parameters expr)
                     (scan-out-defines (lambda-body expr)) ; Exercise 4.16
                     env)]
    [(begin? expr)
     (eval-sequence (begin-actions expr) env)]
    [(if? expr) (eval-if-lazy expr env)]
    [(cond? expr) (eval-lazy (cond->if expr) env)]
    [(and? expr) (eval-and expr env)] ; and & or: Exercise 4.4
    [(or? expr) (eval-or expr env)]
    [(let? expr) (eval-lazy (let->combination expr) env)] ; let: Exercise 4.6
    [(let*? expr) (eval-lazy (let*->nested-lets expr) env)] ; let*: Exercise 4.7
    [(letrec? expr) (eval-lazy (letrec->let expr) env)] ; letrec: Exercise 4.20
    [(application? expr)
     (apply-lazy (actual-value (operator expr) env) ;; CHANGED HERE
                 (operands expr)
                 env)]
    [else (error "Unknown expression type -- EVAL" expr)]))

(define (apply-lazy procedure arguments env)
  (cond
    [(primitive-procedure? procedure)
     (apply-primitive-procedure
      procedure
      (list-of-arg-values arguments env))]
    [(compound-procedure? procedure)
     (eval-sequence
      (procedure-body procedure)
      (extend-environment
       (procedure-parameters procedure)
       (list-of-delayed-args arguments env)
       (procedure-environment procedure)))]
    [else (error "Unknown procedure type -- APPLY" (list procedure arguments))]))

(define (list-of-arg-values exprs env)
  (if (no-operands? exprs) '()
      (cons (actual-value (first-operand exprs) env)
            (list-of-arg-values (rest-operands exprs) env))))

(define (list-of-delayed-args exprs env)
  (if (no-operands? exprs) '()
      (cons (delay-it (first-operand exprs) env)
            (list-of-delayed-args (rest-operands exprs) env))))

(define (eval-if-lazy expr env)
  (if (true? (actual-value (if-predicate expr) env))
      (eval-lazy (if-consequent expr) env)
      (eval-lazy (if-alternative expr) env)))
#+end_src

#+begin_src racket :noweb-ref eval-lazy
(define (force-it-exp obj)
  (if (thunk? obj)
      (actual-value (thunk-expr obj) (thunk-env obj))
      obj))

(define (delay-it expr env) (make-thunk expr env))

(define (make-thunk expr env)
  (list 'thunk expr env))
(define (thunk? obj)
  (tagged-list? obj 'thunk))
(define thunk-expr cadr)
(define thunk-env caddr)

(define (evaluated-thunk? obj)
  (tagged-list? obj 'evaluated-thunk))
(define (thunk-value evaluated-thunk) (cadr evaluated-thunk))

(define (force-it obj)
  (cond [(thunk? obj)
         (let ([result (actual-value (thunk-expr obj) (thunk-env obj))])
           (set-car! obj 'evaluated-thunk)
           (set-car! (cdr obj) result)
           (set-cdr! (cdr obj) '())
           result)]
        [(evaluated-thunk? obj) (thunk-value obj)]
        [else obj]))
#+end_src

#+begin_src racket :noweb-ref repl-lazy
(define input-prompt ";;; L-Eval input:")
(define output-prompt ";;; L-Eval output:")

(define (driver-loop)
  (prompt-for-input input-prompt)
  (let* ([input (read)]
         [output (actual-value input the-global-environment)])
    (announce-output output-prompt)
    (user-print output))
  (driver-loop))
#+end_src

#+begin_src racket
;<<eval-core-exp>>
(define (eval-lazy-scope)
  ;<<eval-lazy>>
  (define global (setup-environment))
  (define (eval-displayln expr env) (display (eval-lazy expr env)) (newline))
  (eval-displayln '(define (try a b) (if (= a 0) 1 b)) global)
  (eval-displayln '(try 0 (/ 1 0)) global)
)
(eval-lazy-scope)
#+end_src

#+RESULTS:
: =: contract violation
:   expected: number?
:   given: (thunk 0 #0=(((try (procedure (a b) ((if (= a 0) 1 b)) #0#)) (false #f) (true #t) (car (primitive #<procedure:mcar>)) (cdr (primitive #<procedure:mcdr>)) (cons (primitive #<procedure:mcons>)) (null? (primitive #<procedure:null?>)) (list (primitive #<pro...
:   context...:
:    c:\Users\asu\AppData\Local\Temp\org-babel-w84wCb.rkt:47:0: eval-if
:    c:\Users\asu\AppData\Local\Temp\org-babel-w84wCb.rkt:462:2
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-w84wCb.rkt"
: ok

Hmm... It comes to a problem. The lazy `eval` depends on other procedures which denpends on outter `eval` which is not lazy. Use `set!` to cover the old `eval`.

#+begin_src racket
;<<eval-core-exp>>
;<<eval-lazy>>
(set! eval eval-lazy)
(define global (setup-environment))

(eval-lazy '(define (try a b) (if (= a 0) 1 b)) global)
(eval-lazy '(try 0 (/ 1 0)) global)
#+end_src

#+RESULTS:
: ok
: 1

#+begin_src racket :tangle "4.2.2-repl.rkt"
;<<eval-core-exp>>
;<<eval-lazy>>
;<<repl-exp>>
(set! eval eval-lazy)
(define the-global-environment (setup-environment))
(define (eval-lazy-repl-scope)
  ;<<repl-lazy>>
  (driver-loop)
)
(eval-lazy-repl-scope)
#+end_src

Results of `./4.2.2-repl.rkt`:

#+begin_src log
————— run 4.2.2-repl.rkt —————


;;; L-Eval input:
(define (try a b) (if (= a 0) 1 b))

;;; L-Eval output:
ok

;;; L-Eval input:
(try 0 (/ 1 0))

;;; L-Eval output:
1

;;; L-Eval input:
#+end_src

#+begin_src racket :noweb-ref eval-lazy-test :results none
;<<eval-core-exp>>
;<<eval-lazy>>
(set! eval eval-lazy)
(define global (setup-environment))
#+end_src

*** 4.27

Note that the REPL use `actual-value` directly to get result.

#+begin_src racket
;<<eval-lazy-test>>
(eval-lazy '(define count 0) global)
(eval-lazy '(define (id x)
              (set! count (+ count 1)) x) global)
(eval-lazy '(define w (id (id 10))) global)

(actual-value 'count global) ; => 0
(actual-value 'w global)     ; => 10
(actual-value 'count global) ; => 2
#+end_src

#+RESULTS:
: ok
: ok
: ok
: 1
: 10
: 2

Well, it is not so lazy as I thought. The first evaluation of `count` is `1` means the `define` evaluates the out layer of executing the `id` proedure.

When defining `w`, `eval-definition` calls `eval` on `(id (id 10))`. This makes `apply-lazy` apply the `id`, so the `count` is changed. And the `(id 10)` is wrapped to a thunk.

*** 4.28

When evaluating application, the value of operator is need, so it shouldn't be thunk.

In Exercise 4.27, I know how to define a value which evaluates to be a thunk. Let me construct an example. Below example uses `eval-lazy` other than `actual-value`, which raise an error by applying a thunk with some arguments.

#+begin_src racket
;<<eval-lazy-test>>
(eval-lazy '(define (id x) x) global)
(eval-lazy '(define add (id +)) global)

(thunk? (eval-lazy 'add global))
(define expr '(add 1 2))
(apply-lazy (eval-lazy (operator expr) global)
            (operands expr)
            global)
#+end_src

#+RESULTS:
: Unknown procedure type -- APPLY (#0=(thunk + #1=(((add #0#) (id (procedure (x) (x) #1#)) (false #f) (true #t) (car (primitive #<procedure:mcar>)) (cdr (primitive #<procedure:mcdr>)) (cons (primitive #<procedure:mcons>)) (null? (primitive #<procedure:null?>)) (list (primitive #<procedu...
:   context...:
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-BpSPhY.rkt"
: ok
: ok
: #t

*** 4.29

Use `(set! force-it force-it-exp)` (see `force-it-exp` in above ***exp section) to use a version without memorization.

#+begin_src racket
;<<eval-lazy-test>>
(set! force-it force-it-exp)
(eval-lazy '(define count 0) global)
(eval-lazy '(define (id x)
              (set! count (+ count 1)) x) global)
(eval-lazy '(define (square x) (* x x)) global)

(actual-value '(square (id 10)) global) ; => 100
(actual-value 'count global) ; => 2
#+end_src

#+RESULTS:
: ok
: ok
: ok
: 100
: 2

The `count` increased twice because it evaluates the `(* (thunk (id 10) <the-env>) (thunk (id 10) <the-env>))`.

*** 4.30

**** a)

#+begin_src racket
;<<eval-lazy-test>>
(eval-lazy '(define (for-each proc items)
              (if (null? items) 'done
                  (begin (proc (car items))
                         (for-each proc (cdr items))))) global)
(actual-value '(for-each (lambda (x) (newline) (display x))
                         (list 57 321 88)) global)
#+end_src

#+RESULTS:
: ok
:
: 57
: 321
: 88done

The key point is whether `(proc (car items))` is evaluated lazily. When it applying the `proc` to the argument `(car items)`, the argument is delayed, but later it is evaluated by `eval-sequence`(in apply-lazy). Then `(car items)` is applied, but the `car` is primitive, it force the value to be evaluated. So it just a special example.

There's some cases that the side effect do not take place in Python 3:

#+begin_src python :results output
map(print, [1, 2])       # this line don't print
list(map(print, [1, 2]))
#+end_src

#+RESULTS:
: 1
: 2

This is because the return value of `map` function in Python 3 is an iterator, or to say as a single-use stream. But the list function will consume the iterator to construct a non-lazy list.

**** b)

#+begin_src racket :results none :noweb-ref 4-30-exp
(eval-lazy '(define (p1 x)
              (set! x (cons x '(2)))
              x) global)
(eval-lazy '(define (p2 x)
              (define (p e) e x)
              (p (set! x (cons x '(2))))) global)

(actual-value '(p1 1) global)
(actual-value '(p2 1) global)
#+end_src

This example to be executed in approach in the book evaluates to `(<thunk of 1> 2)` and `<thunk of 1>` then forced to `(1 2)` and `1` by `actual-value`.

Because the evaluator is lazy to force `(set! x (cons x '(2)))`.

#+begin_src racket
;<<eval-lazy-test>>
;<<4-30-exp>>
#+end_src

#+RESULTS:
: ok
: ok
: (1 2)
: 1

#+begin_src racket :results none :noweb-ref 4-30
(define (eval-sequence-eagerer exps env)
  (cond ((last-expr? exps) (eval (first-expr exps) env))
        (else (actual-value (first-expr exps) env)      ; changed to `actual-value`
              (eval-sequence (rest-exprs exps) env))))
#+end_src

With this new version, the result is more like which is executed by an applicative evaluator. They'll be `(1 2)` and `(1 2)`.

#+begin_src racket
;<<eval-lazy-test>>
;<<4-30>>
(set! eval-sequence eval-sequence-eagerer)
;<<4-30-exp>>
#+end_src

#+RESULTS:
: ok
: ok
: (1 2)
: (1 2)

**** c)

In `a)` the `(car items)` is forced because the `car` is primitive. Execute this example in the new version of `eval-sequence` in `b)`, the `(car items)` should be forced by the implementation.

**** d)

Well, I don't like the way this evaluator takes with laziness. Like my example in Python 3 in `a)`, it's important to recognize conveniently whether the system evaluates lazily. Or just evaluating everything lazily, just like Haskell. This system takes me more consideration on "if it evaluates lazy", and I think this breaks the abstraction barrier, even introducing a more eager `eval-sequence`.

*** 4.31

#+begin_src racket
(define-with-lazy (f a (b lazy) c (d lazy-memo))
  ...)
#+end_src

Consider how to define the syntax with only variable:

#+begin_src racket
(define-with-lazy (f lazy) ...)
#+end_src

Note that this syntax can be explained as a normal procedure(like which defined by `define`) with name `f` and the arguments are `(lazy)`, but also can be explained as defining a variable `f` which is lazily evaluated with body `...`.

To avoid this question, let me set the rule that the `define-with-lazy` cannot define a variable; all `define-with-lazy` define procedures. The form:

#+begin_src
(define-with-lazy <declaration> <value>)

<declaration> ::= "(" + <procedure-name> + <variables-with-laziness-tags> ")"
<variables-with-laziness-tags> ::= <variable> | "(" + <variable> + <laziness-tag> ")"
<laziness-tag> ::= "lazy" | "lazy-memo"
#+end_src

#+begin_src racket :noweb-ref eval-lazy-tag
(define (definition-with-lazy? expr)
  (and (tagged-list? expr 'define-with-lazy)
       (list? (cadr expr))))
(define (make-definition-with-lazy declaration value)
  (list 'define-with-lazy declaration value))
(define definition-with-lazy-declaration cadr)
(define definition-with-lazy-value caddr)

(define declaration-procedure-name car)
(define declaration-varialbes-with-tags cdr)

(define (definition-with-lazy-name expr)
  (declaration-procedure-name (definition-with-lazy-declaration expr)))
(define (definition-with-lazy-variables-with-tags expr)
  (declaration-varialbes-with-tags (definition-with-lazy-declaration expr)))

(define (parameter-lazy? param)
  (and (list? param) (list? (cdr param)) (eq? (cadr param) 'lazy)))
(define (parameter-lazy-memo? param)
  (and (list? param) (list? (cdr param)) (eq? (cadr param) 'lazy-memo)))

(define (lazy-parameter-name param) (car param))
(define (parameter-name param)
  (if (list? param) (car param) param))
(define (parameter-tag param)
  (if (list? param) (cadr param) 'eager))
#+end_src

Consider the different force strategies of `lazy` and `lazy-memo`, new identifiers are need to distinguish them.

#+begin_src racket :noweb-ref eval-lazy-tag
(define (make-thunk expr env)
  (list 'lazy expr env))
(define (thunk? obj)
  (tagged-list? obj 'lazy))
(define (make-thunk-memo expr env)
  (list 'lazy-memo expr env))
(define (thunk-memo? obj)
  (tagged-list? obj 'lazy-memo))

(define thunk-expr cadr)
(define thunk-env caddr)

(define (delay-it expr env) (make-thunk expr env))
(define (delay-it-memo expr env) (make-thunk-memo expr env))

(define (evaluated-thunk? obj)
  (tagged-list? obj 'evaluated-thunk))
(define (thunk-value evaluated-thunk) (cadr evaluated-thunk))

(define (force-it obj)
  (cond [(thunk? obj)
         (actual-value (thunk-expr obj) (thunk-env obj))]
        [(thunk-memo? obj)
         (let ([result (actual-value (thunk-expr obj) (thunk-env obj))])
           (set-car! obj 'evaluated-thunk)
           (set-car! (cdr obj) result)
           (set-cdr! (cdr obj) '())
           result)]
        [(evaluated-thunk? obj) (thunk-value obj)]
        [else obj]))

(define (actual-value expr env)
  (force-it (eval-lazy expr env)))
#+end_src

Well, it's strange. I come up with the expression of the thunks firstly, which is a lower abstraction layer.

Let the `define-with-lazy` keeps the form of `variables-with-laziness-tags` so that the `apply-lazy` can see them.

#+begin_src racket :noweb-ref eval-lazy-tag
(define (eval-lazy expr env)
  (cond
    [(self-evaluating? expr) expr]
    [(variable? expr) (lookup-variable-value expr env)]
    [(quoted? expr) (text-of-quotation expr)]
    [(assignment? expr) (eval-assignment expr env)]
    [(definition? expr) (eval-definition expr env)]
    [(definition-with-lazy? expr) (eval-definition expr env)] ; Exercise 4.31
    [(lambda? expr)
     (make-procedure (lambda-parameters expr)
                     (scan-out-defines (lambda-body expr)) ; Exercise 4.16
                     env)]
    [(begin? expr)
     (eval-sequence (begin-actions expr) env)]
    [(if? expr) (eval-if-lazy expr env)]
    [(cond? expr) (eval-lazy (cond->if expr) env)]
    [(and? expr) (eval-and expr env)] ; and & or: Exercise 4.4
    [(or? expr) (eval-or expr env)]
    [(let? expr) (eval-lazy (let->combination expr) env)] ; let: Exercise 4.6
    [(let*? expr) (eval-lazy (let*->nested-lets expr) env)] ; let*: Exercise 4.7
    [(letrec? expr) (eval-lazy (letrec->let expr) env)] ; letrec: Exercise 4.20
    [(application? expr)
     (apply-lazy (actual-value (operator expr) env) ;; CHANGED HERE
                 (operands expr)
                 env)]
    [else (error "Unknown expression type -- EVAL" expr)]))

(define (apply-lazy procedure arguments env)
  (cond
    [(primitive-procedure? procedure)
     (apply-primitive-procedure
      procedure
      (list-of-arg-values arguments env))]
    [(compound-procedure? procedure)
     (eval-sequence
      (procedure-body procedure)
      (extend-environment
       (map parameter-name (procedure-parameters procedure))
       (list-of-delayed-args arguments
                             (map parameter-tag (procedure-parameters procedure)) env)
       (procedure-environment procedure)))]
    [else (error "Unknown procedure type -- APPLY" (list procedure arguments))]))
#+end_src

The `define-with-lazy` and `define` have same strucutre, so I use the `eval-definition` to eval. But the parameters saved the laziness identifiers, so I need to extract parameter names by `argument-name`.

All procedures defined by `define-with-lazy` are compound procedure, and every lazy evaluation is dispatched to other procedures.

#+begin_src racket :noweb-ref eval-lazy-tag
(define (list-of-arg-values args env)
  (if (no-operands? args) '()
      (cons (actual-value (first-operand args) env)
            (list-of-arg-values (rest-operands args) env))))

(define (list-of-delayed-args args lazy-tags env)
  (define (delay-arg arg tag env)
    (cond [(eq? tag 'lazy)
           (delay-it arg env)]
          [(eq? tag 'lazy-memo)
           (delay-it-memo arg env)]
          [else (actual-value arg env)]))
  (if (no-operands? args) '()
      (cons (delay-arg (first-operand args) (car lazy-tags) env)
            (list-of-delayed-args (rest-operands args) (cdr lazy-tags) env))))

(define (eval-if-lazy expr env)
  (if (true? (actual-value (if-predicate expr) env))
      (eval-lazy (if-consequent expr) env)
      (eval-lazy (if-alternative expr) env)))
#+end_src

Only to change `list-of-delayed-args`, this is because there're two type of lazy.

#+begin_src racket :noweb-ref eval-lazy-tag
;<<eval-core-exp>>
(set! eval eval-lazy)
#+end_src

#+begin_src racket
;<<eval-lazy-tag>>
(define global (setup-environment))
(map (lambda (expr) (eval-lazy expr global))
     (list '(define count 0)
           '(define (id (x lazy-memo))
              (set! count (+ count 1)) x)
           '(define w (id (id 10)))))

(actual-value 'count global) ; => 1
(actual-value 'w global)     ; => 10
(actual-value 'count global) ; => 2

(newline)

(map (lambda (expr) (eval-lazy expr global))
     (list '(define (square x) (* x x))
           '(define (square-lazy (x lazy)) (* x x))
           '(define (id-display x) (display x) x)))
(actual-value '(square (id-display 2)) global)
(actual-value '(square-lazy (id-display 2)) global) ; prints 2 twice
#+end_src

#+RESULTS:
: (ok ok ok)
: 1
: 10
: 2
:
: (ok ok ok)
: 24
: 224

** 4.2.3 Streams as Lazy Lists

*** exp

The evaluator allow redefininition because of the `define-variable!` implementation.

#+begin_src racket
;<<eval-lazy-test>>
(eval-lazy '(define (cons x y)
              (lambda (m) (m x y))) global)
(eval-lazy '(define cons 1) global)
global
#+end_src

#+RESULTS:
: ok
: ok
: (((false #f) (true #t) (car (primitive #<procedure:mcar>)) (cdr (primitive #<procedure:mcdr>)) (cons 1) (null? (primitive #<procedure:null?>)) (list (primitive #<procedure:mlist>)) (pair? (primitive #<procedure:mpair?>)) (+ (primitive #<procedure:+>)) (- (primitive #<procedure:->)) (* (primitive #<procedure:*>)) (/ (primitive #<procedure:/>)) (= (primitive #<procedure:=>)) (display (primitive #<procedure:mdisplay>)) (newline (primitive #<procedure:newline>))))

#+begin_src racket :noweb-ref lazy-list-defs
(define lazy-list-defs
  (list '(define (cons x y)
           (lambda (m) (m x y)))
        '(define (car z)
           (z (lambda (x y) x)))
        '(define (cdr z)
           (z (lambda (x y) y)))
        '(define (list-ref items n)
           (if (= n 0)
               (car items)
               (list-ref (cdr items) (- n 1))))
        '(define (map f items)
           (if (null? items) '()
               (cons (f (car items))
                     (map f (cdr items)))))
        '(define (scale-list items factor)
           (map (lambda (x) (* x factor)) items))
        '(define (add-lists xs ys)
           (cond [(null? xs) ys]
                 [(null? ys) xs]
                 [else (cons (+ (car xs) (car ys))
                             (add-lists (cdr xs) (cdr ys)))]))
        '(define ones (cons 1 ones))
        '(define integers (cons 1 (add-lists ones integers)))
        ))
#+end_src

#+begin_src racket :noweb-ref lazy-list
;<<eval-lazy-test>>
;<<lazy-list-defs>>
(map (lambda (expr) (eval-lazy expr global)) lazy-list-defs)
#+end_src

#+begin_src racket
;<<lazy-list>>
(eval-lazy '(car integers) global)
(actual-value '(list-ref integers 17) global)
#+end_src

#+RESULTS:
: (ok ok ok ok ok ok ok ok ok)
: (thunk x (((m (evaluated-thunk (procedure #4=(x y) #5=(x) (((z (evaluated-thunk #0=(procedure #1=(m) #2=((m x y)) #6=(((x (thunk 1 #3=(((integers #0#) (ones (procedure #1# #2# (((x (thunk 1 #3#)) (y (thunk ones #3#))) . #3#))) (add-lists (procedure (xs ys) ((cond ((null? xs) ys) ((null? ys) xs) (else (cons (+ (car xs) (car ys)) (add-lists (cdr xs) (cdr ys)))))) #3#)) (scale-list (procedure (items factor) ((map (lambda (x) (* x factor)) items)) #3#)) (map (procedure (f items) ((if (null? items) (quote ()) (cons (f (car items)) (map f (cdr items))))) #3#)) (list-ref (procedure (items n) ((if (= n 0) (car items) (list-ref (cdr items) (- n 1)))) #3#)) (false #f) (true #t) (car (procedure (z) ((z (lambda #4# . #5#))) #3#)) (cdr (procedure (z) ((z (lambda (x y) y))) #3#)) (cons (procedure (x y) ((lambda #1# . #2#)) #3#)) (null? (primitive #<procedure:null?>)) (list (primitive #<procedure:mlist>)) (pair? (primitive #<procedure:mpair?>)) (+ (primitive #<procedure:+>)) (- (primitive #<procedure:->)) (* (primitive #<procedure:*>)) (/ (primitive #<procedure:/>)) (= (primitive #<procedure:=>)) (< (primitive #<procedure:<>)) (> (primitive #<procedure:>>)) (display (primitive #<procedure:mdisplay>)) (newline (primitive #<procedure:newline>)))))) (y (thunk (add-lists ones integers) #3#))) . #3#))))) . #3#))))) . #6#))
: 18

#+begin_src racket
;<<lazy-list>>
(map (lambda (expr) (eval-lazy expr global))
     (list '(define (integral integrand initial-value dt)
              (define int
                (cons initial-value
                      (add-lists (scale-list integrand dt)
                                 int)))
              int)
           '(define (solve f y0 dt)
              (define y (integral dy y0 dt))
              (define dy (map f y))
              y)
           ))
(actual-value '(list-ref (solve (lambda (x) x) 1 0.001) 1000) global)
#+end_src

#+RESULTS:
: (ok ok ok ok ok ok ok ok ok)
: (ok ok)
: 2.716923932235896

*** 4.32

Not only the structure is lazy, but also the value of element is delayed. By the book I know they may from the same mechamism, but are two different application of delay.

#+begin_src racket
;<<lazy-list>>
(eval-lazy 'integers global)
(eval-lazy '(car integers) global)
#+end_src

#+RESULTS:
: (ok ok ok ok ok ok ok ok ok)
: #0=(procedure #1=(m) #2=((m x y)) (((x (thunk 1 #3=(((integers #0#) (ones (procedure #1# #2# (((x (thunk 1 #3#)) (y (thunk ones #3#))) . #3#))) (add-lists (procedure (xs ys) ((cond ((null? xs) ys) ((null? ys) xs) (else (cons (+ (car xs) (car ys)) (add-lists (cdr xs) (cdr ys)))))) #3#)) (scale-list (procedure (items factor) ((map (lambda (x) (* x factor)) items)) #3#)) (map (procedure (f items) ((if (null? items) (quote ()) (cons (f (car items)) (map f (cdr items))))) #3#)) (list-ref (procedure (items n) ((if (= n 0) (car items) (list-ref (cdr items) (- n 1)))) #3#)) (false #f) (true #t) (car (procedure (z) ((z (lambda (x y) x))) #3#)) (cdr (procedure (z) ((z (lambda (x y) y))) #3#)) (cons (procedure (x y) ((lambda #1# . #2#)) #3#)) (null? (primitive #<procedure:null?>)) (list (primitive #<procedure:mlist>)) (pair? (primitive #<procedure:mpair?>)) (+ (primitive #<procedure:+>)) (- (primitive #<procedure:->)) (* (primitive #<procedure:*>)) (/ (primitive #<procedure:/>)) (= (primitive #<procedure:=>)) (< (primitive #<procedure:<>)) (> (primitive #<procedure:>>)) (display (primitive #<procedure:mdisplay>)) (newline (primitive #<procedure:newline>)))))) (y (thunk (add-lists ones integers) #3#))) . #3#))
: (thunk x (((m (evaluated-thunk (procedure #4=(x y) #5=(x) (((z (evaluated-thunk #0=(procedure #1=(m) #2=((m x y)) #6=(((x (thunk 1 #3=(((integers #0#) (ones (procedure #1# #2# (((x (thunk 1 #3#)) (y (thunk ones #3#))) . #3#))) (add-lists (procedure (xs ys) ((cond ((null? xs) ys) ((null? ys) xs) (else (cons (+ (car xs) (car ys)) (add-lists (cdr xs) (cdr ys)))))) #3#)) (scale-list (procedure (items factor) ((map (lambda (x) (* x factor)) items)) #3#)) (map (procedure (f items) ((if (null? items) (quote ()) (cons (f (car items)) (map f (cdr items))))) #3#)) (list-ref (procedure (items n) ((if (= n 0) (car items) (list-ref (cdr items) (- n 1)))) #3#)) (false #f) (true #t) (car (procedure (z) ((z (lambda #4# . #5#))) #3#)) (cdr (procedure (z) ((z (lambda (x y) y))) #3#)) (cons (procedure (x y) ((lambda #1# . #2#)) #3#)) (null? (primitive #<procedure:null?>)) (list (primitive #<procedure:mlist>)) (pair? (primitive #<procedure:mpair?>)) (+ (primitive #<procedure:+>)) (- (primitive #<procedure:->)) (* (primitive #<procedure:*>)) (/ (primitive #<procedure:/>)) (= (primitive #<procedure:=>)) (< (primitive #<procedure:<>)) (> (primitive #<procedure:>>)) (display (primitive #<procedure:mdisplay>)) (newline (primitive #<procedure:newline>)))))) (y (thunk (add-lists ones integers) #3#))) . #3#))))) . #3#))))) . #6#))

To get the length of a finite stream, there'is no need to compute the actual value of elements.

#+begin_src racket
;<<lazy-list>>
(eval-lazy '(define (length lst)
              (define (iter xs acc)
                (if (null? xs) acc
                    (iter (cdr xs) (+ acc 1))))
              (iter lst 0)) global)
(actual-value '(length (cons 1 (cons (/ 1 0) '()))) global)
#+end_src

#+RESULTS:
: (ok ok ok ok ok ok ok ok ok)
: ok
: 2

*** 4.33

#+begin_src racket
;<<lazy-list>>
(eval-lazy '(car '(a b c)) global)
#+end_src

#+RESULTS:
: Unknown procedure type -- APPLY ((a b c) ((lambda (x y) x)))
:   context...:
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-dMNvh0.rkt"
: (ok ok ok ok ok ok ok ok ok ok)

This is because the evaluator regard `'` as a `quote`.

#+begin_src racket
;<<eval-core-exp>>
(define (x expr) (quoted? expr))
(x ''(a b c))
#+end_src

#+RESULTS:
: #t

So change the `eval-lazy`, make the branch handling the quoted expr to use `cons` to reconstruct the list.

#+begin_src racket :noweb-ref 4-33
(define (make-quote expr)
  (list 'quote expr))

(define (eval-lazy-4-33 expr env)
  (define (reconstruct-list-dynamically expr)
    ;<<fold>>
    (cond [(not (list? expr)) expr]
          [(null? expr) expr]
          [else (eval-lazy-4-33
                 (fold-right (lambda (x acc)
                               (cons 'cons (cons (make-quote x) (list acc))))
                             expr '()) env)]))
  (cond
    [(null? expr) expr]
    [(self-evaluating? expr) expr]
    [(variable? expr) (lookup-variable-value expr env)]
    [(quoted? expr) (reconstruct-list-dynamically (text-of-quotation expr))]           ;; CHANGED HERE
    [(assignment? expr) (eval-assignment expr env)]
    [(definition? expr) (eval-definition expr env)]
    [(lambda? expr)
     (make-procedure (lambda-parameters expr)
                     (scan-out-defines (lambda-body expr)) ; Exercise 4.16
                     env)]
    [(begin? expr)
     (eval-sequence (begin-actions expr) env)]
    [(if? expr) (eval-if-lazy expr env)]
    [(cond? expr) (eval-lazy (cond->if expr) env)]
    [(and? expr) (eval-and expr env)] ; and & or: Exercise 4.4
    [(or? expr) (eval-or expr env)]
    [(let? expr) (eval-lazy (let->combination expr) env)] ; let: Exercise 4.6
    [(let*? expr) (eval-lazy (let*->nested-lets expr) env)] ; let*: Exercise 4.7
    [(letrec? expr) (eval-lazy (letrec->let expr) env)] ; letrec: Exercise 4.20
    [(application? expr)
     (apply-lazy (actual-value (operator expr) env)
                 (operands expr)
                 env)]
    [else (error "Unknown expression type -- EVAL" expr)]))
#+end_src

#+begin_src racket :noweb-ref lazy-list-quote
;<<lazy-list>>
;<<4-33>>
(set! eval eval-lazy-4-33)
(set! eval-lazy eval-lazy-4-33)
#+end_src

#+begin_src racket
;<<lazy-list-quote>>
(actual-value '(car '(a b c)) global)
(actual-value '(car (cdr '(a b c))) global)
(actual-value '(list-ref '(a b c) 2) global)
(eval-lazy ''(a b c) global)
(actual-value ''() global)
(actual-value '(cdr '(a)) global)
#+end_src

#+RESULTS:
: (ok ok ok ok ok ok ok ok ok)
: a
: b
: c
: (procedure #0=(m) #1=((m x y)) (((x (thunk (quote a) #2=(((integers (procedure #0# #1# (((x (thunk 1 #2#)) (y (thunk (add-lists ones integers) #2#))) . #2#))) (ones (procedure #0# #1# (((x (thunk 1 #2#)) (y (thunk ones #2#))) . #2#))) (add-lists (procedure (xs ys) ((cond ((null? xs) ys) ((null? ys) xs) (else (cons (+ (car xs) (car ys)) (add-lists (cdr xs) (cdr ys)))))) #2#)) (scale-list (procedure (items factor) ((map (lambda (x) (* x factor)) items)) #2#)) (map (procedure (f items) ((if (null? items) (quote ()) (cons (f (car items)) (map f (cdr items))))) #2#)) (list-ref (procedure (items n) ((if (= n 0) (car items) (list-ref (cdr items) (- n 1)))) #2#)) (false #f) (true #t) (car (procedure (z) ((z (lambda (x y) x))) #2#)) (cdr (procedure (z) ((z (lambda (x y) y))) #2#)) (cons (procedure (x y) ((lambda #0# . #1#)) #2#)) (null? (primitive #<procedure:null?>)) (list (primitive #<procedure:mlist>)) (pair? (primitive #<procedure:mpair?>)) (+ (primitive #<procedure:+>)) (- (primitive #<procedure:->)) (* (primitive #<procedure:*>)) (/ (primitive #<procedure:/>)) (= (primitive #<procedure:=>)) (< (primitive #<procedure:<>)) (> (primitive #<procedure:>>)) (display (primitive #<procedure:mdisplay>)) (newline (primitive #<procedure:newline>)))))) (y (thunk (cons (quote b) (cons (quote c) ())) #2#))) . #2#))
: ()
: ()

*** 4.33

When the lazy list is not forced to evalute, the REPL should not print the forced value of its items. I'd like to use the "thunk" tag to express them.

#+begin_src racket
;<<eval-lazy-test>>

(define lazy-list-defs
  (list '(define the-empty-lazy-list
           (cons '() 'lazy-pair))
        '(define (lcons x y)
           (cons 'lazy-pair (lambda (m) (m x y))))
        '(define (lcar z)
           ((cdr z) (lambda (x y) x)))
        '(define (lcdr z)
           ((cdr z) (lambda (x y) y)))
        '(define (lend? lpair)
           (and (pair? lpair) (null? (car lpair)) (eq? (cdr lpair) 'lazy-pair)))
        '(define (lpair? z)
           (and (pair? z) (eq? (car z) 'lazy-pair)))
        '(define (list->llist xs)
           (if (null? xs) the-empty-lazy-list
               (lcons (car xs) (list->llist (cdr xs)))))
        '(define (llist->list xs)
           (if (lend? xs) '()
               (cons (lcar xs) (llist->list (lcdr xs)))))

        '(define (llist-take xs n)
           (if (= n 0) '()
               (cons (lcar xs) (llist-take (lcdr xs) (- n 1)))))

        '(define (llist-print-n lst n)
           (define (iter xs i)
             (cond [(< i 1) '()]
                   [(= i 1) (display (car xs)) (display ")")]
                   [else (display (car xs)) (display " ")
                         (iter (cdr xs) (- i 1))]))
           (display "(")
           (iter lst n))

        '(define ones (lcons 1 ones))
        ))
(map (lambda (expr) (eval-lazy expr global)) lazy-list-defs)

(define (format-thunk thunk)
  (list 'thunk (thunk-expr thunk)))

(define (format-output x env)
  (define (lazy-pair? x)
    (and (list? x) (eq? (car x) 'lazy-pair)))
  (if (lazy-pair? x)
      (format-lazy-pairs x env)
      x))

(define (format-lazy-pairs lst env)
  (define (iter xs i)
    (cond [(actual-value (list 'lend? (list 'quote xs)) env) '()]
          [(>= i 50) '...]
          [else
           (cons (format-thunk
                  (eval-lazy (list 'lcar (list 'quote xs)) env))
                 (iter
                  (actual-value (list 'lcdr (list 'quote xs)) env) (+ i 1))
                 )]))
  (cons 'lazy-list (iter lst 1)))

(actual-value '(list->llist '(a b c)) global)
(actual-value '(lend? (lcdr (lcons 'a the-empty-lazy-list))) global)

(format-output (actual-value '(lcons 'a the-empty-lazy-list) global) global)
(format-output (actual-value '(lcons 'b (lcons 'a the-empty-lazy-list)) global) global)
(format-output (actual-value '(list->llist '(a b c)) global) global)
(format-output (actual-value '(llist->list (list->llist '(a b c))) global) global)
(format-output (actual-value 'ones global) global)
(format-output (actual-value '(llist-take ones 4) global) global)
#+end_src

#+RESULTS:
: (ok ok ok ok ok ok ok ok ok ok ok)
: (lazy-pair procedure #0=(m) #1=((m x y)) (((x (thunk #3=(car xs) #5=(((xs (evaluated-thunk (a b c)))) . #2=(((ones (lazy-pair procedure #0# #1# (((x (thunk 1 #2#)) (y (thunk ones #2#))) . #2#))) (llist-print-n (procedure (lst n) ((let ((iter (quote *unassigned*))) (begin (set! iter (lambda (xs i) (cond ((< i 1) (quote ())) ((= i 1) (display (car xs)) (display ")")) (else (display (car xs)) (display " ") (iter (cdr xs) (- i 1)))))) (begin (display "(") (iter lst n))))) #2#)) (llist-take (procedure (xs n) ((if (= n 0) (quote ()) (cons (lcar xs) (llist-take (lcdr xs) (- n 1))))) #2#)) (llist->list (procedure (xs) ((if (lend? xs) (quote ()) (cons (lcar xs) (llist->list (lcdr xs))))) #2#)) (list->llist (procedure (xs) ((if (null? xs) the-empty-lazy-list (lcons #3# #4=(list->llist (cdr xs))))) #2#)) (lpair? (procedure (z) ((and (pair? z) (eq? (car z) (quote lazy-pair)))) #2#)) (lend? (procedure (lpair) ((and (pair? lpair) (null? (car lpair)) (eq? (cdr lpair) (quote lazy-pair)))) #2#)) (lcdr (procedure (z) (((cdr z) (lambda (x y) y))) #2#)) (lcar (procedure (z) (((cdr z) (lambda (x y) x))) #2#)) (lcons (procedure (x y) ((cons (quote lazy-pair) (lambda #0# . #1#))) #2#)) (the-empty-lazy-list (() . lazy-pair)) (false #f) (true #t) (car (primitive #<procedure:mcar>)) (cdr (primitive #<procedure:mcdr>)) (cons (primitive #<procedure:mcons>)) (null? (primitive #<procedure:null?>)) (list (primitive #<procedure:mlist>)) (pair? (primitive #<procedure:mpair?>)) (+ (primitive #<procedure:+>)) (- (primitive #<procedure:->)) (* (primitive #<procedure:*>)) (/ (primitive #<procedure:/>)) (= (primitive #<procedure:=>)) (< (primitive #<procedure:<>)) (> (primitive #<procedure:>>)) (display (primitive #<procedure:mdisplay>)) (newline (primitive #<procedure:newline>)) (eq? (primitive #<procedure:eq?>))))))) (y (thunk #4# #5#))) . #2#))
: #t
: (lazy-list (thunk x))
: (lazy-list (thunk x) (thunk x))
: (lazy-list (thunk x) (thunk x) (thunk x))
: (a b c)
: (lazy-list (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) (thunk x) . ...)
: (1 1 1 1)

Some examples in Racket language.

#+begin_src racket :lang racket
(define ones (stream-cons 1 ones))
(define ones-delayed (stream-cons (delay 1) ones-delayed))

(stream-take ones 5)
(stream->list (stream-take ones 5))

(stream->list (stream-take ones-delayed 5))
(map force (stream->list (stream-take ones-delayed 5)))
#+end_src

#+RESULTS:
: #<stream>
: '(1 1 1 1 1)
: '(#<promise:...org-babel-Tzq1hC.rkt:5:34> #<promise:...org-babel-Tzq1hC.rkt:5:34> #<promise:...org-babel-Tzq1hC.rkt:5:34> #<promise:...org-babel-Tzq1hC.rkt:5:34> #<promise:...org-babel-Tzq1hC.rkt:5:34>)
: '(1 1 1 1 1)

* 4.3 Variations on a Scheme -- Nondeterministic Computing

*** exp

`amb` syntax is defined in `#lang sicp` in Racket package.

#+begin_src racket
(list (amb 1 2 3) (amb 'a 'b))
#+end_src

#+RESULTS:
: (1 a)

#+begin_src racket
(amb 1 2 3)
(amb)
(amb)
(amb)
#+end_src

#+RESULTS:
: amb tree exhausted
:   context...:
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-XlsVa5.rkt"
: 1
: 2
: 3

This is not good that the amb raise an error when search is done exhaustively. I will try to handle it then.

#+begin_src racket :noweb-ref prime-sum-pair
(define (prime-sum-pair as bs)
  (let ([a (an-element-of as)]
        [b (an-element-of bs)])
    (require (prime? (+ a b)))
    (list a b)))

;<<amb-sicp>>
;<<an-element-of>>

(define (prime? x)
  (define (iter i)
    (cond [(> (floor (* i i)) x) #t]
          [(= (modulo x i) 0) #f]
          [else (iter (+ i 1))]))
  (if (or (and (not (= x 2)) (even? x))
          (= x 1)) #f
      (iter 3)))
#+end_src

#+begin_src racket
;<<prime-sum-pair>>

(prime-sum-pair '(1 3 5 8) '(20 35 110))
#+end_src

#+RESULTS:
: (3 20)

** 4.3.1 Amb and Search

*** exp

#+begin_src racket :noweb-ref amb-sicp
(define (require p)
  (if (not p) (amb)))
#+end_src

#+begin_src racket :noweb-ref an-element-of
(define (an-element-of items)
  (require (not (null? items)))
  (amb (car items) (an-element-of (cdr items))))
#+end_src

#+begin_src racket :noweb-ref an-integer-starting-from
(define (an-integer-starting-from n)
  (amb n (an-integer-starting-from (+ n 1))))
#+end_src

#+begin_src racket
;<<prime-sum-pair>>
(prime-sum-pair '(1 3 5 8) '(20 35 110))
(amb)
(amb)
(amb)
#+end_src

#+RESULTS:
: amb tree exhausted
:   context...:
:    c:\Users\asu\AppData\Local\Temp\org-babel-Dljd9b.rkt:4:0: prime-sum-pair
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-Dljd9b.rkt"
: (3 20)
: (3 110)
: (8 35)

*** try to handle amb error in `#lang sicp`

According to https://github.com/sicp-lang/sicp/blob/master/sicp/main.rkt, the `amb` will raise an `error` when search is end, and the `error` procedure is provide from `racket/base`. I should use some procedure to handle the error.

But it turns out that any procedure which once called `(amb)` won't do anything.

#+begin_src racket
(#%require (only racket with-handlers exn:fail?))

(define (amb-next-not-raise)
  (with-handlers ([exn:fail? identity])
    (amb)))
(define (amb-exaustively)
  (with-handlers ([exn:fail? identity])
    (amb)
    (amb-exaustively)))

(define (example)
  (display 'exp) (newline)
  (amb)
  (display 'exp) (newline)
  (amb)
  )

(amb 1 2 3 4)
(example)
#+end_src

#+RESULTS:
: 1
: exp
: 2

*** 4.35

#+begin_src racket :noweb-ref an-integer-between
(define (an-integer-between low high)
  (require (<= low high))
  (amb low (an-integer-between (+ low 1) high)))
#+end_src


#+begin_src racket
;<<amb-sicp>>
;<<an-integer-between>>
(define (a-pythagorean-triple-between low high)
  (let* ([i (an-integer-between low high)]
         [j (an-integer-between i high)]
         [k (an-integer-between j high)])
    (require (= (+ (* i i) (* j j)) (* k k)))
    (list i j k)))

(a-pythagorean-triple-between 1 5)
(amb)
#+end_src

#+RESULTS:
: amb tree exhausted
:   context...:
:    c:\Users\asu\AppData\Local\Temp\org-babel-uD53Q2.rkt:9:0: a-pythagorean-triple-between
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-uD53Q2.rkt"
: (3 4 5)

*** 4.36

If `(amb)` use DFS as the search strategy, simply replacing the `an-integer-between` to `an-integer-starting-from` will leads `(amb)` stick to endless path without any available result. Let me try to verify.

#+begin_src racket
;<<amb-sicp>>
;<<an-integer-starting-from>>
(define (pythagorean-triples-from low)
  (let* ([i (an-integer-starting-from low)]
         [j (an-integer-starting-from i)]
         [k (an-integer-starting-from j)])
    (if (> (max i j k)
           (* (min i j k) 1000))
        (begin (display (list i j k))
               (error 'endless-unavailable-path)))
    (require (= (+ (* i i) (* j j)) (* k k)))
    (list i j k)))

(pythagorean-triples-from 1)
#+end_src

#+RESULTS:
: error: endless-unavailable-path
:   context...:
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-PiM7xI.rkt"
: (1 1 1001)

Enumerate k first, so that amb can find proper i and j in a finite range.

#+begin_src racket
;<<amb-sicp>>
;<<an-integer-between>>
;<<an-integer-starting-from>>
(define (pythagorean-triples-from low)
  (let* ([k (an-integer-starting-from low)]
         [i (an-integer-between low k)]
         [j (an-integer-between i k)])
    (require (= (+ (* i i) (* j j)) (* k k)))
    (list i j k)))

(pythagorean-triples-from 1)
(amb)
(amb)
(amb)
(amb)
(amb)
#+end_src

#+RESULTS:
: (3 4 5)
: (6 8 10)
: (5 12 13)
: (9 12 15)
: (8 15 17)
: (12 16 20)

*** 4.37

This makes use of the equvalance relation to reduce inner loop (enumeration of `k`s), and pruning impossible branch `(>= hsq ksq)` of search to improve effeciency.

#+begin_src racket
(define (a-pythagorean-triple-between low high)
  (let ((i (an-integer-between low high))
        (hsq (* high high)))
    (let ((j (an-integer-between i high)))
      (let ((ksq (+ (* i i) (* j j))))
        (require (>= hsq ksq))
        (let ((k (sqrt ksq)))
          (require (integer? k))
          (list i j k))))))
#+end_src

** 4.3.2 Examples of Nondeterministic Programs

*** exp: Logic Puzzles

#+begin_src racket :noweb-ref distinct?
(define (distinct? items)
  (cond ((null? items) true)
        ((null? (cdr items)) true)
        ((member (car items) (cdr items)) false)
        (else (distinct? (cdr items)))))
#+end_src

#+begin_src racket
;<<amb-sicp>>
;<<distinct?>>

(define (multiple-dwelling)
  (let ([baker (amb 1 2 3 4 5)]
        [cooper (amb 1 2 3 4 5)]
        [fletcher (amb 1 2 3 4 5)]
        [miller (amb 1 2 3 4 5)]
        [smith (amb 1 2 3 4 5)])
    (require (distinct? (list baker cooper fletcher miller smith)))
    (require (not (= baker 5)))
    (require (not (= cooper 1)))
    (require (not (= fletcher 5)))
    (require (not (= fletcher 1)))
    (require (> miller cooper))
    (require (not (= (abs (- smith fletcher)) 1)))
    (require (not (= (abs (- fletcher cooper)) 1)))
    (list 'baker baker
          'cooper cooper
          'fletcher fletcher
          'miller miller
          'smith smith)))

(multiple-dwelling)
(amb)
#+end_src

#+RESULTS:
: amb tree exhausted
:   context...:
:    c:\Users\asu\AppData\Local\Temp\org-babel-h2Fk2o.rkt:12:0: multiple-dwelling
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-h2Fk2o.rkt"
: (baker 3 cooper 2 fletcher 4 miller 5 smith 1)

There is only one solution.

*** 4.38

#+begin_src racket
;<<amb-sicp>>
;<<distinct?>>
(define (multiple-dwelling)
  (let ([baker (amb 1 2 3 4 5)]
        [cooper (amb 1 2 3 4 5)]
        [fletcher (amb 1 2 3 4 5)]
        [miller (amb 1 2 3 4 5)]
        [smith (amb 1 2 3 4 5)])
    (require (distinct? (list baker cooper fletcher miller smith)))
    (require (not (= baker 5)))
    (require (not (= cooper 1)))
    (require (not (= fletcher 5)))
    (require (not (= fletcher 1)))
    (require (> miller cooper))
    ;(require (not (= (abs (- smith fletcher)) 1)))
    (require (not (= (abs (- fletcher cooper)) 1)))
    (list 'baker baker
          'cooper cooper
          'fletcher fletcher
          'miller miller
          'smith smith)))

(multiple-dwelling)
(amb)
(amb)
(amb)
(amb)
(amb)
#+end_src

#+RESULTS:
: amb tree exhausted
:   context...:
:    c:\Users\asu\AppData\Local\Temp\org-babel-DoJ9dw.rkt:11:0: multiple-dwelling
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-DoJ9dw.rkt"
: (baker 1 cooper 2 fletcher 4 miller 3 smith 5)
: (baker 1 cooper 2 fletcher 4 miller 5 smith 3)
: (baker 1 cooper 4 fletcher 2 miller 5 smith 3)
: (baker 3 cooper 2 fletcher 4 miller 5 smith 1)
: (baker 3 cooper 4 fletcher 2 miller 5 smith 1)

Five solutions.

*** 4.39

Assume a smaller scaled question: Baker, Fletcher, smith lives in each layer in a 3-layers-high buiding. Baker don't live in first floor.

Distinct filter first: 27 -> 6 -> 4. Enumerates $(27 - 6) + 6$.

Baker-don't-live-in-first-floor filter first: 27 -> 18 -> 4. Enumerates $(27 - 18) + 18$.

For more complicated conditions, after a filter layer, it becomes a simpler condition. And each layer the amb may continue or backtrace. All conitions would be explored, so it's better to let the amb backtraces early.

So, the front conditions should filter more conditions. This would be faster:

#+begin_src racket
;<<amb-sicp>>
;<<distinct?>>

(define (multiple-dwelling)
  (let ([baker (amb 1 2 3 4 5)]
        [cooper (amb 1 2 3 4 5)]
        [fletcher (amb 1 2 3 4 5)]
        [miller (amb 1 2 3 4 5)]
        [smith (amb 1 2 3 4 5)])
    (require (distinct? (list baker cooper fletcher miller smith)))
    (require (> miller cooper))
    (require (not (= (abs (- smith fletcher)) 1)))
    (require (not (= (abs (- fletcher cooper)) 1)))
    (require (and (not (= fletcher 5))
                  (not (= fletcher 1)))) ; combine these two
    (require (not (= baker 5)))
    (require (not (= cooper 1)))
    (list 'baker baker
          'cooper cooper
          'fletcher fletcher
          'miller miller
          'smith smith)))

(multiple-dwelling)
(amb)
#+end_src

#+RESULTS:
: amb tree exhausted
:   context...:
:    c:\Users\asu\AppData\Local\Temp\org-babel-o4cwcE.rkt:12:0: multiple-dwelling
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-o4cwcE.rkt"
: (baker 3 cooper 2 fletcher 4 miller 5 smith 1)

*** 4.40

The `distinct?` procedure reduce the posissibilties from $5^5=3125$ to $5+4+3+2=20$.

#+begin_src racket
;<<amb-sicp>>
;<<distinct?>>

(define (multiple-dwelling)
  (let     ([baker    (amb 1 2 3 4  )]
            [fletcher (amb   2 3 4  )]
            [cooper   (amb   2 3 4 5)])
        (require (not (= (abs (- fletcher cooper)) 1)))
    (let   ([smith    (amb 1 2 3 4 5)])
        (require (not (= (abs (- smith fletcher)) 1)))
      (let ([miller   (amb 1 2 3 4 5)])
        (require (> miller cooper))
        (require (distinct? (list baker cooper fletcher miller smith)))
        (list 'baker baker
              'cooper cooper
              'fletcher fletcher
              'miller miller
              'smith smith)))))

(multiple-dwelling)
(amb)
#+end_src

#+RESULTS:
: amb tree exhausted
:   context...:
:    c:\Users\asu\AppData\Local\Temp\org-babel-uq6q8H.rkt:12:0: multiple-dwelling
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-uq6q8H.rkt"
: (baker 3 cooper 2 fletcher 4 miller 5 smith 1)

*** 4.41

#+begin_src racket :lang racket
;<<distinct?>>
(define (enumerate2 xs ys)
  (stream-fold
   (lambda (acc x)
     (stream-append (stream-map (lambda (y) (cons x y)) ys) acc))
   empty-stream xs))
(define (enumerates . sss)
  (cond [(null? sss) (error "No input -- ENUMERATES" sss)]
        [(null? (cdr sss)) (car sss)]
        [else (enumerate2 (car sss) (apply enumerates (cdr sss)))]))

(define (repeat-stream x)
  (define res (stream-cons x res))
  res)

(define five (stream 1 2 3 4 5))

(define (pair->list ps)
  (if (not (pair? ps)) (list ps)
      (cons (car ps) (pair->list (cdr ps)))))

(define (pipe . args)
  (cond [(null? args) '<void>]
        [(null? (cdr args)) (car args)]
        [else (let ([obj (car args)] [fs (cdr args)])
                ((apply compose1 (reverse fs)) obj))]))

(define (multiple-dwelling)
  (define (baker-floor layers) (list-ref layers 0))
  (define (cooper-floor layers) (list-ref layers 1))
  (define (fletcher-floor layers) (list-ref layers 2))
  (define (miller-floor layers) (list-ref layers 3))
  (define (smith-floor layers) (list-ref layers 4))
  (define (adjacent? a b) (= (abs (- a b)) 1))
  (define (format-output l)
    (list
     'baker (baker-floor l)
     'cooper (cooper-floor l)
     'fletcher (fletcher-floor l)
     'miller (miller-floor l)
     'smith (smith-floor l)))
  (let ([conditions
         (stream-map
          pair->list
          (apply enumerates
                 (stream->list (stream-take (repeat-stream five) 5))))])
    (pipe (stream->list (stream-filter distinct? conditions))
          ((curry stream-filter) (lambda (l) (not (= (baker-floor l) 5))))
          ((curry stream-filter) (lambda (l) (not (= (cooper-floor l) 1))))
          ((curry stream-filter) (lambda (l) (and (not (= (fletcher-floor l) 5))
                                                  (not (= (fletcher-floor l) 1)))))
          ((curry stream-filter) (lambda (l) (> (miller-floor l) (cooper-floor l))))
          ;; ((curry stream-filter) (lambda (l) (not (adjacent? (smith-floor l)
          ;;                                                    (fletcher-floor l)))))
          ((curry stream-filter) (lambda (l) (not (adjacent? (fletcher-floor l)
                                                             (cooper-floor l)))))
          stream->list
          reverse ;; I found the reversed result is the same with Exercise 4.38
          ((curry for-each) (lambda (l) (displayln (format-output l))))
          )))

(multiple-dwelling)
#+end_src

#+RESULTS:
: (baker 1 cooper 2 fletcher 4 miller 3 smith 5)
: (baker 1 cooper 2 fletcher 4 miller 5 smith 3)
: (baker 1 cooper 4 fletcher 2 miller 5 smith 3)
: (baker 3 cooper 2 fletcher 4 miller 5 smith 1)
: (baker 3 cooper 4 fletcher 2 miller 5 smith 1)

*** 4.42

#+begin_src racket
;<<amb-sicp>>
;<<distinct?>>
(define (liars-puzzle)
  (define (one-true-one-untrue a b)
    (and (or a b) (not (and a b))))
  (let ([Betty (amb 1 2 3 4 5)]
        [Ethel (amb 1 2 3 4 5)]
        [Joan (amb 1 2 3 4 5)]
        [Kitty (amb 1 2 3 4 5)]
        [Mary (amb 1 2 3 4 5)])
    (require (distinct? (list Betty Ethel Joan Kitty Mary)))
    (require (one-true-one-untrue (= Kitty 2) (= Betty 3)))
    (require (one-true-one-untrue (= Ethel 1) (= Joan 2)))
    (require (one-true-one-untrue (= Kitty 2) (= Mary 4)))
    (require (one-true-one-untrue (= Mary 4) (= Betty 1)))
    (list 'Betty Betty
          'Ethel Ethel
          'Joan Joan
          'Kitty Kitty
          'Mary Mary)))

(liars-puzzle)
(amb)
#+end_src

#+RESULTS:
: amb tree exhausted
:   context...:
:    c:\Users\asu\AppData\Local\Temp\org-babel-LUs1fa.rkt:11:0: liars-puzzle
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-LUs1fa.rkt"
: (Betty 3 Ethel 5 Joan 2 Kitty 1 Mary 4)

*** 4.43

#+begin_src racket :noweb-ref 4-43
;<<amb-sicp>>
;<<distinct?>>
(define (his-yacht people)
  (cond [(eq? people 'Colonel-Downing) 'Mellisa]
        [(eq? people 'Mr.-Hall) 'Rosalind]
        [(eq? people 'Sir-Barnacle-Hood) 'Gabrielle]
        [(eq? people 'Dr.-Parker) 'Mary-Ann]
        [(eq? people 'Mr.-Moore) 'Lorna]
        [else (error "HIS-YACHT:" people)]))

#+end_src

#+begin_src racket
;<<4-43>>
(define (daughter-and-yacht)
  (let ([Mellisa-s-father                                   'Sir-Barnacle-Hood                        ]
        [Rosalind-s-father  (amb 'Colonel-Downing                              'Dr.-Parker           )]
        [Gabrielle-s-father (amb 'Colonel-Downing 'Mr.-Hall                    'Dr.-Parker           )]
        [Mary-Ann-s-father                                                                 'Mr.-Moore ]
        [Lorna-s-father     (amb 'Colonel-Downing 'Mr.-Hall                    'Dr.-Parker           )]
        [Dr.-Parker-s-daughter (amb          'Rosalind 'Gabrielle           'Lorna)])
    (require (distinct? (list                  Rosalind-s-father Gabrielle-s-father                   Lorna-s-father)))
    (require (eq? (his-yacht Gabrielle-s-father) Dr.-Parker-s-daughter))
    (list 'Mellisa   '& Mellisa-s-father   ': (his-yacht Mellisa-s-father) '*
          'Rosalind  '& Rosalind-s-father  ': (his-yacht Rosalind-s-father) '*
          'Gabrielle '& Gabrielle-s-father ': (his-yacht Gabrielle-s-father) '*
          'Mary-Ann  '& Mary-Ann-s-father  ': (his-yacht Mary-Ann-s-father) '*
          'Lorna     '& Lorna-s-father     ': (his-yacht Lorna-s-father))))

(daughter-and-yacht)
(amb)
(amb)
#+end_src

#+RESULTS:
: amb tree exhausted
:   context...:
:    c:\Users\asu\AppData\Local\Temp\org-babel-w142KT.rkt:19:0: daughter-and-yacht
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-w142KT.rkt"
: (Mellisa & Sir-Barnacle-Hood : Gabrielle * Rosalind & Colonel-Downing : Mellisa * Gabrielle & Mr.-Hall : Rosalind * Mary-Ann & Mr.-Moore : Lorna * Lorna & Dr.-Parker : Mary-Ann)
: (Mellisa & Sir-Barnacle-Hood : Gabrielle * Rosalind & Dr.-Parker : Mary-Ann * Gabrielle & Mr.-Hall : Rosalind * Mary-Ann & Mr.-Moore : Lorna * Lorna & Colonel-Downing : Mellisa)

Two solutions when I know Mary's father is Mr. Moore.

#+begin_src racket
;<<4-43>>
(define (daughter-and-yacht)
  (let ([Mellisa-s-father                                   'Sir-Barnacle-Hood                        ]
        [Rosalind-s-father  (amb 'Colonel-Downing                              'Dr.-Parker 'Mr.-Moore)]
        [Gabrielle-s-father (amb 'Colonel-Downing 'Mr.-Hall                    'Dr.-Parker 'Mr.-Moore)]
        [Mary-Ann-s-father  (amb 'Colonel-Downing 'Mr.-Hall                                'Mr.-Moore)]
        [Lorna-s-father     (amb 'Colonel-Downing 'Mr.-Hall                    'Dr.-Parker           )]
        [Dr.-Parker-s-daughter (amb          'Rosalind 'Gabrielle           'Lorna)])
    (require (distinct? (list                  Rosalind-s-father Gabrielle-s-father Mary-Ann-s-father Lorna-s-father)))
    (require (eq? (his-yacht Gabrielle-s-father) Dr.-Parker-s-daughter))
    (list 'Mellisa   '& Mellisa-s-father   ': (his-yacht Mellisa-s-father) '*
          'Rosalind  '& Rosalind-s-father  ': (his-yacht Rosalind-s-father) '*
          'Gabrielle '& Gabrielle-s-father ': (his-yacht Gabrielle-s-father) '*
          'Mary-Ann  '& Mary-Ann-s-father  ': (his-yacht Mary-Ann-s-father) '*
          'Lorna     '& Lorna-s-father     ': (his-yacht Lorna-s-father))))

(daughter-and-yacht)
(amb)
(amb)
(amb)
(amb)
(amb)
(amb)
#+end_src

#+RESULTS:
#+begin_example
amb tree exhausted
  context...:
   c:\Users\asu\AppData\Local\Temp\org-babel-Ld9pUJ.rkt:19:0: daughter-and-yacht
   body of "c:\Users\asu\AppData\Local\Temp\org-babel-Ld9pUJ.rkt"
(Mellisa & Sir-Barnacle-Hood : Gabrielle * Rosalind & Colonel-Downing : Mellisa * Gabrielle & Mr.-Hall : Rosalind * Mary-Ann & Mr.-Moore : Lorna * Lorna & Dr.-Parker : Mary-Ann)
(Mellisa & Sir-Barnacle-Hood : Gabrielle * Rosalind & Colonel-Downing : Mellisa * Gabrielle & Mr.-Moore : Lorna * Mary-Ann & Mr.-Hall : Rosalind * Lorna & Dr.-Parker : Mary-Ann)
(Mellisa & Sir-Barnacle-Hood : Gabrielle * Rosalind & Dr.-Parker : Mary-Ann * Gabrielle & Mr.-Hall : Rosalind * Mary-Ann & Mr.-Moore : Lorna * Lorna & Colonel-Downing : Mellisa)
(Mellisa & Sir-Barnacle-Hood : Gabrielle * Rosalind & Dr.-Parker : Mary-Ann * Gabrielle & Mr.-Moore : Lorna * Mary-Ann & Colonel-Downing : Mellisa * Lorna & Mr.-Hall : Rosalind)
(Mellisa & Sir-Barnacle-Hood : Gabrielle * Rosalind & Dr.-Parker : Mary-Ann * Gabrielle & Mr.-Moore : Lorna * Mary-Ann & Mr.-Hall : Rosalind * Lorna & Colonel-Downing : Mellisa)
(Mellisa & Sir-Barnacle-Hood : Gabrielle * Rosalind & Mr.-Moore : Lorna * Gabrielle & Mr.-Hall : Rosalind * Mary-Ann & Colonel-Downing : Mellisa * Lorna & Dr.-Parker : Mary-Ann)
#+end_example

6 solutions when I don't now Mary's family name is Moore.

*** 4.44

I tried to use quasiquote to generate some codes but failed because the `eval` requires environment which is different from the top-level. And different between `#lang sicp` list and `#lang racket`. I need to do more study then.

#+begin_src racket
;<<eight-queens>>
(define (gen-same-amb-bindings names definition)
  (map (lambda (n) (list n definition)) names))

(define env (scheme-report-environment 5))
(eval `(define (eight-queens-gen)
  (let (,(gen-same-amb-bindings (list 'q1 'q2 'q3 'q4 'q5 'q6 'q7 'q8) '(amb 1 2 3 4 5 6 7 8)))
    (require (distinct-by? (partial equal-by? line) (list q1 q2 q3 q4 q5 q6 q7 q8)))
    (require (distinct-by? in-cross? (list q1 q2 q3 q4 q5 q6 q7 q8)))
    (newline)
    (draw-board (list q1 q2 q3 q4 q5 q6 q7 q8) 8)))
      env)
(eval '(eight-queens-gen) env)
#+end_src

#+RESULTS:
: D:\scoop\apps\racket\current\share\pkgs\r5rs-lib\r5rs\main.rkt:326:7: let: bad syntax (not an identifier and expression for a binding)
:   at: {{q1 {amb 1 2 3 4 5 6 7 8}} {q2 {amb 1 2 3 4 5 6 7 8}} {q3 {amb 1 2 3 4 5 6 7 8}} {q4 {amb 1 2 3 4 5 6 7 8}} {q5 {amb 1 2 3 4 5 6 7 8}} {q6 {amb 1 2 3 4 5 6 7 8}} {q7 {amb 1 2 3 4 5 6 7 8}} {q8 {amb 1 2 3 4 5 6 7 8}}}
:   in: {let {{{q1 {amb 1 2 3 4 5 6 7 8}} {q2 {amb 1 2 3 4 5 6 7 8}} {q3 {amb 1 2 3 4 5 6 7 8}} {q4 {amb 1 2 3 4 5 6 7 8}} {q5 {amb 1 2 3 4 5 6 7 8}} {q6 {amb 1 2 3 4 5 6 7 8}} {q7 {amb 1 2 3 4 5 6 7 8}} {q8 {amb 1 2 3 4 5 6 7 8}}}} {r5rs:body {require {distinc...
:   context...:
:    D:\scoop\apps\racket\current\collects\racket\private\qq-and-or.rkt:101:61: loop
:    D:\scoop\apps\racket\current\collects\racket\private\qq-and-or.rkt:50:20: go
:    D:\scoop\apps\racket\current\share\pkgs\r5rs-lib\r5rs\main.rkt:351:24: loop
:    D:\scoop\apps\racket\current\share\pkgs\r5rs-lib\r5rs\main.rkt:336:2
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-VsV2cC.rkt"

Let me complete this exercise.

#+begin_src racket :noweb-ref eight-queens
;<<amb-sicp>>
;<<distinct?>>
;<<higher-order>>
(define (draw-board queens n)
  (define (draw-line q i)
    (cond [(= (line q) i) (display "👸") (draw-line q (+ i 1))]
          [(<= i n) (display "⬜") (draw-line q (+ i 1))]))
  (for-each (lambda (queen) (draw-line queen 1) (newline)) queens))

(define (memp f lst)
  (cond [(null? lst) #f]
        [(f (car lst)) lst]
        [else (memp f (cdr lst))]))

(define (distinct-by? eq-f items)
  (cond ((null? items) true)
        ((null? (cdr items)) true)
        ((memp (lambda (to-cmp) (eq-f (car items) to-cmp)) (cdr items)) false)
        (else (distinct-by? eq-f (cdr items)))))

(define (equal-by? key a b)
  (equal? (key a) (key b)))
(define partial (F 'partial))

(define (row pos) (car pos))
(define (line pos) (cadr pos))
(define (in-cross? a b)
  (= (abs (- (line a) (line b))) (abs (- (row a) (row b)))))

(define (eight-queens)
  (let ([q1 (amb '(1 1) '(1 2) '(1 3) '(1 4) '(1 5) '(1 6) '(1 7) '(1 8))]
        [q2 (amb '(2 1) '(2 2) '(2 3) '(2 4) '(2 5) '(2 6) '(2 7) '(2 8))]
        [q3 (amb '(3 1) '(3 2) '(3 3) '(3 4) '(3 5) '(3 6) '(3 7) '(3 8))]
        [q4 (amb '(4 1) '(4 2) '(4 3) '(4 4) '(4 5) '(4 6) '(4 7) '(4 8))]
        [q5 (amb '(5 1) '(5 2) '(5 3) '(5 4) '(5 5) '(5 6) '(5 7) '(5 8))]
        [q6 (amb '(6 1) '(6 2) '(6 3) '(6 4) '(6 5) '(6 6) '(6 7) '(6 8))]
        [q7 (amb '(7 1) '(7 2) '(7 3) '(7 4) '(7 5) '(7 6) '(7 7) '(7 8))]
        [q8 (amb '(8 1) '(8 2) '(8 3) '(8 4) '(8 5) '(8 6) '(8 7) '(8 8))])
    (require (distinct-by? (partial equal-by? line) (list q1 q2 q3 q4 q5 q6 q7 q8)))
    (require (distinct-by? in-cross? (list q1 q2 q3 q4 q5 q6 q7 q8)))
    (newline)
    (draw-board (list q1 q2 q3 q4 q5 q6 q7 q8) 8)))
#+end_src

#+begin_src racket
;<<eight-queens>>
(eight-queens)
(amb)
#+end_src

#+RESULTS:
#+begin_example

👸⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜👸⬜⬜⬜
⬜⬜⬜⬜⬜⬜⬜👸
⬜⬜⬜⬜⬜👸⬜⬜
⬜⬜👸⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜👸⬜
⬜👸⬜⬜⬜⬜⬜⬜
⬜⬜⬜👸⬜⬜⬜⬜

👸⬜⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜👸⬜⬜
⬜⬜⬜⬜⬜⬜⬜👸
⬜⬜👸⬜⬜⬜⬜⬜
⬜⬜⬜⬜⬜⬜👸⬜
⬜⬜⬜👸⬜⬜⬜⬜
⬜👸⬜⬜⬜⬜⬜⬜
⬜⬜⬜⬜👸⬜⬜⬜
#+end_example

The results of 8-queens problem are too many to display. Let me try all solutions of 4-queens then.

#+begin_src racket
;<<eight-queens>>
(define (four-queens)
  (let ([q1 (amb '(1 1) '(1 2) '(1 3) '(1 4))]
        [q2 (amb '(2 1) '(2 2) '(2 3) '(2 4))]
        [q3 (amb '(3 1) '(3 2) '(3 3) '(3 4))]
        [q4 (amb '(4 1) '(4 2) '(4 3) '(4 4))])
    (require (distinct-by? (partial equal-by? line) (list q1 q2 q3 q4)))
    (require (distinct-by? in-cross? (list q1 q2 q3 q4)))
    (newline)
    (draw-board (list q1 q2 q3 q4) 4)))

(four-queens)
(amb)
(amb)
#+end_src

#+RESULTS:
#+begin_example
amb tree exhausted
  context...:
   c:\Users\asu\AppData\Local\Temp\org-babel-605Ye6.rkt:72:0: four-queens
   body of "c:\Users\asu\AppData\Local\Temp\org-babel-605Ye6.rkt"

⬜👸⬜⬜
⬜⬜⬜👸
👸⬜⬜⬜
⬜⬜👸⬜

⬜⬜👸⬜
👸⬜⬜⬜
⬜⬜⬜👸
⬜👸⬜⬜
#+end_example

*** exp: Parsing Natural Language

#+begin_src racket :noweb-ref sentence-dataset
(define nouns '(noun student professor cat class))
(define verbs '(verb studies lectures eats sleeps))
(define articles '(article the a))

(define prepositions '(prep for to in by with))
#+end_src

#+begin_src racket :noweb-ref sentence
;<<amb-sicp>>
(define (parse-sentence)
  (list 'sentence
        (parse-noun-phrase)
        (parse-verb-phrase)))

(define (parse-simple-noun-phrase)
  (list 'simple-noun-phrase
        (parse-word articles)
        (parse-word nouns)))

(define (parse-noun-phrase)
  (define (maybe-extend noun-phrase)
    (amb noun-phrase
         (maybe-extend (list 'noun-phrase
                             noun-phrase
                             (parse-prepositional-phrase)))))
  (maybe-extend (parse-simple-noun-phrase)))

(define (parse-prepositional-phrase)
  (list 'prep-phrase
        (parse-word prepositions)
        (parse-noun-phrase)))

(define (parse-verb-phrase)
  (define (maybe-extend verb-phrase)
    (amb verb-phrase
         (maybe-extend (list 'verb-phrase
                             verb-phrase
                             (parse-prepositional-phrase)))))
  (maybe-extend (parse-word verbs)))

(define (parse-word word-list)
  (require (not (null? *unparsed*)))
  (require (memq (car *unparsed*) (cdr word-list)))
  (let ([found-word (car *unparsed*)])
    (set! *unparsed* (cdr *unparsed*))
    (list (car word-list) found-word)))

(define *unparsed* '())
(define (parse input)
  (set! *unparsed* input)
  (let ([sent (parse-sentence)])
    (require (null? *unparsed*))
    sent))
#+end_src

#+begin_src racket
;<<sentence>>
;<<sentence-dataset>>
(parse '(the cat eats))
(parse '(the student with the cat sleeps in the class))
#+end_src

#+RESULTS:
: (sentence (simple-noun-phrase (article the) (noun cat)) (verb eats))
: (sentence (noun-phrase (simple-noun-phrase (article the) (noun student)) (prep-phrase (prep with) (simple-noun-phrase (article the) (noun cat)))) (verb-phrase (verb sleeps) (prep-phrase (prep in) (simple-noun-phrase (article the) (noun class)))))

According to the Book, parsing a sentence with more meanings require `amb`'s ability to backtrace the change of `set!`'s side effect. Obviously the `amb` in `#lang sicp` can't do it.

#+begin_src racket
;<<sentence>>
;<<sentence-dataset>>
(parse '(the professor lectures to the student with the cat))
(amb)
#+end_src

#+RESULTS:
: amb tree exhausted
:   context...:
:    c:\Users\asu\AppData\Local\Temp\org-babel-uHeuQ1.rkt:6:0: parse-sentence
:    c:\Users\asu\AppData\Local\Temp\org-babel-uHeuQ1.rkt:45:0: parse
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-uHeuQ1.rkt"
: (sentence (simple-noun-phrase (article the) (noun professor)) (verb-phrase (verb-phrase (verb lectures) (prep-phrase (prep to) (simple-noun-phrase (article the) (noun student)))) (prep-phrase (prep with) (simple-noun-phrase (article the) (noun cat)))))

I tried to reconstruct codes, to make it do not depends on the global variable and `set!` side effects. Then I found that it would totally change the structure of the codes and the `amb` becomes to a needless.

*** 4.45

"The professor lectures to the student in the class with the cat."

1. The professor takes a cat to lecture:
   "The professor lectures (to the student) in the class with the cat."

2. The student take a cat to having a lecture:
   "The professor lectures (to the student) in the class (with the cat)."

3. The student is already in the classroom, waiting the professor and his/her cat.
   "The professor lectures (to the student in the class) with the cat."

4. The student with a cat is already in the classroom, waiting the professor:
   "The professor lectures (to the student in the class with the cat)."

5. The same meaning with 1, but the parser thinks they are different:
   "[The professor lectures] to the student [in the class with the cat]."

*** 4.46

Let me focus on one procedure:

#+begin_src racket
(define (parse-noun-phrase)
  (define (maybe-extend noun-phrase)
    (amb noun-phrase
         (maybe-extend (list 'noun-phrase
                             noun-phrase
                             (parse-prepositional-phrase)))))
  (maybe-extend (parse-simple-noun-phrase)))
#+end_src

If the `amb` always choose the second options in this procedure, it will runs into endless recursion.

*** 4.47

#+begin_src racket
;<<sentence>>
;<<sentence-dataset>>
(define (parse-verb-phrase-4-47)
  (amb (parse-word verbs)
       (list 'verb-phrase
             (parse-verb-phrase-4-47)
             (parse-prepositional-phrase))))
(set! parse-verb-phrase parse-verb-phrase-4-47)

(parse '(the professor lectures to a student with a cat))
#+end_src

#+RESULTS:
: out of memory

I uncarefully run the code and my computer get stucked... For a few seconds.

#+begin_src racket
(define (parse-verb-phrase)
  (define (maybe-extend verb-phrase)
    (amb verb-phrase
         (maybe-extend (list 'verb-phrase
                             verb-phrase
                             (parse-prepositional-phrase)))))
  (maybe-extend (parse-word verbs)))
#+end_src

Comparing the two, the original version saves the result of `(parse-word verbs)` into a varialbe `verb-phrase`, but this version do not. So every time calls the `parse-verb-phrase-4-47`, the expr will be computed. `amb` choose left then failed, so goto the right; but the right needs to choose left again. This makes endless recursion, no matter the choosing order of `amb`.

*** 4.48

#+begin_src racket
;<<sentence>>
;<<sentence-dataset>>
(define adjectives '(adj lazy intelligent))
(define adverbs '(adv hard happily))

(define (parse-simple-noun-phrase-4-48)
  (amb
   (list 'simple-noun-phrase
        (parse-word articles)
        (parse-word nouns))
   (list 'simple-noun-phrase
        (parse-word articles)
        (parse-word adjectives)
        (parse-word nouns))))

(define (parse-verb-phrase-4-48)
  (define (maybe-extend verb-phrase)
    (amb verb-phrase
         (maybe-extend (list 'verb-phrase
                             verb-phrase
                             (parse-prepositional-phrase)))
         (maybe-extend (list 'verb-phrase
                             verb-phrase
                             (parse-prepositional-phrase)
                             (parse-word adverbs)))))
  (maybe-extend (parse-word verbs)))
(set! parse-simple-noun-phrase parse-simple-noun-phrase-4-48)
(set! parse-verb-phrase parse-verb-phrase-4-48)

(parse '(the professor lectures to the student with the cat))
(parse '(the professor lectures to the student with the cat happily))
(parse '(the intelligent professor lectures to the student with the lazy cat happily))
#+end_src

#+RESULTS:
: amb tree exhausted
:   context...:
:    c:\Users\asu\AppData\Local\Temp\babel-9MzPVt\org-babel-Dmjbus.rkt:16:0: parse-noun-phrase
:    c:\Users\asu\AppData\Local\Temp\babel-9MzPVt\org-babel-Dmjbus.rkt:6:0: parse-sentence
:    c:\Users\asu\AppData\Local\Temp\babel-9MzPVt\org-babel-Dmjbus.rkt:45:0: parse
:    body of "c:\Users\asu\AppData\Local\Temp\babel-9MzPVt\org-babel-Dmjbus.rkt"
: (sentence (simple-noun-phrase (article the) (noun professor)) (verb-phrase (verb-phrase (verb lectures) (prep-phrase (prep to) (simple-noun-phrase (article the) (noun student)))) (prep-phrase (prep with) (simple-noun-phrase (article the) (noun cat)))))

It blames to the `amb` cannot backtrace the side effect of `set!`.

*** 4.49

#+begin_src racket
;<<sentence>>
;<<sentence-dataset>>
;<<an-element-of>>
(define (parse-word-and-generate word-list)
  (require (not (null? *unparsed*)))
  (require (memq (car *unparsed*) (cdr word-list)))
  (set! *unparsed* (cdr *unparsed*))
  (list (car word-list) (an-element-of (cdr word-list))))

(define (generate input-structure)  ;; Well, this do the same with `parse`
  (set! *unparsed* input-structure) ;; procedure, I just change the variable
  (let ([sent (parse-sentence)])    ;; name.
    (require (null? *unparsed*))
    sent))

(set! parse-word parse-word-and-generate)

(generate '(the professor lectures to the student with the cat))
(amb)
(amb)
(amb)
(amb)
(amb)
(amb)
(amb)
(amb)
(amb)
(amb)
(amb)
#+end_src

#+RESULTS:
#+begin_example
amb tree exhausted
  context...:
   c:\Users\asu\AppData\Local\Temp\babel-9MzPVt\org-babel-CE3FUI.rkt:58:0: parse-word-and-generate
   c:\Users\asu\AppData\Local\Temp\babel-9MzPVt\org-babel-CE3FUI.rkt:16:0: parse-noun-phrase
   c:\Users\asu\AppData\Local\Temp\babel-9MzPVt\org-babel-CE3FUI.rkt:6:0: parse-sentence
   c:\Users\asu\AppData\Local\Temp\babel-9MzPVt\org-babel-CE3FUI.rkt:64:0: generate
   body of "c:\Users\asu\AppData\Local\Temp\babel-9MzPVt\org-babel-CE3FUI.rkt"
(sentence (simple-noun-phrase (article the) (noun student)) (verb-phrase (verb-phrase (verb studies) (prep-phrase (prep for) (simple-noun-phrase (article the) (noun student)))) (prep-phrase (prep for) (simple-noun-phrase (article the) (noun student)))))
(sentence (simple-noun-phrase (article the) (noun student)) (verb-phrase (verb-phrase (verb studies) (prep-phrase (prep for) (simple-noun-phrase (article the) (noun student)))) (prep-phrase (prep for) (simple-noun-phrase (article the) (noun professor)))))
(sentence (simple-noun-phrase (article the) (noun student)) (verb-phrase (verb-phrase (verb studies) (prep-phrase (prep for) (simple-noun-phrase (article the) (noun student)))) (prep-phrase (prep for) (simple-noun-phrase (article the) (noun cat)))))
(sentence (simple-noun-phrase (article the) (noun student)) (verb-phrase (verb-phrase (verb studies) (prep-phrase (prep for) (simple-noun-phrase (article the) (noun student)))) (prep-phrase (prep for) (simple-noun-phrase (article the) (noun class)))))
(sentence (simple-noun-phrase (article the) (noun student)) (verb-phrase (verb studies) (prep-phrase (prep for) (simple-noun-phrase (article the) (noun professor)))))
(sentence (simple-noun-phrase (article the) (noun student)) (verb-phrase (verb studies) (prep-phrase (prep for) (simple-noun-phrase (article the) (noun cat)))))
(sentence (simple-noun-phrase (article the) (noun student)) (verb-phrase (verb studies) (prep-phrase (prep for) (simple-noun-phrase (article the) (noun class)))))
(sentence (simple-noun-phrase (article the) (noun student)) (verb lectures))
(sentence (simple-noun-phrase (article the) (noun student)) (verb eats))
(sentence (simple-noun-phrase (article the) (noun student)) (verb sleeps))
#+end_example

* 4.3.3 Implemeting the `Amb` Evaluator

*** exp

#+begin_src racket :noweb-ref eval-amb
(define (amb? expr) (tagged-list? expr 'amb))
(define (amb-choices expr) (cdr expr))

(define (ambeval expr env succeed fail)
  ((analyze expr) env succeed fail))

(define (analyze expr)
  (cond [(self-evaluating? expr) (analyze-self-evaluating expr)]
        [(quoted? expr) (analyze-quoted expr)]
        [(variable? expr) (analyze-variable expr)]
        [(assignment? expr) (analyze-assignment expr)]
        [(definition? expr) (analyze-definition expr)]
        [(if? expr) (analyze-if expr)]
        [(lambda? expr) (analyze-lambda expr)]
        [(begin? expr) (analyze-sequence (begin-actions expr))]
        [(cond? expr) (analyze (cond->if expr))]
        [(let? expr) (analyze (let->combination expr))]         ; let: Exercise 4.22
        [(amb? expr) (analyze-amb expr)]
        [(ramb? expr) (analyze-ramb expr)]                      ; ramb: Exercise 4.50
        [(if-fail? expr) (analyze-if-fail expr)]                ; if-fail: Exercise 4.52
        [(permanent-assignment? expr) (analyze-permanent-assignment expr)] ; permanent-set!: Exercise 4.51
        [(require? expr) (analyze-require expr)]               ; require: Exercise 4.54
        [(application? expr) (analyze-application expr)]
        [else (error "Unknown expression type -- ANALYZE" expr)]))
#+end_src

This below description of type of the analyzed amb expr, may be the best part in this book to make me miss a typed programming language. Use this form to express type is a real humour for me...

#+begin_src racket
(lambda (env succeed fail)
  ;; succeed is (lambda (value fail) ...)
  ;; fail is (lambda () ...)
...)
#+end_src

#+begin_src racket :noweb-ref eval-amb
(define (analyze-self-evaluating expr)
  (lambda (env succeed fail)
    (succeed expr fail)))

(define (analyze-quoted expr)
  (let ([qval (text-of-quotation expr)])
    (lambda (env succeed fail)
      (succeed qval fail))))

(define (analyze-variable expr)
  (lambda (env succ fail)
    (succ (lookup-variable-value expr env) fail)))

(define (analyze-lambda expr)
  (let ([vars (lambda-parameters expr)]
        [bproc (analyze-sequence (lambda-body expr))])
    (lambda (env succ fail)
      (succ (make-procedure vars bproc env) fail))))
#+end_src

#+begin_src racket :noweb-ref eval-amb
(define (analyze-if expr)
  (let ([pproc (analyze (if-predicate expr))]
        [cproc (analyze (if-consequent expr))]
        [aproc (analyze (if-alternative expr))])
    (lambda (env succ fail)
      (pproc env
             (lambda (pred-value failp)
               (if (true? pred-value)
                   (cproc env succ failp)
                   (aproc env succ failp)))
             fail))))

(define (analyze-sequence expr)
  (define (sequentially a b)
    (lambda (env succ fail)
      (a env
         (lambda (a-value faila)
           (b env succ faila))
         fail)))
  (define (loop first-proc rest-procs)
    (if (null? rest-procs)
        first-proc
        (loop (sequentially first-proc (car rest-procs))
              (cdr rest-procs))))
  (let ([procs (map analyze expr)])
    (if (null? procs)
        (error "Empty sequence -- ANALYZE"))
    (loop (car procs) (cdr procs))))
#+end_src

#+begin_src racket :noweb-ref eval-amb
(define (analyze-definition expr)
  (let ([var (definition-variable expr)]
        [vproc (analyze (definition-value expr))])
    (lambda (env succ fail)
      (vproc env
             (lambda (val failv)
               (define-variable! var val env)
               (succ 'ok failv))
             fail))))

(define (analyze-assignment expr)
  (let ([var (assignment-variable expr)]
        [vproc (analyze (assignment-value expr))])
    (lambda (env succ fail)
      (vproc env
             (lambda (val failv)
               (let ([old-value (lookup-variable-value var env)])
                 (set-variable-value! var val env)
                 (succ 'ok
                       (lambda ()
                         (set-variable-value! var old-value env)
                         (failv)))))
             fail))))
#+end_src

#+begin_src racket :noweb-ref eval-amb
(define (analyze-application expr)
  (let ([fproc (analyze (operator expr))]
        [aprocs (map analyze (operands expr))])
    (lambda (env succ fail)
      (fproc env
             (lambda (proc failf)
               (get-args aprocs
                         env
                         (lambda (args failg)
                           (execute-application
                            proc args succ failg))
                         failf))
             fail))))

(define (get-args aprocs env succ fail)
  (if (null? aprocs)
      (succ '() fail)
      ((car aprocs) env
                    (lambda (arg faila)
                      (get-args (cdr aprocs)
                                env
                                (lambda (args fail-rest)
                                  (succ (cons arg args)
                                        fail-rest))
                                faila))
                      fail)))

(define (execute-application proc args succ fail)
  (cond [(primitive-procedure? proc)
         (succ (apply-primitive-procedure proc args) fail)]
        [(compound-procedure? proc)
         ((procedure-body proc)
          (extend-environment (procedure-parameters proc)
                              args
                              (procedure-environment proc))
          succ fail)]
        [else (error "Unknown procedure type -- EXECUTE-APPLICATION" proc)]))
#+end_src

#+begin_src racket :noweb-ref eval-amb
(define (analyze-amb expr)
  (let ([cprocs (map analyze (amb-choices expr))])
    (lambda (env succ fail)
      (define (try-next choices)
        (if (null? choices)
            (fail)
            ((car choices) env
                           succ
                           (lambda ()
                             (try-next (cdr choices))))))
      (try-next cprocs))))
#+end_src

#+begin_src racket :tangle "4.3.3-repl.rkt" :results none
;<<eval-core-exp>>
;<<repl-exp>>
;<<eval-amb>>

(define the-global-environment (setup-environment))

(define (amb-repl-scope)
  (define input-prompt ";;; Amb-Eval input:")
  (define output-prompt ";;; Amb-Eval output:")

  (define (driver-loop)
    (define (internal-loop try-again)
      (prompt-for-input input-prompt)
      (let ([input (read)])
        (if (eq? input 'try-again)
            (try-again)
            (begin
              (newline)
              (display ";;; Starting a new problem")
              (ambeval input
                       the-global-environment
                       (lambda (val next-alternative)
                         (announce-output output-prompt)
                         (user-print val)
                         (internal-loop next-alternative))
                       (lambda ()
                         (announce-output ";;; There are no more value of")
                         (user-print input)
                         (driver-loop)))))))
    (internal-loop
     (lambda ()
       (newline)
       (display ";;; There is no current problem")
       (driver-loop))))
  (driver-loop)
)

(amb-repl-scope)
#+end_src

*** exp

The driver loop calls the `fail` handler only when input `try-again` in REPL. Let me make some helper functions to make ambeval system more usable.

#+begin_src racket :noweb-ref eval-amb-test
;<<eval-core-exp>>
;<<eval-amb>>
(set! eval ambeval)
(define global (setup-environment))

(define (ambeval-handle expr env)
  (define do-nothing-handle (lambda () '<void>))
  (ambeval expr
           env
           (lambda (val fail-handle)
             (display val) (newline)
             fail-handle)
           (lambda ()
             (display "Amb tree exhausted: ")
             (display expr)
             (newline)
             do-nothing-handle)))

(define (try-handle fail-handle times)
  (if (<= times 0) 'ok
      (try-handle (fail-handle) (- times 1))))

(define (try-ambeval expr env times)
  (try-handle (ambeval-handle expr env) (- times 1)))

(define amb-fail #f)
(define (amb-new handle) (set! amb-fail handle))
(define (amb) (set! amb-fail (amb-fail)))
#+end_src

#+begin_src racket
;<<eval-amb-test>>
(define handle (ambeval-handle '(amb 1 2) global)) ; display 1
(handle)   ; display 2
((handle)) ; display 2 and exhausted message

(try-ambeval '(amb 1 2 3) global 4)
#+end_src

#+RESULTS:
#+begin_example
1
2
#<procedure:...rg-babel-8Hs4O7.rkt:518:27>
2
Amb tree exhausted: (amb 1 2)
#<procedure:...rg-babel-8Hs4O7.rkt:558:28>
1
2
3
Amb tree exhausted: (amb 1 2 3)
done
#+end_example

#+begin_src racket
;<<eval-amb-test>>
(amb-new (ambeval-handle '(amb 1 2) global))
(amb)
(amb)
#+end_src

#+RESULTS:
: 1
: 2
: Amb tree exhausted: (amb 1 2)

*** extra exp: `amb` in `#lang sicp`

Before implementing accompany with book, I took a quick look at the implementation of `#lang sicp` in https://github.com/sicp-lang/sicp/blob/master/sicp/main.rkt.

#+begin_src racket :lang racket :noweb-ref amb-racket
(require r5rs)

(define (amb-fail) (error "amb tree exhausted"))
(define (set-amb-fail! x) (set! amb-fail x))

(define-syntax-rule (explore +prev-amb-fail +sk alt)
  (call/cc
   (lambda (+fk)
     (set-amb-fail!
      (thunk
       (set-amb-fail! +prev-amb-fail)
       (+fk 'fail)))
     (+sk alt))))

(define-syntax-rule (amb alt ...)
  (let ([+prev-amb-fail amb-fail])
    (call/cc
     (lambda (+sk)
       (explore +prev-amb-fail +sk alt) ...
       (+prev-amb-fail)))))
#+end_src

Well, I can't understand this. It is said that the `call/cc` manipulates the context of continuation, capture the control state, though it won't memorize the state of the global variables. So this version is different from the version in Book 4.3.3 on tracebacking with procedures with side effects.

#+begin_src racket :lang racket
;<<amb-racket>>
(define x 0)
(define (id-set-x! v) (set! x v) v)
(define (show-x) (display "x: ") (displayln x))
(amb 1 2 (id-set-x! 3)) ; => 1
(amb (id-set-x! 'x))                ; => x
(show-x)
(amb)                               ; => 2
(show-x) ; display 0 if amb traceback the side effect
(amb)
#+end_src

#+RESULTS:
: 1
: 'x
: x: x
: 2
: x: x
: 3

#+begin_src racket
;<<eval-amb-test>>
(ambeval-handle '(define x 0) global)
(ambeval-handle '(define (show-x) (display "x: ") (display x)) global)
(ambeval-handle '(define (id-set-x! v) (set! x v) v) global)
(ambeval-handle '(show-x) global)
(amb-new (ambeval-handle '(amb (id-set-x! 1) 2) global))
(ambeval-handle '(show-x) global)
(amb)
(ambeval-handle '(show-x) global)
(amb)
#+end_src

#+RESULTS:
#+begin_example
ok
#<procedure:...rg-babel-GIMGNi.rkt:576:11>
ok
#<procedure:...rg-babel-GIMGNi.rkt:576:11>
ok
#<procedure:...rg-babel-GIMGNi.rkt:576:11>
x: 0#<void>
#<procedure:...rg-babel-GIMGNi.rkt:576:11>
1
x: 1#<void>
#<procedure:...rg-babel-GIMGNi.rkt:576:11>
2
x: 0#<void>
#<procedure:...rg-babel-GIMGNi.rkt:576:11>
Amb tree exhausted: (amb (id-set-x! 1) 2)
#+end_example

*** again: Parsing Natural Language

Let me use this version of `amb` to run the codes in Book 4.3.2.

#+begin_src racket :results none :noweb-ref sentence-4-3-3
;<<eval-amb-test>>
;<<higher-order>>

(ambeval-handle '(define (require p)
                   (if (not p) (amb))) global)

(for-each ((F 'partial) ((F 'flip) ambeval-handle) global)
          (list
           '(define nouns '(noun student professor cat class))
           '(define verbs '(verb studies lectures eats sleeps))
           '(define articles '(article the a))
           '(define prepositions '(prep for to in by with))

           '(define (parse-sentence)
              (list 'sentence
                    (parse-noun-phrase)
                    (parse-verb-phrase)))

           '(define (parse-simple-noun-phrase)
              (list 'simple-noun-phrase
                    (parse-word articles)
                    (parse-word nouns)))

           '(define (parse-noun-phrase)
              (define (maybe-extend noun-phrase)
                (amb noun-phrase
                     (maybe-extend (list 'noun-phrase
                                         noun-phrase
                                         (parse-prepositional-phrase)))))
              (maybe-extend (parse-simple-noun-phrase)))

           '(define (parse-prepositional-phrase)
              (list 'prep-phrase
                    (parse-word prepositions)
                    (parse-noun-phrase)))

           '(define (parse-verb-phrase)
              (define (maybe-extend verb-phrase)
                (amb verb-phrase
                     (maybe-extend (list 'verb-phrase
                                         verb-phrase
                                         (parse-prepositional-phrase)))))
              (maybe-extend (parse-word verbs)))

           '(define (parse-word word-list)
              (require (not (null? *unparsed*)))
              (require (memq (car *unparsed*) (cdr word-list)))
              (let ([found-word (car *unparsed*)])
                (set! *unparsed* (cdr *unparsed*))
                (list (car word-list) found-word)))

           '(define *unparsed* '())
           '(define (parse input)
              (set! *unparsed* input)
              (let ([sent (parse-sentence)])
                (require (null? *unparsed*))
                sent))
           ))
#+end_src

#+begin_src racket
;<<sentence-4-3-3>>
(ambeval-handle '(parse '(the cat eats)) global)
(ambeval-handle '(parse '(the student with the cat sleeps in the class)) global)

(newline) (display "Two possibilities:") (newline)
(try-ambeval '(parse '(the professor lectures to the student with the cat)) global 3)
#+end_src

#+RESULTS:
#+begin_example
ok
#<procedure:...rg-babel-rK0QVu.rkt:576:11>
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
ok
(sentence (simple-noun-phrase (article the) (noun cat)) (verb eats))
#<procedure:...rg-babel-rK0QVu.rkt:520:27>
(sentence (noun-phrase (simple-noun-phrase (article the) (noun student)) (prep-phrase (prep with) (simple-noun-phrase (article the) (noun cat)))) (verb-phrase (verb sleeps) (prep-phrase (prep in) (simple-noun-phrase (article the) (noun class)))))
#<procedure:...rg-babel-rK0QVu.rkt:520:27>

Two possibilities:
(sentence (simple-noun-phrase (article the) (noun professor)) (verb-phrase (verb-phrase (verb lectures) (prep-phrase (prep to) (simple-noun-phrase (article the) (noun student)))) (prep-phrase (prep with) (simple-noun-phrase (article the) (noun cat)))))
(sentence (simple-noun-phrase (article the) (noun professor)) (verb-phrase (verb lectures) (prep-phrase (prep to) (noun-phrase (simple-noun-phrase (article the) (noun student)) (prep-phrase (prep with) (simple-noun-phrase (article the) (noun cat)))))))
Amb tree exhausted: (parse (quote (the professor lectures to the student with the cat)))
ok
#+end_example

*** 4.50

#+begin_src racket :noweb-ref eval-amb
(define (a-random-element-and-rest lst)
  (define (pick-to-first heads tails i)
    (if (= i 0)
        (cons (car tails) (append (reverse heads) (cdr tails)))
        (pick-to-first (cons (car tails) heads)
                       (cdr tails)
                       (- i 1))))
  (let ([rand (random (length lst))])
    (pick-to-first '() lst rand)))

(define (ramb? expr) (tagged-list? expr 'ramb))
(define (analyze-ramb expr)
  (let ([cprocs (map analyze (cdr expr))])
    (lambda (env succ fail)
      (define (try-again choices)
        (if (null? choices)
            (fail)
            (let ([chosen-rest (a-random-element-and-rest choices)])
              ((car chosen-rest) env
                                 succ
                                 (lambda ()
                                   (try-again (cdr chosen-rest)))))))
      (try-again cprocs))))
#+end_src

#+begin_src racket
;<<eval-amb-test>>
(try-ambeval '(ramb 1 2 3) global 3)
(try-ambeval '(ramb 1 2 3) global 3)
#+end_src

#+RESULTS:
: 1
: 3
: 2
: ok
: 1
: 3
: 2
: ok

*** 4.51

#+begin_src racket :results none :noweb-ref eval-amb
(define (permanent-assignment? expr) (tagged-list? expr 'permanent-set!))
(define (analyze-permanent-assignment expr)
  (lambda (env succ fail)
    (let ([var (assignment-variable expr)]
          [vproc (analyze (assignment-value expr))])
      (vproc env
             (lambda (val failv)
               (set-variable-value! var val env)
               (succ 'ok failv))
             fail))))
#+end_src

#+begin_src racket :noweb-ref eval-amb-test-util
(define eval-amb-util
  (list
   '(define (require p)
      (if (not p) (amb)))
   '(define (an-element-of xs)
      (require (not (null? xs)))
      (amb (car xs) (an-element-of (cdr xs))))
   ))
(for-each
 (lambda (expr) (ambeval expr global (lambda (val fail) val) (lambda () (display 'failed))))
 eval-amb-util)
#+end_src

#+begin_src racket
;<<eval-amb-test>>
;<<eval-amb-test-util>>
(ambeval-handle '(define count 0) global)
(try-ambeval '(let ((x (an-element-of '(a b c)))
                    (y (an-element-of '(a b c))))
                (permanent-set! count (+ count 1))
                (require (not (eq? x y)))
                (list x y count))
             global 3)
#+end_src

#+RESULTS:
: ok
: #<procedure:...rg-babel-oVxIO8.rkt:590:11>
: (b a 2)
: (c a 3)
: (a b 4)
: ok

*** 4.52

#+begin_src racket :noweb-ref eval-amb
(define (if-fail? expr) (tagged-list? expr 'if-fail))
(define (analyze-if-fail expr)
  (lambda (env succ fail)
    (let ([pproc (analyze (if-predicate expr))]
          [cproc (analyze (if-consequent expr))])
      (pproc env
             (lambda (val failp)
               (succ val failp))
             (lambda ()
               (cproc env succ fail))))))
#+end_src

#+begin_src racket
;<<eval-amb-test>>
;<<eval-amb-test-util>>
(try-ambeval '(if-fail (let ((x (an-element-of '(1 3 5))))
                         (require (even? x))
                         x)
                       'all-odd)
             global 1)

(try-ambeval '(if-fail (let ((x (an-element-of '(1 3 5 8))))
                         (require (even? x))
                         x)
                       'all-odd)
             global 1)
#+end_src

#+RESULTS:
: all-odd
: ok
: 8
: ok

*** 4.53

I didn't implement the `and` and `or` syntax...

#+begin_src racket
;<<eval-amb-test>>
;<<eval-amb-test-util>>
(for-each (lambda (expr) (ambeval-handle expr global))
          (list
           '(define (or a b)
              (if a true (if b b)))
           '(define (and a b)
              (if a
                  (if b b #f)
                  #f))

           '(define (prime-sum-pair as bs)
              (let ([a (an-element-of as)]
                    [b (an-element-of bs)])
                (require (prime? (+ a b)))
                (list a b)))

           '(define (prime? x)
              (define (iter i)
                (cond [(> (floor (* i i)) x) #t]
                      [(= (modulo x i) 0) #f]
                      [else (iter (+ i 1))]))
              (if (or (and (not (= x 2)) (even? x))
                      (= x 1)) #f
                  (iter 3)))
           ))

(try-ambeval '(let ((pairs '()))
                (if-fail (let ((p (prime-sum-pair '(1 3 5 8) '(20 35 110))))
                           (permanent-set! pairs (cons p pairs))
                           (amb))
                         pairs))
             global 2)
; => '(23)
#+end_src

#+RESULTS:
: ok
: ok
: ok
: ok
: ((3 110) (8 35) (3 20))
: Amb tree exhausted: (let ((pairs (quote ()))) (if-fail (let ((p (prime-sum-pair (quote (1 3 5 8)) (quote (20 35 110))))) (permanent-set! pairs (cons p pairs)) (amb)) pairs))
: ok

Because there're two layer of fails.

There is another interesting phenomenon in `#lang sicp`:

#+begin_src racket
(amb 1 3) ; => 1
(amb 2)   ; => 2
(amb)     ; => 3
#+end_src

#+RESULTS:
: 1
: 2
: 3

This is because the `call/cc` saved the context so the `amb` traceback to the before possibility of `amb`.

*** 4.54

#+begin_src racket :noweb-ref eval-amb
(define (require? expr) (tagged-list? expr 'require))
(define (require-predicate expr) (cadr expr))

(define (analyze-require expr)
  (let ([pproc (analyze (require-predicate expr))])
    (lambda (env succ fail)
      (pproc env
             (lambda (valp failp)
               (if (false? valp)
                   (failp)
                   (succ 'ok failp)))
             fail))))
#+end_src

#+begin_src racket
;<<eval-amb-test>>
(try-ambeval '(define (an-element-of xs)
                (require (not (null? xs)))
                (amb (car xs) (an-element-of (cdr xs)))) global 1)
(try-ambeval '(let ([x (an-element-of '(1 2 3 4))])
                (require (even? x))
                x)
             global 2)
#+end_src

#+RESULTS:
: ok
: ok
: 2
: 4
: ok

* 4.4 Logic Programming

I know it will comes again that giving me the examples but I can't run to verify them. Facing this, I should come back to run. But the `.org` file are consist of sequential lines. Going back to change things will make a mess to the "history". Or I should copy the former snippets. But see, the line number of this line is close to 5,000. Oh, my! I need less copies.

Now I will deal with it.

** 4.1 Deductive Information Retrieval

*** exp

#+begin_src racket :noweb-ref database
(define database-company
  (list
   '(address (Bitdiddle Ben) (Slumerville (Ridge Road) 10))
   '(job (Bitdiddle Ben) (computer wizard))
   '(salary (Bitdiddle Ben) 60000)

   '(address (Hacker Alyssa P) (Cambridge (Mass Ave) 78))
   '(job (Hacker Alyssa P) (computer programmer))
   '(salary (Hacker Alyssa P) 40000)
   '(supervisor (Hacker Alyssa P) (Bitdiddle Ben))
   '(address (Fect Cy D) (Cambridge (Ames Street) 3))
   '(job (Fect Cy D) (computer programmer))
   '(salary (Fect Cy D) 35000)
   '(supervisor (Fect Cy D) (Bitdiddle Ben))
   '(address (Tweakit Lem E) (Boston (Bay State Road) 22))
   '(job (Tweakit Lem E) (computer technician))
   '(salary (Tweakit Lem E) 25000)
   '(supervisor (Tweakit Lem E) (Bitdiddle Ben))

   '(address (Reasoner Louis) (Slumerville (Pine Tree Road) 80))
   '(job (Reasoner Louis) (computer programmer trainee))
   '(salary (Reasoner Louis) 30000)
   '(supervisor (Reasoner Louis) (Hacker Alyssa P))

   '(supervisor (Bitdiddle Ben) (Warbucks Oliver))
   '(address (Warbucks Oliver) (Swellesley (Top Heap Road)))
   '(job (Warbucks Oliver) (administration big wheel))
   '(salary (Warbucks Oliver) 150000)

   '(address (Scrooge Eben) (Weston (Shady Lane) 10))
   '(job (Scrooge Eben) (accounting chief accountant))
   '(salary (Scrooge Eben) 75000)
   '(supervisor (Scrooge Eben) (Warbucks Oliver))
   '(address (Cratchet Robert) (Allston (N Harvard Street) 16))
   '(job (Cratchet Robert) (accounting scrivener))
   '(salary (Cratchet Robert) 18000)
   '(supervisor (Cratchet Robert) (Scrooge Eben))

   '(address (Aull DeWitt) (Slumerville (Onion Square) 5))
   '(job (Aull DeWitt) (administration secretary))
   '(salary (Aull DeWitt) 25000)
   '(supervisor (Aull DeWitt) (Warbucks Oliver))

   '(can-do-job (computer wizard) (computer programmer))
   '(can-do-job (computer wizard) (computer technician))

   '(can-do-job (computer programmer)
                (computer programmer trainee))

   '(can-do-job (administration secretary)
                (administration big wheel))
   ))
#+end_src

*** 4.55

It seems I will do these exercises twice to verify them.

a. all people supervised by Ben Bitdiddle;

b. the names and jobs of all people in the accounting division;

c. the names and addresses of all people who live in Slumerville.

#+begin_src racket :noweb-ref queries-4-55
(define queries-4-55
  (list
   '(supervisor ?who (Bitdiddle Ben))
   '(job ?who (accounting . ?job))
   '(address ?who (Slumerville . ?where))
   ))
#+end_src

*** exp: compound queries

#+begin_src racket :results none
(and (job ?persion (computer programmer))
     (address ?person ?where))

(or (supervisor ?x (Bitdiddle Ben))
    (supervisor ?x (Hacker Alyssa P)))

(and (supervisor ?x (Bitdiddle Ben))
     (not (job ?x (computer programmer))))

(and (salary ?person ?amount)
     (lisp-value > ?amount 30000))
#+end_src

*** 4.56

a. the names of all people who are supervised by Ben Bitdiddle, together with their addresses;

b. all people whose salary is less than Ben Bitdiddle's, together with their salary and Ben Bitdiddle's salary;

c. all people who are supervised by someone who is not in the computer division, together with the supervisor's name and job.

#+begin_src racket :noweb-ref queries-4-56
(define queries-4-56
  (list
   '(and (supervisor ?who (Bitdiddle Ben))
         (address ?who . ?other-info))
   '(and (salary ?person ?amount)
         (salary (Bitdiddle Ben) ?base)
         (lisp-value < ?amount ?base))
   '(and (supervisor ?who ?leader)
         (not (job ?leader (computer . ?any-role)))
         (job ?leader ?job))
   ))
#+end_src

*** exp: rules

#+begin_src racket :noweb-ref rules-exp
(define rules-exp
  (list
   '(rule (same ?x ?x))

   '(rule (lives-near ?person-1 ?person-2)
          (and (address ?person-1 (?town . ?rest-1))
               (address ?person-2 (?town . ?rest-2))
               (not (same ?person-1 ?person-2))))

   '(rule (wheel ?person)
          (and (supervisor ?middle-manager ?person)
               (supervisor ?x ?middle-manager)))
   ))
#+end_src

*** 4.57

a.  all people who can replace Cy D. Fect;

b.  all people who can replace someone who is being paid more than they are, together with the two salaries.

#+begin_src racket :noweb-ref rules-4-57
(define rules-4-57
  (list
   '(rule (can-replace ?person ?successor)
          (and (job ?person ?person-job)
               (job ?successor ?successor-job)
               (can-do-job ?successor-job ?person-job)
               (not (same ?person ?successor))))
   ))
#+end_src

#+begin_src racket :noweb-ref queries-4-57
(define queries-4-57
  (list
   '(can-replace (Fect Cy D) ?anyone)

   '(and (who-can-replace ?person ?succesor)
         (salaries ?person ?person-salaries)
         (salaries ?successor ?successor-salaries)
         (lisp-value < ?successor-salaries ?person-salaries))
   ))
#+end_src

*** 4.58

The person works in the division but does not have a supervisor who works in the division.

#+begin_src racket :noweb-ref rules-4-58
(define rules-4-58
  (list
   '(rule (big-shot ?somebody ?division)
          (and (job ?somebody (?division . ?role))
               (not (supervisor ?somebody ?anyone))
               (job ?anyone (?division . ?any-role))))
   ))
#+end_src

#+begin_src racket :noweb-ref queries-4-58
(define queries-4-58
  (list
   '(and (big-shot ?somebody ?anywhere)
         (job ?somebody ?job))
   ))
#+end_src

*** 4.59

#+begin_src racket :noweb-ref database
(define database-meetings
  (list
   '(meeting accounting (Monday 9am))
   '(meeting administration (Monday 10am))
   '(meeting computer (Wednesday 3pm))
   '(meeting administration (Friday 1pm))
   '(meeting whole-company (Wednesday 4pm))
   ))
#+end_src

**** a) and c)

#+begin_src racket :noweb-ref queries-4-59
(define queries-4-59
  (list
   '(meeting ?division (Friday . ?time-details))

   '(meeting-time (Hacker Alyssa P) (Wednesday ?time))
   ))
#+end_src

**** b)

#+begin_src racket :noweb-ref rules-4-59
(define rules-4-59
  (list
   '(rule (meeting-time ?person ?day-and-time)
          (and (meeting whole-company ?day-and-time)
               (job ?person (?division . ?role))
               (meeting ?division ?day-and-time)))
   ))
#+end_src

*** 4.60

There may be some trick to remove duplicate results.

But its availability defines by the behavior of `not` expression.

#+begin_src racket :noweb-ref queries-4-60
(define queries-4-60
  (list
   '(lives-near ?person-1 ?person-2)

   '(and (lives-near ?p1 ?p2)
         (and (lives-near ?p2 ?p3)
              (not (same ?p1 ?p3))))
   ))
#+end_src

This trick requires the inner `and` expression returns a `()`, which need the `not` do not reject everything. And the trailing `()` is not good-looking.

*** exp: logic as programs

Until here this example shows the real usage of the pattern matching functionality of a rule defining expression.

#+begin_src racket :noweb-ref rules-exp-append
(define rules-exp-append
  (list
   '(rule (append-to-form () ?y ?y))
   '(rule (append-to-form (?u . ?v) ?y (?u . ?z))
          (append-to-form ?v ?y ?z))
   ))
#+end_src

#+begin_src racket :noweb-ref queries-exp-append
(define queries-exp-append
  (list
   '(append-to-form (a b) (c d) ?z)
   '(append-to-form (a b) ?y (a b c d))
   '(append-to-form ?x ?y (a b c d))
   ))
#+end_src

*** 4.61

#+begin_src racket :noweb-ref rules-4-61
(define rules-4-61
  (list
   '(rule (?x next-to ?y in (?x ?y . ?u)))
   '(rule (?x next-to ?y in (?v . ?z))
          (?x next-to ?y in ?z))
   ))
#+end_src

I haven't thought move the rule name to another position and multiple rule names.

#+begin_src racket :noweb-ref queries-4-61
(define queries-4-61
  (list
   '(?x next-to ?y in (1 (2 3) 4))
   '(?x next-to 1 in (2 1 3 1))
   ))
#+end_src

#+begin_src
(1 next-to (2 3) in (1 (2 3) 4))
((2 3) next-to 4 in (1 (2 3) 4))

(2 next-to 1 in (2 1 3 1))
(3 next-to 1 in (2 1 3 1))
#+end_src

*** 4.62

#+begin_src racket :noweb-ref rules-4-62
(define rules-4-62
  (list
   '(rule (last-pair () ?x)
          (last-pair () none))
   '(rule (last-pair (?x) ?x))
   '(rule (last-pair (?pickout . ?rest) ?x)
          (last-pair (?rest) ?x))
   ))
#+end_src

#+begin_src racket :noweb-ref queries-4-62
(define queries-4-62
  (list
   '(last-pair (3) ?x)
   '(last-pair (1 2 3) ?x)
   '(last-pair (2 ?x) (3))
   '(last-pair ?x (3))
   ))
#+end_src

The `(last-pair ?x (3))` will work because it match the pattern of `(rule (last-pair (?x) ?x))`. In the rule it knows the `?x` is `(3)`, so the `(?x)` is `((3))`.

*** 4.63

#+begin_src racket :noweb-ref database-4-63
(define database-4-63
  (list
     '(son Adam Cain)
     '(son Cain Enoch)
     '(son Enoch Irad)
     '(son Irad Mehujael)
     '(son Mehujael Methushael)
     '(son Methushael Lamech)
     '(wife Lamech Ada)
     '(son Ada Jabal)
     '(son Ada Jubal)
     ))
#+end_src

#+begin_src racket :noweb-ref rules-4-63
(define rules-4-63
  (list
   '(rule (grandson-with-parent ?grandparent ?parent ?son)
          (and (son ?grandparent ?parent)
               (son ?parent ?son)))
   '(rule (grandson ?g ?s)
          (grandson-with-parent ?g ?somebody ?s))

   ;; '(rule (nuclear-family ?husband ?wife (?child . ?other-children))
   ;;        (and (nuclear-family ?husband ?wife (?child))
   ;;             (nuclear-family ?husband ?wife)))
   ;; '(rule (nuclear-family ?h ?w (?child))
   ;;        (and (wife ?h ?w)
   ;;             (or (son ?h ?child)
   ;;                 (son ?w ?child))))

   '(rule (son ?parent ?son)
          (or (son ?parent ?son)
              (and (wife ?parent ?wife)
                   (son ?wife ?son))))
   ;; '(rule (son ?parent ?son)
   ;;        (or (son ?parent ?son)
   ;;            (and (or (and (wife ?parent ?wife)
   ;;                          (son ?wife ?son))
   ;;                     (and (wife ?husband ?parent)
   ;;                          (son ?husband ?son))))))
   ))
#+end_src

I implement the nuclear-family because I misunderstood the meaning of the exercise description. Why I make it commented?

There is another relative question. I tried to implement another version of `son` rule, but this version is also be commented.

This is because I can't sure the solving process introduced the short circuit evaluation of `and` and `or`. If not, the son rule may leads into an endless recustion searching.

Similarly, the coexistence of `son` rule and `nuclear-famliy` rule constructs to a mutual recursion structure, which also may leads to a endless recusion.

This may be why there's no any `(husband ?a ?b)` rule/datum.

#+begin_src racket :noweb-ref queries-4-63
(define queries-4-63
  (list
   '(grandson Cain ?who)
   '(son Lamech ?who)
   '(grandson Methushael)
   ))
#+end_src

*** 4.4.2 How the Query System Works

* Helper functions

#+begin_src racket :noweb-ref sicp
(define (sicp m)
  (define (square x) (* x x))
  (define (average a b) (/ (+ a b) 2))
  (define (displayln x) (display x) (newline))

  (cond
    [(eq? m 'square) square]
    [(eq? m 'average) average]
    [(eq? m 'displayln) displayln]
    [else (error "Unknown procedure -- SICP")]))
#+end_src

#+begin_src racket :noweb-ref higher-order
(define (F m)
  (define (id x) x)
  (define (partial f . args1)
    (lambda args2 (apply f (append args1 args2))))
  (define (compose . f1s) ; functions in f-s only need one argument
    (if (null? f1s) id
        (lambda (x) ((apply compose (cdr f1s)) (apply (car f1s) (list x))))))
  (define (flip f2) (lambda (x y) (f2 y x)))

  (cond
    [(eq? m 'id) id]
    [(eq? m 'partial) partial]
    [(eq? m 'compose) compose]
    [(eq? m 'flip) flip]
    [else (error "Unknown procedure -- F" m)]))
#+end_src

#+begin_src racket :noweb-ref fold
(define (fold-left f acc lst)
  (if (null? lst) acc
      (fold-left f (f acc (car lst)) (cdr lst))))

(define (fold-right f lst acc)
  (if (null? lst) acc
      (f (car lst) (fold-right f (cdr lst) acc))))
#+end_src

* COMMENT Local Variables
# Local Variables:
# org-babel-noweb-wrap-start: ";<<"
# org-babel-noweb-wrap-end: ">>"
# End:
