#+title: Exercise
#+property: header-args:racket :lang sicp :results output :noweb yes

Chapter 4: Metalinguistic Abstraction

* 4.1 The Metacircular Evaluator

** 4.1.1 The Core of the Evaluator

*** exp

#+begin_src racket :noweb-ref eval-core-exp
(define (eval expr env)
  (cond
    [(self-evaluating? expr) expr]
    [(variable? expr) (lookup-variable-value expr env)]
    [(quoted? expr) (text-of-quotation expr)]
    [(assignment? expr) (eval-assignment expr env)]
    [(definition? expr) (eval-definition expr env)]
    [(lambda? expr)
     (make-procedure (lambda-parameters expr)
                     (scan-out-defines (lambda-body expr)) ; Exercise 4.16
                     env)]
    [(begin? expr)
     (eval-sequence (begin-actions expr) env)]
    [(if? expr) (eval-if expr env)]
    [(cond? expr) (eval (cond->if expr) env)]
    [(and? expr) (eval-and expr env)] ; and & or: Exercise 4.4
    [(or? expr) (eval-or expr env)]
    [(let? expr) (eval (let->combination expr) env)] ; let: Exercise 4.6
    [(let*? expr) (eval (let*->nested-lets expr) env)] ; let*: Exercise 4.7
    [(letrec? expr) (eval (letrec->let expr) env)] ; letrec: Exercise 4.20
    [(application? expr)
     (my-apply (eval (operator expr) env)
               (list-of-values (operands expr) env))]
    [else (error "Unknown expression type -- EVAL" expr)]))

(define (my-apply procedure arguments)
  (cond
    [(primitive-procedure? procedure)
     (apply-primitive-procedure procedure arguments)]
    [(compound-procedure? procedure)
     (eval-sequence
      (procedure-body procedure)
      (extend-environment
       (procedure-parameters procedure)
       arguments
       (procedure-environment procedure)))]
    [else (error "Unknown procedure type -- APPLY" (list procedure arguments))]))

(define (list-of-values exprs env)
  (if (no-operands? exprs)
      '()
      (cons (eval (first-operand exprs) env)
            (list-of-values (rest-operands exprs) env))))

(define (eval-if expr env)
  (if (true? (eval (if-predicate expr) env))
      (eval (if-consequent expr) env)
      (eval (if-alternative expr) env)))

(define (eval-sequence exprs env)
  (cond [(last-expr? exprs) (eval (first-expr exprs) env)]
        [else (eval (first-expr exprs) env)
              (eval-sequence (rest-exprs exprs) env)]))

(define (eval-assignment expr env)
  (set-variable-value! (assignment-variable expr)
                 (eval (assignment-value expr) env)
                 env)
  'ok)

(define (eval-definition expr env)
  (define-variable! (definition-variable expr)
                    (eval (definition-value expr) env)
                    env)
  'ok)
#+end_src

*** 4.1

Comparing to the example of `list-of-values`, this version of `list-of-values` evals from left to right(first to end):

#+begin_src racket
(define (list-of-values exprs env)
  (if (no-operands? exprs)
      '()
      (let ([first-value (eval (first-operand exprs) env)])
        (cons first-value
              (list-of-values (rest-exprs exprs) env)))))
#+end_src

And this version evals from right to left:

#+begin_src racket
(define (list-of-values exprs env)
  (if (no-operands? exprs)
      '()
      (let ([rest-values (list-of-values (rest-exprs exprs) env)])
        (cons (eval (first-operand exprs) env)
              rest-values))))
#+end_src

*** exp

#+begin_src racket :noweb-ref eval-core-exp
(define (self-evaluating? expr)
  (cond [(number? expr) true]
        [(string? expr) true]
        [else false]))

(define (variable? expr) (symbol? expr))

;; quote
(define (quoted? expr)
  (tagged-list? expr 'quote))
(define (text-of-quotation expr) (cadr expr))

(define (tagged-list? expr tag)
  (if (pair? expr)
      (eq? (car expr) tag)
      false))

;; assignment
(define (make-assignment var val)
  (list 'set! var val))
(define (assignment? expr)
  (tagged-list? expr 'set!))
(define (assignment-variable expr) (cadr expr))
(define (assignment-value expr) (caddr expr))

;; definition
(define (definition? expr)
  (tagged-list? expr 'define))
(define (definition-variable expr)
  (if (symbol? (cadr expr))
      (cadr expr)           ; (define <var> <value>)
      (caadr expr)))        ; (define (function_name arg...) <value>)
(define (definition-value expr)
  (if (symbol? (cadr expr))
      (caddr expr)
      (make-lambda (cdadr expr)
                   (cddr expr))))
; lambda
(define (make-lambda parameters body)
  (cons 'lambda (cons parameters body)))
(define (lambda? expr) (tagged-list? expr 'lambda))
(define lambda-parameters cadr)
(define lambda-body cddr)

;; if
(define (make-if predicate consequent alternative)
  (list 'if predicate consequent alternative))
(define (if? expr) (tagged-list? expr 'if))
(define if-predicate cadr)
(define if-consequent caddr)
(define (if-alternative expr)
  (if (not (null? (cdddr expr)))
      (cadddr expr)
      false))

;; begin
(define (begin? expr) (tagged-list? expr 'begin))
(define (begin-actions expr) (cdr expr))
(define (last-expr? seq) (null? (cdr seq)))
(define first-expr car)
(define rest-exprs cdr)

(define (sequence->expr seq)
  (cond [(null? seq) seq]
        [(last-expr? seq) (first-expr seq)]
        [else (make-begin seq)]))
(define (make-begin seq) (cons 'begin seq))

;; apply
(define (application? expr) (pair? expr))
(define operator car)
(define operands cdr)
(define (no-operands? ops) (null? ops))
(define first-operand car)
(define rest-operands cdr)
#+end_src

#+begin_src racket :noweb-ref eval-core-exp :results none
(define (cond? expr) (tagged-list? expr 'cond))
(define cond-clauses cdr)
(define (cond-predicate clause) (car clause))
(define (cond-actions clause) (cdr clause))
(define (cond-else-clause? clause) (eq? (cond-predicate clause) 'else))

(define (cond->if expr)
  (expand-clauses (cond-clauses expr)))

(define (expand-clauses clauses)
  (if (null? clauses)
      false              ; clause else
      (let ([first (car clauses)] [rest (cdr clauses)])
        (if (cond-else-clause? first)
            (if (null? rest)
                (sequence->expr (cond-actions first))
                (error "ELSE clause is not last -- COND->IF" clauses))
            (make-if (cond-predicate first)
                     (sequence->expr (cond-actions first))
                     (expand-clauses rest))))))
#+end_src

** 4.1.2 Representing Expressions

*** 4.2

a) The `application?` clause in `cond` clauses in `eval` should be a last clause before `else` clause. This is because the `application?` is implemented by a simple `pair?` and recognise almost all expression as application other than the `if`s, `define`s and so on.
b) Known the reason, I know how to improve, adding a tag to the application expression:

   #+begin_src racket
(define (application? expr) (tagged-list? expr 'call))
(define operator cadr)
(define operands cddr)
   #+end_src

*** 4.3 data directed eval

#+begin_src BNF
<expr> ::= <value> | <statement>

<value> ::= <literal> | <variable>
<literal> ::= <number> | <string>
<variable> ::= <literal> | <procedure>
<procedure> ::= <parameters><body>
<body> ::= <sequence>
<sequence> ::= "(" <expr> | <expr> <expr> ")"

<statement> ::= <quoted> | <lambda> | <definition> | <assignment> | <if> | <cond> | <begin> | <apply>
<quoted> ::= "(" <quote-identifier><expr> ")"
<lambda> ::= "(" <lambda-identifier><procedure> ")"
...
#+end_src

|--------------------+---------+-----+-------+--------+-------+---------+-------+-------|
| Op\Expr            | literal | var | quote | assign | λ/def | if/cond | apply | begin |
| eval               | yes     | yes | yes   | yes    | yes   | yes     | yes   | yes   |
| self type identify | yes     | yes | yes   | yes    | yes   | yes     | yes   | yes   |
| ...                |         |     |       |        |       |         |       |       |
|--------------------+---------+-----+-------+--------+-------+---------+-------+-------|

#+begin_src racket :results none
(define (tag? x) (symbol? x))
(define (tagged-list-tag lst)
  (car lst))

(define (literal-pkg)
  (define (literal? x)
    (cond [(number? x) true]
          [(string? x) true]
          [else false]))
  (define (eval x env) x)

  (put 'literal? '(expr) literal?)
  (put 'eval '(literal env) eval)
  'done)

(define (variable-pkg)
  (define variable? symbol?)
  (define (eval x env)
    (lookup-variable-value x env))

  (put 'variable? '(expr) variable?)
  (put 'eval '(variable env) eval)
  'done)

(define (quote-pkg)
  (define (quoted? x) (tagged-list? x 'quote))
  (define (eval x env)
    (text-of-quotation x))
  (define (text-of-quotation x)
    (cadr x))

  (put 'quoted? '(expr) quoted?)
  (put 'eval '(quote env) eval)
  'done)

(define (assignment-pkg)
  (define (assignment? x) (tagged-list? x 'set!))
  (define (eval-assignment x env)
    (define-variable! (definition-variable expr)
      (eval (assignment-value expr) env)
      env))
  (define assignment-variable cadr)
  (define assigment-value caddr)

  (put 'assignment? '(expr) assignment?)
  (put 'eval '(assignment env) eval-assignment)
  'done)

(define (lambda-definition-pkg)
  (define (lambda? x) (tagged-list? x 'lambda))
  (define (definition? x) (tagged-list? x 'define))

  (define (make-lambda parameters body)
    (cons 'lambda (cons parameters body)))
  (define lambda-parameters cadr)
  (define lambda-body cddr)

  (define (difinition-varible expr)
    (if (symbol? (cadr expr))
        (cadr expr)
        (caadr expr)))
  (define (difinition-value expr)
    (if (symbol? (cadr expr))
        (caddr expr)
        (make-lambda (cdadr expr)
                     (cddr expr))))

  (define (eval-lambda expr env)
    (make-procedure (lambda-parameters expr)
                    (lambda-body expr)
                    env))
  (define (eval-definition expr env)
    (define-variable! (definition-variable expr)
      (eval (definition-value expr) env)
      env))

  (put 'lambda? '(expr) lambda?)
  (put 'definition? '(expr) definition?)
  (put 'eval '(lambda env) eval-lambda)
  (put 'eval '(definition env) eval-definition)
  'done)

(define (if-cond-pkg)
  (define (if? expr) (tagged-list? expr 'if))
  (define (make-if predicate consequent alternative)
    (list 'if predicate consequent alternative))
  (define if-predicate cadr)
  (define if-consequent caddr)
  (define (if-alternative expr)
    (if (null? (cdddr expr)) false
        (cadddr expr)))

  (define (eval-if expr env)
    (if (true? (if-predicate expr))
        (eval (if-consequent expr) env)
        (eval (if-alternative expr) env)))

  (define (cond? expr) (tagged-list? expr 'cond))
  (define cond-clauses cdr)
  (define (cond-predicate clause) (car clause))
  (define (cond-actions clause) (cdr clause))
  (define (cond-else-clause? clause) (eq? (cond-predicate clause) 'else))
  (define (cond->if expr)
    (expand-clauses (cond-clauses expr)))
  (define (expand-clauses clauses)
    (if (null? clauses)
        false
        (let ([first (car clauses)] [rest (cdr clauses)])
          (if (cond-else-clause? first)
              (if (null? rest)
                  (sequence->expr (cond-actions first))
                  (error "ELSE clause is not last -- COND->IF"))
              (make-if (cond-predicate first)
                       (sequence->expr (cond-actions first))
                       (expand-clauses rest))))))

  (define (eval-cond expr env)
    (eval (cond->if expr env)))

  (put 'if? '(expr) if?)
  (put 'cond? '(expr) cond?)
  (put 'eval '(if env) eval-if)
  (put 'eval '(cond env) eval-cond)
  'done)

(define (apply-pkg)
  (define (application? expr) (pair? expr))
  (define operator car)
  (define operands cdr)
  (define (no-operands? ops) (null? ops))
  (define first-operand car)
  (define rest-operands cdr)
  (define (list-of-values exprs env)
    (if (no-operands? exprs)
        '()
        (cons (eval (first-operand exprs) env)
              (list-of-values (rest-operands exprs) env))))

  (define (eval-application expr env)
    (apply (eval (operator expr) env)
           (list-of-values (operands expr) env)))

  (put 'application? '(expr) application?)
  (put 'eval '(application env) eval-application)
  'done)

(define (begin-pkg)
  (define (make-begin seq) (cons 'begin seq))
  (define (begin? expr) (tagged-list? expr 'begin))
  (define (begin-actions expr) (cdr expr))
  (define (eval-begin expr env)
    (eval-sequence (begin-actions expr) env))

  (define (last-expr? seq) (null? (cdr seq)))
  (define first-expr car)
  (define rest-exprs cdr)
  (define (sequence->expr seq)
    (cond [(null? seq) seq]
          [(last-expr? seq) (first-expr seq)]
          [else (make-begin seq)]))
  (define (eval-sequence exprs env)
    (cond [(last-expr? exprs) (eval (first-expr exprs) env)]
          [else (eval (first-expr exprs) env)
                (eval-sequence (rest-exprs exprs) env)]))

  (put 'begin? '(expr) begin?)
  (put 'sequence->expr '(sequence) sequence->expr)
  (put 'eval '(begin env) eval-begin)
  (put 'eval '(sequence env) eval-sequence)
  'done)

(define (sequence->expr seq) (get 'sequence->expr '(sequence)))

(define (lookup-variable-value var env)
  ??)

(define literal? (get 'literal? '(expr)))
(define variable? (get 'variable?) '(expr))
(define (type-of-value value)
  (cond [(literal? value) 'literal]
        [(variable? value) 'variable]
        [else false]))
(define (type-of-expr expr)
  (let ([value-type (type-of-value expr)])
    (if (value-type) value-type
        (let ([expr-tag (tagged-list-tag expr)])
          (if (tag? expr-tag) expr-tag
              'application)))))
(define (eval expr env)
  ((get 'eval (list (type-of-expr expr) 'env)) expr env))
#+end_src

It seems I did too much.

The implementation of `eval` is quite alike to the `deriv` in Exercise 2.73.

*** 4.4 and & or

#+begin_src BNF
<sequence> ::= "(" <sequence-exprs> ")"
<sequence-exprs> ::= <expr> | <expr> <sequence-exprs>

<and> ::= "(" <and-identifier> <sequence> ")"
<or> ::= "(" <or-identifier> <sequence> ")"
#+end_src

Wait, until now the Book haven't told me any implementation or interface of the booleans...

#+begin_src racket :noweb-ref eval-core-exp
(define (and? expr) (tagged-list? expr 'and))
(define (eval-and expr env)
  (define (iter seq)
    (let ([curr (eval (first-expr seq) env)])
      (if (not curr) false
          (if (last-expr? seq)
              curr
              (iter (rest-exprs seq))))))
  (if (null? (cdr expr)) true
      (iter (cdr expr))))

(define (or? expr) (tagged-list? expr 'or))
(define (eval-or expr env)
  (define (iter seq)
    (let ([curr (eval (first-expr seq) env)])
      (if curr true
          (if (last-expr? seq)
              curr
              (iter (rest-exprs seq))))))
  (if (null? (cdr expr)) false
      (iter (cdr expr))))
#+end_src

It seems that the book didn't define the `derived expression` clearly. I guess it means the syntax function which don't call the `eval` directly.

Derived expression version:

#+begin_src racket :results none
; implementation of `and?` and `or`
(define (and->if expr)
  (define (iter seq)
    (cond [(null? seq) true]
          [(last-expr? seq)
           (make-if (first-expr seq)
                    (first-expr seq)
                    false)]
          [else (make-if (first-expr seq)
                         (iter (rest-exprs seq))
                         false)]))
  (iter (cdr expr)))

(define (or->if expr)
  (define (iter seq)
    (cond [(null? seq) false]
          [(last-expr? seq)
           (make-if (first-expr seq)
                    true
                    false)]
          [else (make-if (first-expr seq)
                         true
                         (iter (rest-exprs seq)))]))
  (iter (cdr expr)))
#+end_src

*** 4.5

I can only change the expand-clauses to implement the `(<test> => <recipient>)` grammar. Before this, let me have a try.

#+begin_src racket :lang racket
(define (3n+1-problem n)
  (define (odd-id? x) (and (odd? x) x))
  (define (even-id? x) (and (even? x) x))
  (cond [(odd-id? n) => (lambda (x) (+ (* 3 x) 1))]
        [(even-id? n) => (lambda (x) (/ x 2))]))

; below uses racket standard library functions
(define (3n+1-stream n)
  (define ss (stream-cons n (stream-map 3n+1-problem ss)))
  ss)

(stream->list (stream-take (3n+1-stream 7) 20))
(stream->list (stream-take (3n+1-stream 27) 112))
#+end_src

#+RESULTS:
: '(7 22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 4 2 1)
: '(27 82 41 124 62 31 94 47 142 71 214 107 322 161 484 242 121 364 182 91 274 137 412 206 103 310 155 466 233 700 350 175 526 263 790 395 1186 593 1780 890 445 1336 668 334 167 502 251 754 377 1132 566 283 850 425 1276 638 319 958 479 1438 719 2158 1079 3238 1619 4858 2429 7288 3644 1822 911 2734 1367 4102 2051 6154 3077 9232 4616 2308 1154 577 1732 866 433 1300 650 325 976 488 244 122 61 184 92 46 23 70 35 106 53 160 80 40 20 10 5 16 8 4 2 1)

#+begin_src racket :results none
(define (cond-arrow-clause? clause)
  (eq? (cadr clause) '=>))
(define (cond-arrow-recipient clause) (cddr clause))

(define (make-application proc exprs)
  (cons proc exprs))

(define (expand-clauses clauses)
  (if (null? clauses)
      false              ; clause else
      (let ([first (car clauses)] [rest (cdr clauses)])
        (if (cond-else-clause? first)
            (if (null? rest)
                (sequence->expr (cond-actions first))
                (error "ELSE clause is not last -- COND->IF" clauses))
            (if (cond-arrow-clause? first)
                (make-if (cond-predicate first)
                         (make-application (cond-arrow-recipient first) (cond-predicate first))
                         (expand-clauses rest))
                (make-if (cond-predicate first)
                         (sequence->expr (cond-actions first))
                         (expand-clauses rest)))))))
#+end_src

*** 4.6

#+begin_src BNF
<let> ::= "(" <let-identifier> "(" <bindings> ")" <body> ")"
<let-identifier> ::= 'let
<bindings> :: = <binding> | <bindings>
<binding> :: = "(" <variable> <expr> ")"
#+end_src

The binding itself is also an `expr`.

#+begin_src racket :noweb-ref eval-core-exp
(define (make-application proc exprs)
  (cons proc exprs))

(define (make-let bindings body)
  (list 'let bindings body))
(define (let? expr) (tagged-list? expr 'let))
(define let-bindings cadr)
(define let-body cddr)
(define (binding? expr) (and (pair? expr) (pair? (cdr expr)) (null? (cddr expr))
                             (variable? (car expr))))
(define bindings-first car)
(define bindings-rest cdr)
(define binding-variable car)
(define binding-value cadr)

(define (let->combination expr)
  (define (iter bindings variables exprs)
    (if (null? bindings) (cons variables exprs)
        (let ([first (bindings-first bindings)]
              [rest (bindings-rest bindings)])
          (if (binding? first)
              (iter rest
                    (cons (binding-variable first) variables) ; note that it reverse the order
                    (cons (binding-value first) exprs))
              (error "Binding form illegal -- LET" first)))))

  (let ([parameters-expressions (iter (let-bindings expr) '() '())])
    (make-application (make-lambda (car parameters-expressions)
                                   (sequence->expr (let-body expr)))
                      (cdr parameters-expressions))))
#+end_src

*** 4.7

A natural way to implement the `let*` is to use nested environments for orders of bindings.

As for implementing it as derived expression... Let me try to implement one to make it clear.

#+begin_src racket :noweb-ref eval-core-exp
(define (let*? expr) (tagged-list? expr 'let*))
(define (let*->nested-lets expr)
  (let ([bindings (let-bindings expr)])
    (if (or (null? bindings) (last-expr? bindings))
        expr
        (make-let (bindings-first bindings)
                  (let*->nested-lets (make-let (bindings-rest bindings)
                                               (let-body expr)))))))
#+end_src

Well, the evaluation of `let*` exactly updates the environment dynamically, since `let*` evals to nested `let`s then to nested `lambda`s. So I do not need to do more.

*** 4.8

It seems that the `(let <variable> <bindings> <body>)` can be transform to `(define (<variable> vars-in-bindings) <body>))  (let <bindings> (<variable> <vars-in-bindings>))`. Let me compare two versions of a implementation:

#+begin_src racket :results none
(define (fib n)
  (let fib-iter ((a 1)
                 (b 0)
                 (count n))
    (if (= count 0)
        b
        (fib-iter (+ a b) a (- count 1)))))

(define (fib n)
  (define (fib-iter a b count)
    (if (= count 0)
        b
        (fib-iter (+ a b) a (- count 1))))
  (let ((a 1)
        (b 0)
        (count n))
    (fib-iter a b count)))
#+end_src

#+begin_src BNF
<named-let> ::= "(" <let-identifier> <variable> <bindings> <body> ")"
#+end_src

Only list the changed procedures.

#+begin_src racket
(define (let-with-name? expr) (and (let? expr) (not (null? (cdddr expr)))))
(define let-with-name-name cadr)
(define let-with-name-bindings caddr)
(define let-with-name-body cadddr)

(define (make-function-definition name parameters body)
  (list (cons name parameters) body))

(define (let->combination expr)
  (define (iter bindings variables exprs)
    (if (null? bindings) (cons variables exprs)
        (let ([first (bindings-first bindings)]
              [rest (bindings-rest bindings)])
          (if (binding? first)
              (iter rest
                    (cons (binding-variable first) variables) ; note that it reverse the order
                    (cons (binding-value first) exprs))
              (error "Binding form illegal -- LET" first)))))

  (if (let-with-name? expr)
      (let ([name (let-with-name-name expr)]
            [parameters-expressions (iter (let-with-name-bindings expr) '() '())])
        (make-begin
         (make-function-definition name
                                   (car parameters-expressions))
         (make-let (let-with-name-bindings expr)
                   (make-application name
                                     (car parameters-expressions)))))
      (let ([parameters-expressions (iter (let-bindings expr) '() '())])
        (make-application (make-lambda (car parameters-expressions)
                                       (let-body expr))
                          (cdr parameters-expressions)))))
#+end_src

*** 4.9

#+begin_src racket :results none
(for <bindings> <pred> <after-body-bindings> <body>) ->
(let <bindings>
  (define (iter (binding-variable <bindings>) last-res)
    (<if> <pred>
          (let ([res <body>])
            (iter (binding-value <after-body-bindings>) res))
          last-res))
  (iter (binding-variable <bindings>) nil))

(for ([i 0]) (= i 10) ([i (inc i)])
     (display i))
#+end_src

It's more like a fold procedure...

#+begin_src racket
(define (for? expr) (tagged-list? expr 'for))
(define for-init-bindings car)
(define for-pred cadr)
(define for-after-bindings caddr)
(define for-body cadddr)
(define (for->derived expr)
  (let ([variables (binding-variable (for-init-bindings expr))]))
  (make-let (for-init-bindings expr)
            (make-begin
             (list
              (make-function-definition 'iter (append variables (list 'last-res))
                                        (make-if (for-pred expr)
                                                 (make-let (list [list 'res (for-body expr)])
                                                           (make-application 'iter (append variables (list 'res))))
                                                 'last-res)))
             (make-application (append variables '())))))
#+end_src

*** 4.10

Change the application to make operator to the last place in the expr list.

#+begin_src racket
(define (application? expr) (pair? expr))
(define operator tail)
(define operands heads)
(define (no-operands? ops) (null? ops))
(define first-operand car)
(define rest-operands cdr)
;<<heads-tail>>
#+end_src

#+NAME: heads-tail
#+begin_src racket
(define (tail lst)
  (cond [(null? lst) lst]
        [(null? (cdr lst)) (car lst)]
        [else (tail (cdr lst))]))
(define (heads lst)
  (cond [(null? lst) lst]
        [(null? (cdr lst)) '()]
        [else (cons (car lst) (heads (cdr lst)))]))
#+end_src

#+begin_src racket
;<<heads-tail>>
(tail (list 1 2 3))
(heads (list 1 2 3))
#+end_src

#+RESULTS:
: 3
: (1 2)

** 4.1.3 Evaluator Data Structures

*** exp

Predicate:

#+begin_src racket :noweb-ref eval-core-exp
(define (true? x)
  (not (eq? x false)))
(define (false? x)
  (eq? x false))
#+end_src

#+NAME: fix-eval-core-exp-4-1-3
#+begin_src racket
(define (apply-primitive-procedure proc args) ??)
(define (primitive-procedure? proc) ??)
#+end_src

#+begin_src racket :noweb-ref eval-core-exp
(define (make-procedure parameters body env)
  (list 'procedure parameters body env))

(define (compound-procedure? p)
  (tagged-list? p 'procedure))
(define procedure-parameters cadr)
(define procedure-body caddr)
(define procedure-environment cadddr)
#+end_src

#+begin_src racket
(define the-empty-environment '())
(define (enclosing-environment envs) (cdr envs))
(define (first-frame envs) (car envs))

(define (make-frame variables values)
  (cons variables values))
(define frame-variables car)
(define frame-values cdr)
(define (add-binding-to-frame! var val frame)
  (set-car! (cons var (frame-variables frame))
            (cons val (frame-values frame))))

(define (extend-environment vars vals base-env)
  (if (= (length vars) (length vals))
      (cons (make-frame vars vals) base-env)
      (if (< (length vars) (length vals))
          (error "Too many arguments supplied -- EXTEND-ENVIRONMENT" vars vals)
          (error "Too few arguments supplied -- EXTEND-ENVIRONMENT" vars vals))))

(define (lookup-variable-value var env)
  (define (env-loop env)
    (define (scan vars vals)
      (cond [(null? vars)
             (env-loop (enclosing-environment env))]
            [(eq? var (car vars)) (car vals)]
            [else scan (cdr vars) (cdr vals)]))
    (if (eq? env the-empty-environment)
        (error "Unbound variable" var)
        (let ([frame (first-frame env)])
          (scan (frame-variables frame)
                (frame-values frame)))))
  (env-loop env))

(define (set-variable-value! var val env)
  (define (env-loop env)
    (define (scan vars vals)
      (cond [(null? vars)
             (env-loop  (enclosing-environment env))]
            [(eq? var (car vars))
             (set-car! vals val)]
            [else scan (cdr vars) (cdr vals)]))
    (if (eq? env the-empty-environment)
        (error "Unbound variable -- SET!" var)
        (let ([frame (first-frame env)])
          (scan (frame-variables frame)
                (frame-values frame)))))
  (env-loop env))

(define (define-variable! var val env)
  (let ([frame (first-frame env)])
    (define (scan vars vals)
      (cond [(null? vars)
             (add-binding-to-frame! var val frame)]
            [(eq? var (car vars))
             (set-car! vals val)]
            [else (scan (cdr vars vals))]))
    (scan (frame-variables frame)
          (frame-values frame))))
#+end_src

I wonder why the frame entries is not implemented as an association list. That way the `let` bindings would have the same form with a frame, which makes a simpler system...

So it's at Exercise 4.11!

*** 4.11

Scheme have a helpful builtin procedure `assv` to find record in an association list.

#+begin_src racket
(assv 3 '((1 1) (2 2) (3 3) (4 4)))
(assv 'b '((a 1) (b 2) (c 3) (d 4)))
#+end_src

#+RESULTS:
: (3 3)
: (b 2)


#+begin_src racket :noweb-ref eval-core-exp
(define the-empty-environment '())
(define (enclosing-environment envs) (cdr envs))
(define (first-frame envs) (car envs))

(define (zip2 xs ys)
  (map list xs ys))

(define (make-frame-by-bindings bindings) bindings) ; a frame is bindings
(define (make-frame vars vals) (zip2 vars vals))
(define (make-binding var val) (list var val))
;; (define binding-variable car) ; they are defined above
;; (define binding-value cadr)
(define (bind-new-value! binding val)
  (set-cdr! binding (list val)))

;; this procedure is the same with example in book
(define (extend-environment vars vals base-env)
  (if (= (length vars) (length vals))
      (cons (make-frame vars vals) base-env)
      (if (< (length vars) (length vals))
          (error "Too many arguments supplied -- EXTEND-ENVIRONMENT" vars vals)
          (error "Too few arguments supplied -- EXTEND-ENVIRONMENT" vars vals))))

(define (lookup-variable-value var env)
  (define (env-loop env)
    (if (eq? env the-empty-environment)
        (error "Unbound variable" var)
        (let ([record (assv var (first-frame env))])
          (if record
              (binding-value record)
              (env-loop (enclosing-environment env))))))
  (env-loop env))
(define (set-variable-value! var val env)
  (define (env-loop env)
    (if (eq? env the-empty-environment)
        (error "Unbound variable -- SET!" var)
        (let ([record (assv var (first-frame env))])
          (if record
              (bind-new-value! record val)
              (env-loop (enclosing-environment env))))))
  (env-loop env))
(define (define-variable! var val env)
  (let* ([frame (first-frame env)]
         [record (assv var frame)])
    (if record
        (bind-new-value! record val)
        (set-car! env (cons (make-binding var val) frame)))))
#+end_src

*** 4.12

As for `define-variable!` in Exercise 4.11, it's precise enough. For the `scan` in the example, the `assv` abstracted it. The rest is the `env-loop`.

#+begin_src racket
(define (search-to-do-with-the-binding env var f)
  (if (eq? env the-empty-environment)
      (error "Unbound variable" var)
      (let ([record (assv (first-frame env))])
        (if record
            (f record)
            (search-to-do-with-the-binding (enclosing-environment env) var f)))))

(define (lookup-variable-value var env)
  (search-to-do-with-the-binding
   env var binding-value))

(define (set-variable-value! var val env)
  (search-to-do-with-the-binding
   env var (lambda (binding) (begin (bind-new-value! binding val)
                                    binding))))
#+end_src

*** 4.13

I think it is better not to delete all the all bindings of the same named variables in different frames. Take below python code as example:

#+begin_src python :results output
lst = [1,2,3]

def reversed_list(lst):
    res = list(reversed(lst))
    del lst
    return res

print(reversed_list(lst), lst)
#+end_src

#+RESULTS:
: [3, 2, 1] [1, 2, 3]

If the `del lst` also unbound the `lst` in the enclosing environment, the `print` call would raise an error.

I do not allow to unbound variables in enclosing environment, that may introduce dangling-pointer problem. I think it's reasonable for a strong dynamic typed language - scheme.

#+begin_src racket
(assv 2 '((1 1) ((2 2))))

(define x '(a b))
(begin (set-car! x (cadr x))
       (set-cdr! x '())
       x)

(define y '((2 2)))
(begin (set-car! y (cadr y))
       (set-cdr! y '())
       y)
#+end_src

#+RESULTS:
: mcar: contract violation
:   expected: mpair?
:   given: ()
:   context...:
:    body of "c:\Users\asu\AppData\Local\Temp\babel-lPETWE\org-babel-rjQw1z.rkt"
: #f
: (b)

#+begin_src racket
(define (memp f lst)
  (define (iter xs)
    (cond [(null? xs) #f]
          [(f (car lst)) xs]
          [else (iter (cdr xs))]))
  (iter lst))

(define (make-unbound! var env)
  (let* ([frame (first-frame env)]
         [mems (memp (lambda (binding) (eqv? (binding-variable binding) var)) frame)])
    (cond [(or (null? frame) (not mems))
           (error "Variable is not bind -- MAKE-UNBOUND!" var)]
          [(null? (cdr frame))
           (set-car! env '())]
          [else (begin (set-car! y (cadr y))
                       (set-cdr! y '()))])))
#+end_src

** 4.1.4 Running the Evaluator as a Program

***  exp

#+begin_src racket :noweb-ref eval-core-exp
(define (setup-environment)
  (let ([initial-env
         (extend-environment (primitive-procedure-names)
                             (primitive-procedure-objects)
                             the-empty-environment)])
    (define-variable! 'true true initial-env)
    (define-variable! 'false false initial-env)
    initial-env))

(define (primitive-procedure? expr)
  (tagged-list? expr 'primitive))
(define (primitive-implementation proc) (cadr proc))

(define primitive-procedures
  (list
   (list 'car car) (list 'cdr cdr)
   (list 'cons cons) (list 'null? null?)
   (list 'list list) (list 'pair? pair?)
   (list '+ +) (list '- -) (list '* *) (list '/ /)
   (list '= =)
   ))

(define (primitive-procedure-names)
  (map car primitive-procedures))

(define (primitive-procedure-objects)
  (map (lambda (proc) (list 'primitive (cadr proc)))
       primitive-procedures))

(define (apply-primitive-procedure proc args)
  (apply-in-underlying-scheme
   (primitive-implementation proc) args))

(define apply-in-underlying-scheme apply)
#+end_src

**** shadow `apply` in `#lang sicp` in racket

The `apply` is defined as a macro, it's not good to redefine it as a procedure name. In `#lang sicp`, this makes an error:

#+begin_src racket
;<<eval-core-exp>>
(define the-global-environment (setup-environment))
#+end_src

#+RESULTS:
: apply: undefined;
:  cannot reference an identifier before its definition
:   in module: "c:\Users\asu\AppData\Local\Temp\org-babel-mKGmrQ.rkt"
:   context...:
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-mKGmrQ.rkt"

This may because the statements is not evaluated sequentially. If I copy the codes(by `org-babel-expand-src-block`) into a file, it still errors.
If I use geiser other than emacs-ob-racket(which copy codes into a temp file to execute), this won't happen.

#+begin_src scheme :noweb yes :results output
(require sicp)
(define apply-in-underlying-scheme apply)
;<<eval-core-exp>>
(define the-global-environment (setup-environment))
(display the-global-environment)
(display (eval '1 the-global-environment))
#+end_src

#+RESULTS:
: (((false #f) (true #t) (car (primitive #<procedure:mcar>)) (cdr (primitive #<procedure:mcdr>)) (cons (primitive #<procedure:mcons>)) (null? (primitive #<procedure:null?>)) (+ (primitive #<procedure:+>)) (- (primitive #<procedure:->)) (* (primitive #<procedure:*>)) (/ (primitive #<procedure:/>))))1

I decide to go back to change the name of `apply` to `my-apply` in this system.

#+begin_src racket
;<<eval-core-exp>>
(define the-global-environment (setup-environment))
the-global-environment
(eval 'false the-global-environment)

;<<sicp>>
(for-each (lambda (x) ((sicp 'displayln) (eval x the-global-environment)))
          (list
           '(car (cons 1 2))
           '(define x 1)
           '(+ x 1)
           '(quote (1 car))
           '(define (square x) (* x x))
           '(square 11)))
the-global-environment
#+end_src

#+RESULTS:
: (((false #f) (true #t) (car (primitive #<procedure:mcar>)) (cdr (primitive #<procedure:mcdr>)) (cons (primitive #<procedure:mcons>)) (null? (primitive #<procedure:null?>)) (+ (primitive #<procedure:+>)) (- (primitive #<procedure:->)) (* (primitive #<procedure:*>)) (/ (primitive #<procedure:/>))))
: #f
: 1
: ok
: 2
: (1 car)
: ok
: 121
: #0=(((square (procedure (x) ((* x x)) #0#)) (x 1) (false #f) (true #t) (car (primitive #<procedure:mcar>)) (cdr (primitive #<procedure:mcdr>)) (cons (primitive #<procedure:mcons>)) (null? (primitive #<procedure:null?>)) (+ (primitive #<procedure:+>)) (- (primitive #<procedure:->)) (* (primitive #<procedure:*>)) (/ (primitive #<procedure:/>))))

*** exp

Well, the `driver-loop` is a REPL(Read-Eval-Print-Loop), but the book didn't mentioned about this here, it's mentiened at Book 1.1.1.

#+begin_src racket :noweb-ref repl-exp
(define input-prompt ";;; M-Eval input:")
(define output-prompt ";;; M-Eval output:")

(define (driver-loop)
  (prompt-for-input input-prompt)
  (let ([input (read)])
    (let ([output (eval input the-global-environment)])
      (announce-output output-prompt)
      (user-print output))
    (driver-loop)))

(define (prompt-for-input string)
  (newline) (newline) (display string) (newline))
(define (announce-output string)
  (newline) (display string) (newline))

(define (user-print object)
  (if (compound-procedure? object)
      (display (list 'compound-procedure
                     (procedure-parameters object)
                     (procedure-body object)
                     '<procedure-env>))
      (display object)))
#+end_src

#+begin_src racket :tangle "4.1.4-repl.rkt" :comments link :results none
;<<eval-core-exp>>
(define the-global-environment (setup-environment))

;<<repl-exp>>
(driver-loop)
#+end_src

It works perfect:

#+begin_src log
————— run 4.1.4-repl.rkt —————


;;; M-Eval input:
(define (append x y) (if (null? x) y (cons (car x) (append (cdr x) y))))

;;; M-Eval output:
ok

;;; M-Eval input:
(append '(a b c) '(d e f))

;;; M-Eval output:
(a b c d e f)

;;; M-Eval input:
#+end_src

But I don't understand why & how the `'` quote works. Following the book, I didn't add this functionality explicitly.

Let me see:

#+begin_src racket
(number? '1)
(number? 1)
#+end_src

#+RESULTS:
: #t
: #t

In scheme, to execute "(number? '1)" is `(eval (quote (number? '1)))` => `(apply (eval number?) (list (eval '1)))` => `(apply number? '(1))`. So the "`" quote is evaluated by intepreting my input. It seems the new evaluation system is the same.

*** 4.14

`map` recieve a function as one of an argument. In our system, they're either `(primitive #<procedure>)` or `(procedure <body>)`. The procedure tag can't be understand by the implementation of the scheme builtin `map`.

Below implement a `map` in the evaluation system, the `my-apply` will strip the procedure tag, and all things work well.

#+begin_src racket
;<<eval-core-exp>>
(define the-global-environment (setup-environment))
(eval '(define (map f xs)
         (if (null? xs) xs
             (cons (f (car xs)) (map f (cdr xs))))) the-global-environment)
(eval '(map (lambda (x) (+ x 1)) '(1 2)) the-global-environment)
#+end_src

#+RESULTS:
: ok
: (2 3)

** 4.1.5 Data as Programs

*** exp

#+begin_src racket
;<<eval-core-exp>>
;<<higher-order>>
(define global (setup-environment))
(((F 'flip) eval) global '(define (factorial n)
                            (if (= n 1) 1
                                (* n (factorial (- n 1))))))
(((F 'flip) eval) global '(factorial 4))
#+end_src

#+RESULTS:
: ok
: 24

I know how to use this at https://docs.racket-lang.org/r5rs/r5rs-std/r5rs-Z-H-9.html#%25_idx_600.

#+begin_src racket
(eval '1 (null-environment 5))
#+end_src

#+RESULTS:
: 1

*** 4.15

It's the halting problem!

#+begin_src racket :results none
(define (run-forever) (run-forever))

(define (try p)
  (if (halts? p p)
      (run-forever)
      'halted))
#+end_src

To evaluate `(try try)`, if it evaluates to `'halted`, this means `(halts? try try) => false`, `halts?` judges the `try` applied with `try` can be halted. While `halts?` judges the `try` for `try` can halt, the `(halts? try try)` would evaluates to true, and the `(try try)` should run forerver.

If `(try try)` runs forever, this means `halts?` judges the `try` applied with `try` can not halt. While this means `(halts? try try) => false`, it should evaluates to `'halted`.

** 4.1.6 Internal Definitions

*** exp

#+begin_src racket
;<<eval-core-exp>>
;<<higher-order>>
(define global (setup-environment))
(((F 'flip) eval) global
                  '(define (even? x)
                     (define (isodd n)
                       (if (= n 0) false
                           (iseven (- n 1))))
                     (define (iseven n)
                       (if (= n 0) true
                           (isodd (- n 1))))
                     (iseven x)))
(map ((F 'partial) ((F 'flip) eval) global)
     (list
      '(even? 2)
      '(even? 3)))
#+end_src

#+RESULTS:
: ok
: (#t #f)

#+begin_src racket
;<<eval-core-exp>>
(define global (setup-environment))
(eval '(define (main)
         (define (b) 1)
         (define a (b))
         a) global)
(eval '(main) global)
#+end_src

#+RESULTS:
: ok
: 1

In fact, `define` in `#lang sicp` also can't do this:

#+begin_src racket
(define (main)
  (define (b) 1)
  (define a (b))
  a)
(main)
#+end_src

#+RESULTS:
: b: undefined;
:  cannot use before initialization
:   context...:
:    c:\Users\asu\AppData\Local\Temp\org-babel-7CLhFN.rkt:8:0
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-7CLhFN.rkt"

See the error message, it's because the definition of the implementation of internal definition of R5RS. Detail are here and Exercise 4.18, 4.19, 4.20: https://conservatory.scheme.org/schemers/Documents/Standards/R5RS/HTML/r5rs-Z-H-8.html#%_sec_5.2.2.

*** 4.16

**** a)

My implementation of environment of the intepreter is defined in Exercise 4.11.

Just check the return value of the `env-loop`.

#+begin_src racket
(define (lookup-variable-value-check-unassigned var env)
  (define (env-loop env)
    (if (eq? env the-empty-environment)
        (error "Unbound variable" var)
        (let ([record (assv var (first-frame env))])
          (if record
              (binding-value record)
              (env-loop (enclosing-environment env))))))
  (let ([res (env-loop env)])
    (if (eqv? res '*unassigned*)
        (error "Value of var is unassigned" var))))

;<<eval-core-exp>>
(define global (setup-environment))
(eval '(define x '*unassigned*) global)
(eval 'x global)

(lookup-variable-value-check-unassigned 'x global)
#+end_src

#+RESULTS:
: Value of var is unassigned x
:   context...:
:    body of "c:\Users\asu\AppData\Local\Temp\org-babel-Ppx8JL.rkt"
: ok
: *unassigned*

**** b)

In the intepreter, the procedure is expressed as a tagged list of structure `(<procedure-identifer> <parameters> <body> <env>)` (see Book 4.1.3), and <body>s are <sequence>s (see Book 4.1.1 and my answer of Exercise 4.3).

#+NAME: scan-out-defines
#+begin_src racket :noweb-ref eval-core-exp
(define (unassigned-bindings vars)
  (map (lambda (var) (make-binding var ''*unassigned*)) vars))

(define (scan-out-defines proc-body)
  (define (reversed lst)
    (define (iter xs acc)
      (if (null? xs) acc
          (iter (cdr xs) (cons (car xs) acc))))
    (iter lst '()))
  (define (iter rests acc-v acc-e)
    ;; in r5rs, the last expr of a procedure body should not be a definition;
    ;; but I choose to return a '<void> simply
    (cond [(null? rests) (list (reversed acc-v) (reversed acc-e) '<void>)]
          [(and (last-expr? rests)
                (not (definition? (first-expr rests))))
           (list (reversed acc-v) (reversed acc-e) (first-expr rests))]
          [(definition? (first-expr rests))
           (let ([def (first-expr rests)])
             (iter (cdr rests)
                   (cons (definition-variable def) acc-v)
                   (cons (definition-value def) acc-e)))]
          [else (iter (cdr rests) acc-v acc-e)]))
  (let ([vars-vals-expr (iter proc-body '() '())])
    (let ([vars (car vars-vals-expr)]
          [vals (cadr vars-vals-expr)]
          [expr (caddr vars-vals-expr)])
      (if (null? vars) proc-body
          (list (make-let (unassigned-bindings vars)
                          (append (map (lambda (var val)
                                         (make-assignment var val)) vars vals)
                                  (list expr))))))))
#+end_src

#+begin_src racket
;<<eval-core-exp>>
(define global (setup-environment))

(scan-out-defines
 (procedure-body '(define (main)
                    ((define (square x) (* x x))
                     (define (double x) (* x 2))
                     (double (square 3))))))
(eval '(define (main)
         (define (square x) (* x x))
         (define (double x) (* x 2))
         (double (square 3))) global)
(eval '(main) global)
#+end_src

#+RESULTS:
: ((let ((square (quote *unassigned*)) (double (quote *unassigned*))) ((set! square (lambda (x) (* x x))) (set! double (lambda (x) (* x 2))) (double (square 3)))))
: ok
: 18

**** c)

Think what is the mean to add this mechanism to the language. To make inner `define` expand to parallel bindings of `let`, it's better to add it in `eval`. And this will put off the expanding to the evaluation other than parse.
If installing it to `make-procedure`, expanding would be move to parsing process.
It's not good to install it to `procedure-body` to break out abstraction barrier.

Just add the `scan-out-defines` in the `eval` of `(lambda? expr)` options.

#+begin_src racket
    [(lambda? expr)
     (make-procedure (lambda-parameters expr)
                     (scan-out-defines (lambda-body expr)) ;; here
                     env)]
#+end_src

*** 4.17

To expand

#+begin_src racket
(lambda <vars>
  (define u <e1>)
  (define v <e2>)
  <e3>)
#+end_src

into

#+begin_src racket
(lambda <vars>
  (let ((u '*unassigned*)
        (v '*unassigned*))
    (set! u <e1>)
    (set! v <e2>)
    <e3>))
#+end_src

, a new `let` scope is defined, so an extra frame is added. The system finds value from the upper frame so evaluating this would not failure.

Graphs to descript the applications of `((lambda <vars> <expr with inner defines>) <args>)`:

#+begin_src
table1 <- global:  ; nothing special
by-lambda <- E1: <vars>(<args>), u(<e1>), v(<e2>)
#+end_src

#+begin_src
table1 <- global:  ; nothing special
by-lambda <- E1: <vars>(<args>)
by-let <- E2: u(<e1>), v(<e2>)
#+end_src

To make them defines simultaneously, a natural thought is to combine inner definitions with `lambda` or `<e3>`. A viewpoint is that the new `let` bindings with `<e3>` consists to a new expr `<e4>`. In this thinking path, the only is to combine them with `lambda`.
This would transform the above example to be:

#+begin_src racket
(lambda (<vars-without-parentheses> u v)
  ; the value of `u` is `<e1>`, `v` is `<e2>`
  <e3>)
#+end_src

*** 4.18

For this transform:

#+begin_src racket
(lambda <vars>
  (let ((u '*unassigned*)
        (v '*unassigned*))
    (let ((a <e1>)
          (b <e2>))
      (set! u a)
      (set! v b))
    <e3>))
#+end_src

when evaluating `<e2>`, the `u` is not assigned. (So it's more like simultaneous assignments)

But for transform metioned in book(see Exercise 4.17 b or 4.18), when evaluating `<e2>`, `u` is assigned.

So, for this below `solve` procedure in Book 3.5.4, this transform to evaluate `solve` would raises error like `y is not defined`. But the transform mentioned in the book, this is syntax legal.

#+begin_src racket :results none
(define (solve f y0 dt)
  (define y (integral (delay dy) y0 dt))
  (define dy (stream-map f y))
  y)
#+end_src

Alike example see above of my notes with example of Book 4.1.6.

*** 4.19

Before Exercise 4.16, the expr would be evaluated to 16. This is because the system tries to find in upper environment `a` when `a` is not defined in current frame, and there's no `'*unassigned*` mechanism. If there is, it would raise an error.

#+begin_src racket
;<<eval-core-exp>>
(define global (setup-environment))

(eval '(let ((a 1))
         (define (f x)
           (define b (+ a x))
           (define a 5)
           (+ a b))
         (f 10))
      global)
#+end_src

#+RESULTS:
: +: contract violation
:   expected: number?
:   given: *unassigned*
:   context...:
:    c:\Users\asu\AppData\Local\Temp\babel-wlfyEl\org-babel-O5tnsR.rkt:58:0: eval-assignment
:    c:\Users\asu\AppData\Local\Temp\babel-wlfyEl\org-babel-O5tnsR.rkt:53:0: eval-sequence
:    body of "c:\Users\asu\AppData\Local\Temp\babel-wlfyEl\org-babel-O5tnsR.rkt"

It's weird to make it evaluates to 20, since the order of the definition is `b a` other than `a b`. To implement this, I come up with a convenient way to use error handling:

#+begin_src racket :results none
(define (f x)
  (define b (+ a x))
  (define a 5)
  (+ a b))

; pseudo code
(define (f x)
  (try (define b (+ a x))
       (unassigned-error
        (try (define a 5)
             (unassigned-error
              (raise-unassigned-error)))
        (define b (+ a x))))
  (+ a b))
#+end_src

This would expands to 2n-1 definition statements if there's n `define`s. But this requires a `try` macro which do not create a new scope and the side effect of `define`. If the body of the inner `define`s makes side effect, this method would computes wrong results!

It's avaliable to adjust the order of `define`s when parsing. Change the implementation of `let->combination` to sort it. It would be kind of complex.

*** 4.20

**** a)

To expand `(letrec ([<var> <val>] <other-bindings>) <body>)` to `(let ([<var> '*unassigned*] <other-bindings>) ((set! <var> <val>) <body-exprs>))`.

#+begin_src racket :noweb-ref eval-core-exp
(define (unzip2 pairs)
  ;<<fold>>
  (define first car)
  (define second cadr)
  (fold-right (lambda (pair acc)
                (cons (cons (first pair) (car acc))
                      (cons (second pair) (cdr acc))))
              pairs (cons nil nil)))
(define (bindings-variables-values bindings)
  (unzip2 bindings))

(define (letrec? expr)
  (tagged-list? expr 'letrec))
(define letrec-bindings cadr)
(define letrec-body cddr)
(define (letrec->let expr)
  (let ([vars-vals (bindings-variables-values (letrec-bindings expr))])
    (make-let (unassigned-bindings (car vars-vals))
              (append (map (lambda (var val) (make-assignment var val)) (car vars-vals) (cdr vars-vals))
                      (letrec-body expr)))))
#+end_src

#+begin_src racket
;<<eval-core-exp>>
(define global (setup-environment))

(define expr '(letrec ([fact
                        (lambda (n)
                          (if (= n 1) 1
                              (* n (fact (- n 1)))))])
                (fact 4)))

(letrec->let expr)
(eval expr global)
#+end_src

#+RESULTS:
: (let ((fact (quote *unassigned*))) ((set! fact (lambda (n) (if (= n 1) 1 (* n (fact (- n 1)))))) (fact 4)))
: 24

**** b)

#+begin_src racket :results none
(define (f x)
  (letrec ((even?
            (lambda (n)
              (if (= n 0)
                  true
                  (odd? (- n 1)))))
           (odd?
            (lambda (n)
              (if (= n 0)
                  false
                  (even? (- n 1))))))
    <rest of body of f>))
#+end_src

The environment when evaluating `<rest of body of f>` in `(f 5)`:

#+begin_src
table <- global: f((x), (letrec ...))
by-f <- E1: (global), x(5)
by-letrec <- E2: (E1), even?((n), ...), odd?((n), ...), <what defined in the rest of body of f>
by-even? <- E3: (E2), n(5)
#+end_src

#+begin_src
table <- global: f((x), (letrec ...))
by-f <- E1: (global), x(5)
by-let <- E2: (E1), even?((n), ...), odd?((n), ...), <what defined in the rest of body of f>
by-even? <- E3: (E1), n(5)
#+end_src

The only difference is that the inner procedure calling would inherit different environment.

*** 4.21

Wow, it's lambda calculus.

#+begin_src racket
((lambda (n)
   ((lambda (fact)
      (fact fact n))
    (lambda (ft k)
      (if (= k 1)
          1
          (* k (ft ft (- k 1)))))))
 10)
#+end_src

#+RESULTS:
: 3628800

**** a)

I try to refactor it to a understandable form.

#+begin_src racket
(define (factorial n)
  (define (b ft k)
    (if (= k 1)
        1
        (* k (ft ft (- k 1)))))
  (b b n))
(factorial 10)
#+end_src

#+RESULTS:
: 3628800

The `(lambda (n) ...)` to memorize the value of n, the `(lambda (fact) (fact fact n))` to use the `fact` twice. The `(lambda (ft k) ...)` calling it self to recurse.

**** b)

#+begin_src racket
(define (f x)
  ((lambda (even? odd?)
     (even? even? odd? x))
   (lambda (ev? od? n)
     (if (= n 0) true (od? ev? od? (- n 1))))
   (lambda (ev? od? n)
     (if (= n 0) false (ev? ev? od? (- n 1))))))

(f 5) ; => #f
(map f (list 1 3 5 7 2 4 6 8))
#+end_src

#+RESULTS:
: #f
: (#f #f #f #f #t #t #t #t)

* Helper functions

#+begin_src racket :noweb-ref sicp
(define (sicp m)
  (define (square x) (* x x))
  (define (average a b) (/ (+ a b) 2))
  (define (displayln x) (display x) (newline))

  (cond
    [(eq? m 'square) square]
    [(eq? m 'average) average]
    [(eq? m 'displayln) displayln]
    [else (error "Unknown procedure -- SICP")]))
#+end_src

#+begin_src racket :noweb-ref higher-order
(define (F m)
  (define (id x) x)
  (define (partial f . args1)
    (lambda args2 (apply f (append args1 args2))))
  (define (compose . f1s) ; functions in f-s only need one argument
    (if (null? f1s) id
        (lambda (x) ((apply compose (cdr f1s)) (apply (car f1s) (list x))))))
  (define (flip f2) (lambda (x y) (f2 y x)))

  (cond
    [(eq? m 'id) id]
    [(eq? m 'partial) partial]
    [(eq? m 'compose) compose]
    [(eq? m 'flip) flip]
    [else (error "Unknown procedure -- F" m)]))
#+end_src

#+begin_src racket :noweb-ref fold
(define (fold-left f acc lst)
  (if (null? lst) acc
      (fold-left f (f (car lst) acc) (cdr lst))))

(define (fold-right f lst acc)
  (if (null? lst) acc
      (f (car lst) (fold-right f (cdr lst) acc))))
#+end_src

* COMMENT Local Variables
# Local Variables:
# org-babel-noweb-wrap-start: ";<<"
# org-babel-noweb-wrap-end: ">>"
# End:
